# Generated by GitHub Copilot
"""
brampton.py — BRT Fleet Movement Script.

This is the authoritative fleet movement executor, refactored from the original
nightly brampton.py script. It is invoked as a governed tool via the
brampton_mcp_server and should never be called directly by the agent.

Responsibilities:
  - Accept a list of IntendedMove objects (as JSON)
  - MOCK mode: simulate moves, return what WOULD happen (no SOTI calls)
  - LIVE mode: call SOTI REST API directly per device (search → move → verify)
  - Write the 5-tab output workbook (mirrors original brampton.py output)
  - Return a structured result dict: {moved, unmoved, unidentified, workbook_path}

SOTI API calls use the same credentials as soti_mcp_server (.env in this folder).
"""

import json
import logging
import os
import time
from typing import Any, Optional

import httpx
from dotenv import load_dotenv

load_dotenv(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".env"))

logger = logging.getLogger(__name__)

# ── SOTI folder field extraction ────────────────────────────────────────────
_FOLDER_FIELDS = (
    "CurrentGroupPath", "currentGroupPath",
    "DeviceGroupPath",  "deviceGroupPath",
    "GroupPath",        "groupPath",
    "CurrentGroup",     "currentGroup",
    "PathToDevice",     "pathToDevice",
    "folder", "Path", "path",
)


def _extract_folder(device_info: dict) -> str:
    """Extract current folder/group path from a SOTI device response dict."""
    if not device_info:
        return "UNKNOWN"
    for field in _FOLDER_FIELDS:
        value = device_info.get(field)
        if value:
            return str(value)
    return "UNKNOWN"


# ── SOTI credentials (loaded from brampton_mcp_server/.env) ─────────────────
SOTI_BASE_URL      = os.getenv("SOTI_BASE_URL", "").rstrip("/")
SOTI_USERNAME      = os.getenv("SOTI_USERNAME", "")
SOTI_PASSWORD      = os.getenv("SOTI_PASSWORD", "")
SOTI_CLIENT_ID     = os.getenv("SOTI_CLIENT_ID", "")
SOTI_CLIENT_SECRET = os.getenv("SOTI_CLIENT_SECRET", "")
SOTI_GRANT_TYPE    = os.getenv("SOTI_GRANT_TYPE", "password")


# ── SOTI auth helpers (inline — brampton.py calls SOTI directly, not via MCP) ─

class _TokenStore:
    def __init__(self):
        self.token: Optional[str] = None
        self.expires_at: float = 0.0

    def is_valid(self, buffer: int = 30) -> bool:
        return self.token is not None and time.time() < (self.expires_at - buffer)

    def store(self, token: str, expires_in: int):
        self.token = token
        self.expires_at = time.time() + expires_in


_token_store = _TokenStore()


async def _get_http() -> httpx.AsyncClient:
    """Return a shared AsyncClient (self-signed cert tolerance for test host)."""
    return httpx.AsyncClient(verify=False, timeout=httpx.Timeout(30.0))


async def _ensure_token(http: httpx.AsyncClient) -> None:
    """Acquire / refresh bearer token if needed."""
    if _token_store.is_valid():
        return

    # Try OAuth2 endpoint first
    oauth_url = SOTI_BASE_URL.replace("/MobiControl/api", "/MobiControl/oauth/token")
    payload = {
        "grant_type":    SOTI_GRANT_TYPE,
        "username":      SOTI_USERNAME,
        "password":      SOTI_PASSWORD,
        "client_id":     SOTI_CLIENT_ID,
        "client_secret": SOTI_CLIENT_SECRET,
    }
    try:
        r = await http.post(oauth_url, data=payload)
        r.raise_for_status()
        d = r.json()
        _token_store.store(d["access_token"], int(d.get("expires_in", 3600)))
        logger.info("SOTI token acquired via /oauth/token")
        return
    except Exception as exc:
        logger.warning("OAuth token failed, trying legacy: %s", exc)

    # Fallback: legacy /api/token
    api_url = f"{SOTI_BASE_URL}/token"
    r = await http.post(api_url, data=payload)
    r.raise_for_status()
    d = r.json()
    _token_store.store(d["access_token"], int(d.get("expires_in", 3600)))
    logger.info("SOTI token acquired via /api/token")


async def _soti_request(
    http: httpx.AsyncClient, method: str, path: str, **kwargs
) -> Any:
    """Make an authenticated SOTI API call."""
    await _ensure_token(http)
    url = f"{SOTI_BASE_URL}/{path.lstrip('/')}"
    headers = {
        "Authorization": f"Bearer {_token_store.token}",
        "Content-Type":  "application/json",
        "Accept":        "application/json",
    }
    r = await http.request(method, url, headers=headers, **kwargs)
    r.raise_for_status()
    if r.status_code == 204 or not r.content:
        return {"status": "success"}
    return r.json()


BRT_GROUP_PATH = os.getenv(
    "SOTI_BRT_GROUP_PATH",
    "//Presto/Brampton Transit(BRT)/1.Production",
)


async def _build_device_lookup(http: httpx.AsyncClient) -> dict[str, dict]:
    """
    Search SOTI devices by BRT group path and return a name-keyed lookup dict.
    { lowercased_device_name -> device_dict }

    Uses GET /api/devices/search?groupPath=<BRT_PATH> instead of GET /api/devices
    because get_all_devices is paginated (~100 devices) and the BRT buses (1800+)
    are not in the first page. Group-path search returns exactly the BRT devices.
    Searches both Production and LTM sub-folders if SOTI_BRT_GROUP_PATH points to
    the common BRT parent.
    """
    lookup: dict[str, dict] = {}
    try:
        data = await _soti_request(
            http, "GET", "/devices", params={"top": 5000, "skip": 0}
        )
        devices = data if isinstance(data, list) else (
            data.get("devices") or data.get("Devices") or data.get("items") or []
        )
        if not devices:
            logger.warning(
                "SOTI get_all_devices(top=5000) returned no devices. Keys: %s",
                list(data.keys()) if isinstance(data, dict) else type(data).__name__,
            )
            return {}
        brt_devices = [
            d for d in devices
            if str(d.get("DeviceName") or d.get("deviceName") or d.get("Name") or "")
               .upper().startswith("BRT_")
        ]
        logger.info(
            "SOTI get_all_devices: %d total, %d BRT devices",
            len(devices), len(brt_devices),
        )
        for dev in brt_devices:
            for field in ("DeviceName", "deviceName", "Name", "name", "ReferenceId"):
                name = dev.get(field)
                if name:
                    lookup[str(name).lower()] = dev
                    break
        return lookup
    except Exception as exc:
        logger.error("SOTI device fetch failed: %s", exc)
        return {}


def _lookup_device(lookup: dict[str, dict], device_name: str) -> dict:
    """Find a device in the pre-built lookup dict by name (case-insensitive)."""
    return lookup.get(device_name.lower(), {})


async def _move_device(http: httpx.AsyncClient, device_id: str, parent_path: str) -> dict:
    """PUT /api/devices/{deviceId}/parentPath"""
    try:
        return await _soti_request(
            http, "PUT", f"/devices/{device_id}/parentPath",
            json=parent_path,
        )
    except Exception as exc:
        logger.error("SOTI move_device(%s → %s) failed: %s", device_id, parent_path, exc)
        raise


# ── Core fleet movement logic ────────────────────────────────────────────────

async def run_fleet_movement(
    run_id: str,
    intended_moves: list[dict],
    mode: str,
    output_dir: str,
) -> dict:
    """
    Execute fleet device movements.

    Parameters
    ----------
    run_id         : Unique run identifier (e.g. "BRT-2026-05-27")
    intended_moves : List of IntendedMove dicts with keys:
                     current_device, target_folder, bus_number, vehicle_status
    mode           : "MOCK" (simulate only) | "LIVE" (call SOTI API)
    output_dir     : Directory where the 5-tab workbook is written

    Returns
    -------
    dict with keys: moved, unmoved, unidentified, workbook_path, mode
    """
    mode = mode.upper()
    logger.info("brampton.py — run_id=%s mode=%s devices=%d", run_id, mode, len(intended_moves))

    moved: list[dict] = []
    unmoved: list[dict] = []
    unidentified: list[dict] = []

    if mode == "MOCK":
        # Simulate: assume all moves would succeed (no SOTI calls)
        for m in intended_moves:
            moved.append({
                "device":      m["current_device"],
                "bus_number":  m.get("bus_number", ""),
                "from_folder": "CURRENT_SOTI_FOLDER",
                "to_folder":   m["target_folder"],
                "mock":        True,
            })
        logger.info("MOCK run complete — %d moves simulated", len(moved))

    else:
        # LIVE: call SOTI REST API for each device
        async with httpx.AsyncClient(verify=False, timeout=httpx.Timeout(30.0)) as http:
            # Build device lookup once — replaces per-device search calls
            device_lookup = await _build_device_lookup(http)
            if not device_lookup:
                logger.error("SOTI bulk lookup returned empty — cannot move any devices")

            for m in intended_moves:
                device_name   = m["current_device"]
                target_folder = m["target_folder"]
                bus_number    = m.get("bus_number", "")

                # Step 1 — resolve device name → device ID from bulk lookup
                device_info = _lookup_device(device_lookup, device_name)
                if not device_info:
                    unidentified.append({
                        "device":      device_name,
                        "bus_number":  bus_number,
                        "reason":      "device not found in SOTI",
                    })
                    logger.warning("Device not found in SOTI: %s", device_name)
                    continue

                device_id = (
                    device_info.get("DeviceId")
                    or device_info.get("deviceId")
                    or device_info.get("id")
                    or device_info.get("DeviceID")
                    or ""
                )
                if not device_id:
                    unidentified.append({
                        "device":      device_name,
                        "bus_number":  bus_number,
                        "reason":      f"device found but DeviceId missing — keys: {list(device_info.keys())}",
                    })
                    continue

                current_folder = _extract_folder(device_info)

                # Step 2 — move device
                try:
                    await _move_device(http, device_id, target_folder)
                except Exception as exc:
                    unmoved.append({
                        "device":           device_name,
                        "bus_number":       bus_number,
                        "intended_folder":  target_folder,
                        "reason":           f"SOTI move failed: {exc}",
                    })
                    continue

                # Step 3 — immediate verify: read back actual folder
                # Re-fetch the single device info after move via group path search
                post_info = _lookup_device(device_lookup, device_name)
                actual_folder = _extract_folder(post_info)

                if actual_folder.lower() == target_folder.lower():
                    moved.append({
                        "device":      device_name,
                        "bus_number":  bus_number,
                        "from_folder": current_folder,
                        "to_folder":   actual_folder,
                    })
                else:
                    unmoved.append({
                        "device":          device_name,
                        "bus_number":      bus_number,
                        "intended_folder": target_folder,
                        "actual_folder":   actual_folder,
                        "reason":          f"post-move verify failed: actual='{actual_folder}' expected='{target_folder}'",
                    })

        logger.info(
            "LIVE run complete — moved=%d unmoved=%d unidentified=%d",
            len(moved), len(unmoved), len(unidentified),
        )

    # Write the 5-tab output workbook
    workbook_path = _write_workbook(run_id, intended_moves, moved, unmoved, unidentified, output_dir)

    return {
        "run_id":        run_id,
        "mode":          mode,
        "moved":         moved,
        "unmoved":       unmoved,
        "unidentified":  unidentified,
        "workbook_path": workbook_path,
    }


# ── 5-tab output workbook ────────────────────────────────────────────────────

def _write_workbook(
    run_id: str,
    intended_moves: list[dict],
    moved: list[dict],
    unmoved: list[dict],
    unidentified: list[dict],
    output_dir: str,
) -> str:
    """
    Write the 5-tab output workbook that mirrors the original brampton.py output.

    Tabs:
      1. Moved to LTM
      2. Failed → LTM
      3. Moved to Production
      4. Failed → Production
      5. Unidentified
    """
    try:
        import openpyxl
        from openpyxl import Workbook
        from openpyxl.styles import Alignment, Font, PatternFill
        from openpyxl.utils import get_column_letter

        os.makedirs(output_dir, exist_ok=True)
        path = os.path.join(output_dir, f"BRT_FleetMovement_{run_id}.xlsx")

        # Build target lookup from intended_moves
        target_by_device: dict[str, str] = {
            m["current_device"]: m["target_folder"] for m in intended_moves
        }

        def _is_ltm(folder: str) -> bool:
            return "ltm" in folder.lower()

        moved_ltm  = [m for m in moved  if _is_ltm(m.get("to_folder", ""))]
        moved_prod = [m for m in moved  if not _is_ltm(m.get("to_folder", ""))]
        fail_ltm   = [u for u in unmoved if _is_ltm(target_by_device.get(u.get("device", ""), ""))]
        fail_prod  = [u for u in unmoved if not _is_ltm(target_by_device.get(u.get("device", ""), ""))]

        wb = Workbook()

        def _header(ws, colour: str) -> None:
            fill = PatternFill("solid", fgColor=colour)
            bold = Font(bold=True, color="FFFFFF")
            for cell in ws[1]:
                cell.fill = fill
                cell.font = bold
                cell.alignment = Alignment(horizontal="center")
            for col in ws.columns:
                length = max(len(str(c.value or "")) for c in col) + 4
                ws.column_dimensions[get_column_letter(col[0].column)].width = min(length, 50)

        ws1 = wb.active
        ws1.title = "Moved to LTM"
        ws1.append(["Device", "Bus #", "From Folder", "To Folder", "Run ID"])
        for r in moved_ltm:
            ws1.append([r.get("device"), r.get("bus_number"), r.get("from_folder"), r.get("to_folder"), run_id])
        _header(ws1, "1F7A4D")

        ws2 = wb.create_sheet("Failed - LTM")
        ws2.append(["Device", "Bus #", "Intended Folder", "Reason", "Run ID"])
        for r in fail_ltm:
            ws2.append([r.get("device"), r.get("bus_number"), target_by_device.get(r.get("device", ""), "LTM"), r.get("reason"), run_id])
        _header(ws2, "C0392B")

        ws3 = wb.create_sheet("Moved to Production")
        ws3.append(["Device", "Bus #", "From Folder", "To Folder", "Run ID"])
        for r in moved_prod:
            ws3.append([r.get("device"), r.get("bus_number"), r.get("from_folder"), r.get("to_folder"), run_id])
        _header(ws3, "1A5276")

        ws4 = wb.create_sheet("Failed - Production")
        ws4.append(["Device", "Bus #", "Intended Folder", "Reason", "Run ID"])
        for r in fail_prod:
            ws4.append([r.get("device"), r.get("bus_number"), target_by_device.get(r.get("device", ""), "Production"), r.get("reason"), run_id])
        _header(ws4, "884EA0")

        ws5 = wb.create_sheet("Unidentified")
        ws5.append(["Device", "Bus #", "Reason", "Run ID"])
        for r in unidentified:
            ws5.append([r.get("device"), r.get("bus_number"), r.get("reason"), run_id])
        _header(ws5, "717D7E")

        wb.save(path)
        logger.info("5-tab workbook written: %s", path)
        return path

    except Exception as exc:
        logger.error("Failed to write workbook: %s", exc)
        return ""
