# Generated by GitHub Copilot
"""
BRT Fleet Movement MCP Server.

Exposes one tool: run_fleet_movement
  - Wraps brampton.py logic (the fleet movement script)
  - Called by the fleet-agents orchestrator (never by a human directly)
  - Supports MOCK mode (dry-run preview) and LIVE mode (real SOTI API calls)

Transport: stdio (launched as subprocess by fleet-agents/mcp_clients/fleet_client.py)
"""

import asyncio
import json
import logging
import os
import sys

# Load .env before any os.getenv() calls inside brampton.py
from dotenv import load_dotenv
load_dotenv()

import mcp.server.stdio
import mcp.types as types
from mcp.server import Server

from brampton import run_fleet_movement

logging.basicConfig(level=logging.INFO, stream=sys.stderr)
logger = logging.getLogger(__name__)

app = Server("brt-fleet-movement")

# ── Tool definition ──────────────────────────────────────────────────────────

TOOL_RUN_FLEET_MOVEMENT = types.Tool(
    name="run_fleet_movement",
    description=(
        "Execute BRT fleet device movements in SOTI MobiControl. "
        "MOCK mode simulates moves without touching SOTI (for pre-move preview). "
        "LIVE mode calls the SOTI API directly (search → move → verify per device). "
        "Writes the 5-tab output workbook and returns a structured result JSON."
    ),
    inputSchema={
        "type": "object",
        "properties": {
            "run_id": {
                "type": "string",
                "description": "Unique run identifier, e.g. BRT-2026-05-27",
            },
            "intended_moves_json": {
                "type": "string",
                "description": (
                    "JSON array of IntendedMove objects, each with: "
                    "current_device, target_folder, bus_number, vehicle_status"
                ),
            },
            "mode": {
                "type": "string",
                "enum": ["MOCK", "LIVE"],
                "description": "MOCK = dry-run preview; LIVE = real SOTI API calls",
            },
            "output_dir": {
                "type": "string",
                "description": "Absolute path to write the 5-tab output workbook",
            },
        },
        "required": ["run_id", "intended_moves_json", "mode", "output_dir"],
    },
)


@app.list_tools()
async def list_tools() -> list[types.Tool]:
    return [TOOL_RUN_FLEET_MOVEMENT]


@app.call_tool()
async def call_tool(name: str, arguments: dict) -> list[types.TextContent]:
    if name != "run_fleet_movement":
        raise ValueError(f"Unknown tool: {name}")

    run_id     = arguments["run_id"]
    mode       = arguments.get("mode", "MOCK").upper()
    output_dir = arguments.get("output_dir", ".")

    try:
        intended_moves = json.loads(arguments["intended_moves_json"])
    except json.JSONDecodeError as exc:
        return [types.TextContent(
            type="text",
            text=json.dumps({"error": f"Invalid intended_moves_json: {exc}"}),
        )]

    logger.info("run_fleet_movement called — run_id=%s mode=%s moves=%d",
                run_id, mode, len(intended_moves))

    try:
        result = await run_fleet_movement(
            run_id=run_id,
            intended_moves=intended_moves,
            mode=mode,
            output_dir=output_dir,
        )
        return [types.TextContent(type="text", text=json.dumps(result, default=str))]
    except Exception as exc:
        logger.error("run_fleet_movement failed: %s", exc, exc_info=True)
        return [types.TextContent(
            type="text",
            text=json.dumps({"error": str(exc), "run_id": run_id, "mode": mode}),
        )]


async def main():
    async with mcp.server.stdio.stdio_server() as (read_stream, write_stream):
        logger.info("BRT Fleet Movement MCP Server started")
        await app.run(
            read_stream,
            write_stream,
            app.create_initialization_options(),
        )


if __name__ == "__main__":
    asyncio.run(main())
