# Generated by GitHub Copilot
"""
BaseAgent wraps Azure OpenAI chat-completions calls via the openai SDK.
USE_MOCK_LLM=True bypasses all network calls; set False once API key is in .env.

Pattern: all agents are narrators — they receive structured JSON and return
plain-English prose.  No tool calls happen inside agents.
"""
import json
import logging

import config

log = logging.getLogger(__name__)


class BaseAgent:
    """
    Thin wrapper around Azure OpenAI chat completions (openai SDK).
    Subclasses override _system_prompt() and _mock_narration().
    """

    def __init__(self, name: str):
        self.name = name
        self._client = None  # lazy-initialised on first real call

    def _get_client(self):
        """Return (and cache) an OpenAI client pointed at the Azure endpoint."""
        if self._client is None:
            if not config.AZURE_OPENAI_API_KEY:
                raise RuntimeError(
                    "AZURE_OPENAI_API_KEY is not set in .env — "
                    "add the key and set USE_MOCK_LLM=false."
                )
            from openai import OpenAI  # imported lazily to keep startup fast
            self._client = OpenAI(
                base_url=config.AZURE_OPENAI_ENDPOINT_V1,
                api_key=config.AZURE_OPENAI_API_KEY,
            )
        return self._client

    def _system_prompt(self) -> str:
        """Override in each subclass with a domain-specific system instruction."""
        return (
            "You are an AI assistant that produces concise operational summaries "
            "for a bus fleet management system. Respond in plain English only."
        )

    def narrate(self, structured_input: dict) -> str:
        """
        Send structured_input to Azure OpenAI and return the prose response.
        Falls back to _mock_narration when USE_MOCK_LLM is True.
        """
        if config.USE_MOCK_LLM:
            return self._mock_narration(structured_input)

        client = self._get_client()
        user_content = json.dumps(structured_input, default=str, indent=2)

        log.debug("Narrating via Azure OpenAI | agent=%s", self.name)
        response = client.chat.completions.create(
            model=config.AZURE_OPENAI_DEPLOYMENT,
            messages=[
                {"role": "system", "content": self._system_prompt()},
                {"role": "user",   "content": user_content},
            ],
            max_tokens=1024,
            temperature=0.3,
        )
        return response.choices[0].message.content or f"[{self.name}] Empty response."

    def _mock_narration(self, data: dict) -> str:
        """Override in each subclass with a realistic domain-specific stub."""
        return f"[MOCK] {self.name} narration for keys: {list(data.keys())}"
