# Generated by GitHub Copilot
"""
ErrorTriageAgent — diagnoses a failed pipeline step (e.g. a SOTI move error in
Stage 4) and recommends retry vs escalate, plus a short incident note.
Advisory only — the human still makes the skip/retry/abort decision at HITL-Error.
"""
from .base_agent import BaseAgent


class ErrorTriageAgent(BaseAgent):
    """Diagnoses a failed step and recommends a next action for the L2 operator."""

    def __init__(self):
        super().__init__("brt-error-triage-v1")

    def _system_prompt(self) -> str:
        return (
            "You are an incident-response analyst for the Brampton Transit (BRT) fleet "
            "movement automation. You receive structured JSON describing a step that "
            "failed during a run: the failing component, the error message, and the run "
            "ID. Produce a short diagnosis (2-4 sentences) that: (1) states the most "
            "likely root cause in plain English, (2) recommends RETRY or ESCALATE with a "
            "one-line justification, and (3) gives a one-sentence incident note an "
            "operator could paste into a ticket. Do not invent details not present in "
            "the input. No JSON, no code blocks."
        )

    def _mock_narration(self, data: dict) -> str:
        component = data.get("component", "unknown step")
        error = data.get("error", "")
        run_id = data.get("run_id", "UNKNOWN")
        err_lower = error.lower()
        if any(k in err_lower for k in ("timeout", "connection", "timed out", "unreachable")):
            cause = "a transient network/connectivity issue reaching SOTI"
            rec = "RETRY — transient errors usually clear on a second attempt"
        elif any(k in err_lower for k in ("401", "403", "token", "auth", "unauthorized")):
            cause = "an authentication/authorization failure with the SOTI API"
            rec = "ESCALATE — credentials or token scope likely need attention"
        elif any(k in err_lower for k in ("404", "not found")):
            cause = "a missing resource (device or endpoint not found in SOTI)"
            rec = "ESCALATE — verify device enrolment and API path before retrying"
        else:
            cause = "an unexpected error during execution"
            rec = "RETRY once; if it recurs, ESCALATE"
        return (
            f"Diagnosis: {component} failed, most likely due to {cause}. "
            f"Recommendation: {rec}. "
            f"Incident note: Run {run_id} — {component} failed with: "
            f"{error[:200] or 'no error detail provided'}."
        )
