# Generated by GitHub Copilot
"""
ExceptionTriageAgent — reasons about devices that don't behave cleanly:
  - Stage 2b: devices not found in SOTI (UNKNOWN) and stale LTM_ rename tags
  - Stage 5 : reconciliation residuals (unmoved / unidentified devices)

The LLM classifies probable cause and suggests a fix in plain English.
It NEVER changes data or makes movement decisions — triage is advisory only.
All move/verify logic stays in core/ (pure Python).
"""
from .base_agent import BaseAgent


class ExceptionTriageAgent(BaseAgent):
    """Diagnoses exception devices and suggests probable cause + remediation."""

    def __init__(self):
        super().__init__("brt-exception-triage-v1")

    def _system_prompt(self) -> str:
        return (
            "You are a SOTI MobiControl operations analyst for the Brampton Transit "
            "(BRT) bus fleet. You receive structured JSON describing devices that did "
            "not behave cleanly during a fleet movement run: devices not found in SOTI, "
            "stale LTM rename tags, or devices that failed to move. "
            "For each distinct problem pattern, briefly explain the PROBABLE CAUSE and a "
            "SUGGESTED FIX an L2 operator can act on (e.g. device not enrolled, naming "
            "mismatch between DVA and SOTI, device offline, stale LTM_ prefix needing "
            "cleanup). Group similar cases together rather than repeating per device. "
            "Be concise (4-8 sentences total). Plain English only — no JSON, no code."
        )

    def _mock_narration(self, data: dict) -> str:
        stage = data.get("stage", "unknown")
        unknown = data.get("unknown", [])
        stale = data.get("stale_ltm", [])
        unmoved = data.get("unmoved", [])
        unidentified = data.get("unidentified", [])

        parts: list[str] = [f"Exception triage ({stage}):"]
        if unknown:
            parts.append(
                f"{len(unknown)} device(s) were not found in the SOTI bulk lookup. "
                f"Probable cause: the device is not enrolled, or its DeviceName in SOTI "
                f"does not match the DVA-derived name (BRT_DCU_<bus>_1 / BRT_BFTP_<bus>_1). "
                f"Suggested fix: confirm enrolment and verify the naming convention in SOTI."
            )
        if stale:
            parts.append(
                f"{len(stale)} device(s) carry a stale LTM_ rename tag while the DVA says "
                f"Production. Probable cause: a prior LTM move left the LTM_ prefix in place. "
                f"Suggested fix: the pipeline targets the LTM_-prefixed name so the move "
                f"corrects this — verify the device lands in Production after the run."
            )
        if unmoved:
            reasons = "; ".join(d.get("reason", "?") for d in unmoved[:3])
            parts.append(
                f"{len(unmoved)} device(s) failed to move ({reasons}). Probable cause: the "
                f"device may be offline or the SOTI move API returned an error. "
                f"Suggested fix: retry the affected devices or check device connectivity."
            )
        if unidentified:
            parts.append(
                f"{len(unidentified)} device(s) could not be identified in SOTI and need "
                f"manual investigation."
            )
        if len(parts) == 1:
            parts.append("No exceptions to triage — all devices behaved as expected.")
        return " ".join(parts)
