# Generated by GitHub Copilot
"""
ExecutionNarrator — drafts SR notes and summary email for the SR closure gate.
LLM is used ONLY for prose; run_id and device list come from deterministic code.
"""
from .base_agent import BaseAgent


class ExecutionNarrator(BaseAgent):
    """Drafts ServiceNow SR notes and summary email body."""

    def __init__(self):
        super().__init__("brt-execution-narrator-v1")

    def _system_prompt(self) -> str:
        return (
            "You are an operations assistant for a transit agency bus fleet management system. "
            "You receive structured JSON describing a completed BRT fleet device movement run: "
            "the run ID, successfully moved devices, and any failures. "
            "Draft two things: (1) a concise ServiceNow SR closure note (2-3 sentences), "
            "and (2) a brief summary email body (Subject + 3-4 sentence body). "
            "Use professional, clear language. Do not include JSON in your response."
        )

    def _mock_narration(self, data: dict) -> str:
        moved = data.get("moved", [])
        run_id = data.get("run_id", "UNKNOWN")
        devices = ", ".join(d.get("device", "?") for d in moved) or "none"
        return (
            f"SR Notes (auto-generated | run {run_id}):\n\n"
            f"BRT Fleet device movement operation completed successfully.\n"
            f"Devices moved: {devices}.\n"
            f"All devices confirmed in target SOTI folders via automated "
            f"reconciliation. No manual intervention required.\n\n"
            f"--- Summary Email ---\n"
            f"Subject: BRT Fleet Movement Complete — {run_id}\n"
            f"Body: The scheduled BRT Fleet device movement for run {run_id} "
            f"has completed. {len(moved)} device(s) were successfully relocated "
            f"in SOTI. Please see the attached run document for full details."
        )
