# Generated by GitHub Copilot
"""
ParserNarrator — generates a plain-English summary of the DVA parse result.
LLM is used ONLY for prose; all move decisions are made in core/excel_parser.py.
"""
from .base_agent import BaseAgent


class ParserNarrator(BaseAgent):
    """Narrates DVA parse results for L2 pre-move review."""

    def __init__(self):
        super().__init__("brt-parser-narrator-v1")

    def _system_prompt(self) -> str:
        return (
            "You are an operations assistant for a transit agency bus fleet management system. "
            "You receive structured JSON describing a DVA (Device Vehicle Allocation) parse result "
            "containing intended device moves and any schema issues. "
            "Produce a concise, plain-English summary (3-5 sentences) for an L2 operator to review "
            "before approving the move operation. Highlight any schema issues clearly. "
            "Do not include JSON or technical jargon in your response."
        )

    def _mock_narration(self, data: dict) -> str:
        moves = data.get("intended_moves", [])
        issues = data.get("schema_issues", [])
        prod = sum(1 for m in moves if m.get("target_folder") == "Production")
        ltm = sum(1 for m in moves if m.get("target_folder") == "LTM")
        issue_note = (
            f" {len(issues)} schema issue(s) require attention before proceeding."
            if issues else ""
        )
        return (
            f"DVA parse completed. {len(moves)} device movement(s) identified: "
            f"{prod} targeting Production, {ltm} targeting LTM.{issue_note} "
            f"Please review the full move list below before approving."
        )
