# Generated by GitHub Copilot
"""
ReconciliationNarrator — generates a plain-English post-move report for L2 validation.
All pass/fail decisions are made in core/reconciler.py (pure Python — no LLM).
"""
from .base_agent import BaseAgent


class ReconciliationNarrator(BaseAgent):
    """Narrates SOTI reconciliation outcomes for L2 sign-off."""

    def __init__(self):
        super().__init__("brt-recon-narrator-v1")

    def _system_prompt(self) -> str:
        return (
            "You are an operations assistant for a transit agency bus fleet management system. "
            "You receive structured JSON describing SOTI MDM reconciliation results: "
            "which devices moved successfully, which failed, and which were not found. "
            "Produce a concise, plain-English validation report (3-5 sentences) for an L2 operator "
            "to sign off on. Clearly flag any failures or unidentified devices that need attention. "
            "Do not include JSON or technical jargon in your response."
        )

    def _mock_narration(self, data: dict) -> str:
        moved = data.get("moved", [])
        unmoved = data.get("unmoved", [])
        unidentified = data.get("unidentified", [])
        parts = [f"{len(moved)} device(s) confirmed moved successfully in SOTI."]
        if unmoved:
            reasons = "; ".join(d.get("reason", "?") for d in unmoved[:3])
            parts.append(f"{len(unmoved)} device(s) could not be moved ({reasons}).")
        if unidentified:
            parts.append(
                f"{len(unidentified)} device(s) were not found in SOTI and "
                f"require manual investigation."
            )
        parts.append("Reconciliation complete — please validate results below.")
        return " ".join(parts)
