# Generated by GitHub Copilot
"""
RunSummaryNarrator — composes a stakeholder summary email at run completion.
LLM is used ONLY for prose; all counts come from the deterministic reconciliation.
This replaces the SR-closure narrative that was removed from the pipeline.
"""
from .base_agent import BaseAgent


class RunSummaryNarrator(BaseAgent):
    """Drafts the end-of-run stakeholder summary email (Subject + body)."""

    def __init__(self):
        super().__init__("brt-run-summary-v1")

    def _system_prompt(self) -> str:
        return (
            "You are an operations assistant for the Brampton Transit (BRT) bus fleet. "
            "You receive structured JSON describing a completed device-movement run: the "
            "run ID, how many devices moved to Production vs LTM, and any exceptions. "
            "Write a brief stakeholder summary email: a one-line Subject, then a 3-5 "
            "sentence body suitable for transit operations management. State the outcome "
            "clearly, call out anything needing follow-up, and keep the tone professional. "
            "Do not include JSON, code, or device-by-device lists."
        )

    def _mock_narration(self, data: dict) -> str:
        run_id = data.get("run_id", "UNKNOWN")
        moved = data.get("moved", [])
        unmoved = data.get("unmoved", [])
        unidentified = data.get("unidentified", [])
        to_prod = sum(1 for m in moved if "LTM" not in str(m.get("to_folder", "")).upper())
        to_ltm = len(moved) - to_prod
        follow_up = len(unmoved) + len(unidentified)
        follow_note = (
            f" {follow_up} device(s) require follow-up and are listed in the run document."
            if follow_up else " No exceptions — all moves verified successfully."
        )
        return (
            f"Subject: BRT Fleet Movement Complete — {run_id}\n\n"
            f"The scheduled BRT fleet device movement for run {run_id} has completed. "
            f"{len(moved)} device(s) were successfully relocated in SOTI "
            f"({to_prod} to Production, {to_ltm} to LTM).{follow_note} "
            f"Full reconciliation details and the 5-tab workbook are available in the "
            f"ops dashboard for this run."
        )
