// Generated by GitHub Copilot
import type { RunDoc, PendingGate, WorkbookTabs, DecisionForm } from './types';

const BASE = '/api';

async function get<T>(path: string): Promise<T> {
  const res = await fetch(`${BASE}${path}`);
  if (!res.ok) throw new Error(`HTTP ${res.status} — ${path}`);
  return res.json() as Promise<T>;
}

/** Fetch all runs, newest first. */
export const fetchRuns = (): Promise<RunDoc[]> => get('/runs');

/** Fetch a single run by ID. */
export const fetchRun = (runId: string): Promise<RunDoc> => get(`/runs/${runId}`);

/** Fetch the pending HITL gate for a run, or { status: 'none' } if none. */
export const fetchPending = (runId: string): Promise<PendingGate | { status: 'none' }> =>
  get(`/runs/${runId}/pending`);

/** Fetch the 5-tab output workbook as JSON (tab → rows). */
export const fetchWorkbook = (runId: string): Promise<WorkbookTabs> =>
  get(`/runs/${runId}/workbook`);

/** Submit an L2 HITL decision. */
export async function submitDecision(runId: string, form: DecisionForm): Promise<void> {
  const body = new URLSearchParams({
    gate: form.gate,
    decision: form.decision,
    note: form.note,
    subset_indices: form.subset_indices,
  });
  const res = await fetch(`${BASE}/runs/${runId}/decision`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
    body: body.toString(),
  });
  if (!res.ok) throw new Error(`Decision submit failed: HTTP ${res.status}`);
}
