// Generated by GitHub Copilot
import { useState, useEffect, useCallback } from 'react'
import { fetchRuns } from './api'
import type { RunDoc } from './types'
import RunCard from './components/RunCard'

function Header({ onRefresh, lastUpdated }: { onRefresh: () => void; lastUpdated: Date | null }) {
  return (
    <header className="bg-slate-900 text-white shadow-lg">
      <div className="max-w-screen-xl mx-auto px-6 py-4 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-8 h-8 bg-blue-500 rounded-lg flex items-center justify-center font-bold text-sm">BRT</div>
          <div>
            <h1 className="font-bold text-lg leading-none">Fleet Ops Dashboard</h1>
            <p className="text-slate-400 text-xs mt-0.5">Brampton Transit · SOTI Device Movement</p>
          </div>
        </div>
        <div className="flex items-center gap-4">
          {lastUpdated && (
            <span className="text-slate-400 text-xs">
              Updated {lastUpdated.toLocaleTimeString()}
            </span>
          )}
          <button
            onClick={onRefresh}
            className="bg-slate-700 hover:bg-slate-600 text-white text-sm px-3 py-1.5 rounded transition-colors"
            aria-label="Refresh runs"
          >
            ↻ Refresh
          </button>
        </div>
      </div>
    </header>
  )
}

function SummaryBar({ runs }: { runs: RunDoc[] }) {
  const total = runs.length
  const active = runs.filter(r => !['COMPLETED', 'ABORTED', 'FAILED'].includes(r.state)).length
  const pending = runs.filter(r => r.state.startsWith('AWAITING') || r.state === 'ON_HOLD').length
  const completed = runs.filter(r => r.state === 'COMPLETED').length
  const failed = runs.filter(r => ['ABORTED', 'FAILED'].includes(r.state)).length

  return (
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3 mb-6">
      {[
        { label: 'Total Runs', value: total, color: 'bg-slate-700 text-white' },
        { label: 'Awaiting Action', value: pending, color: pending > 0 ? 'bg-amber-500 text-white' : 'bg-slate-100 text-slate-600' },
        { label: 'Completed', value: completed, color: 'bg-green-600 text-white' },
        { label: 'Failed / Aborted', value: failed, color: failed > 0 ? 'bg-red-600 text-white' : 'bg-slate-100 text-slate-600' },
      ].map(s => (
        <div key={s.label} className={`rounded-xl px-5 py-4 ${s.color} shadow-sm`}>
          <div className="text-2xl font-bold">{s.value}</div>
          <div className="text-xs opacity-80 mt-0.5">{s.label}</div>
        </div>
      ))}
    </div>
  )
}

export default function App() {
  const [runs, setRuns] = useState<RunDoc[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [lastUpdated, setLastUpdated] = useState<Date | null>(null)
  const [expandedId, setExpandedId] = useState<string | null>(null)

  const load = useCallback(async () => {
    try {
      const data = await fetchRuns()
      setRuns(data)
      setLastUpdated(new Date())
      setError(null)
      // Auto-expand the first run that is awaiting action
      if (!expandedId) {
        const pending = data.find(r => r.state.startsWith('AWAITING') || r.state === 'ON_HOLD')
        if (pending) setExpandedId(pending.run_id)
        else if (data.length > 0) setExpandedId(data[0].run_id)
      }
    } catch (e) {
      setError(String(e))
    } finally {
      setLoading(false)
    }
  }, [expandedId])

  // Initial load
  useEffect(() => { load() }, [])

  // Auto-refresh every 10 seconds
  useEffect(() => {
    const id = setInterval(load, 10_000)
    return () => clearInterval(id)
  }, [load])

  return (
    <div className="min-h-screen bg-slate-100">
      <Header onRefresh={load} lastUpdated={lastUpdated} />
      <main className="max-w-screen-xl mx-auto px-4 py-6">
        {loading && (
          <div className="flex items-center justify-center py-20 text-slate-500">
            <span className="animate-spin mr-2">⟳</span> Loading runs…
          </div>
        )}
        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl px-5 py-4 mb-4">
            ⚠ Could not reach API: {error}
          </div>
        )}
        {!loading && runs.length === 0 && !error && (
          <div className="text-center py-20 text-slate-400">
            <div className="text-5xl mb-4">📭</div>
            <p className="text-lg">No runs found yet.</p>
            <p className="text-sm mt-1">Run the fleet-agents pipeline to see results here.</p>
          </div>
        )}
        {!loading && runs.length > 0 && (
          <>
            <SummaryBar runs={runs} />
            <div className="space-y-3">
              {runs.map(run => (
                <RunCard
                  key={run.run_id}
                  run={run}
                  expanded={expandedId === run.run_id}
                  onToggle={() => setExpandedId(expandedId === run.run_id ? null : run.run_id)}
                  onDecisionSubmit={load}
                />
              ))}
            </div>
          </>
        )}
      </main>
    </div>
  )
}
