// Generated by GitHub Copilot

export interface RunStep {
  step: string;
  status: 'DONE' | 'FAILED' | 'RUNNING' | string;
  timestamp_utc: string;
  output?: Record<string, unknown>;
}

export interface RunApproval {
  gate: string;
  decision: string;
  note?: string;
  timestamp_utc: string;
  decided_by: string;
}

export interface ToolCall {
  tool: string;
  args?: Record<string, unknown>;
  result?: Record<string, unknown>;
  duration_ms?: number;
  timestamp_utc?: string;
}

export interface IntendedMove {
  bus_number?: string;
  current_device?: string;
  target_folder?: string;
  current_soti_folder?: string;
  vehicle_status?: string;
  reason?: string;
  stale_ltm_tag?: boolean;
  [key: string]: unknown;
}

export interface RunDoc {
  run_id: string;
  intake_id: string;
  agency: string;
  state: string;
  current_step: string;
  dva_path?: string;
  started_utc: string;
  steps: RunStep[];
  approvals: RunApproval[];
  tool_calls?: ToolCall[];
  revisions?: unknown[];
}

export interface PendingGate {
  run_id: string;
  gate: string;
  payload: {
    intended_moves?: IntendedMove[];
    schema_issues?: SchemaIssue[];
    recon_result?: ReconResult;
    sr_notes?: string;
    mock_result?: MockResult;
    post_hitl2_summary?: string;
    post_hitl3_summary?: string;
    post_hitl4_summary?: string;
    [key: string]: unknown;
  };
  created_at?: string;
}

export interface SchemaIssue {
  row: number;
  issue: string;
  data?: Record<string, unknown>;
}

export interface ReconResult {
  moved: ReconDevice[];
  unmoved: ReconDevice[];
  unidentified: ReconDevice[];
  summary_text?: string;
}

export interface ReconDevice {
  device?: string;
  bus_number?: string;
  from_folder?: string;
  to_folder?: string;
  reason?: string;
  actual_folder?: string;
  intended_folder?: string;
}

export interface MockResult {
  moved: ReconDevice[];
  workbook_path?: string;
}

/** Tab name → rows (first row is header) */
export type WorkbookTabs = Record<string, string[][]>;

export interface DecisionForm {
  gate: string;
  decision: string;
  note: string;
  subset_indices: string;
}

export interface NLEdit {
  action: 'exclude' | 'retarget';
  device: string;
  bus: string;
  target_folder?: 'Production' | 'LTM';
  reason?: string;
}

export interface NLEditResult {
  run_id?: string;
  instruction?: string;
  edits: NLEdit[];
  unmatched: string[];
  summary: string;
}

// Pipeline stage ordering for the timeline (6-stage flow; SR stages removed)
export const PIPELINE_STAGES = [
  { key: 'RECEIVED',              label: 'Triggered',         step: 'stage1_trigger' },
  { key: 'PARSING',               label: 'Parse DVA',         step: 'stage2_parse' },
  { key: 'PLANNED',               label: 'Planned',           step: 'stage2b_enrich' },
  { key: 'AWAITING_PRE_APPROVAL', label: 'HITL-2 Approval',   step: 'stage3_hitl_pre' },
  { key: 'MOVING',                label: 'Executing',         step: 'stage4_execute' },
  { key: 'RECONCILING',           label: 'Reconciling',       step: 'stage5_reconcile' },
  { key: 'AWAITING_VALIDATION',   label: 'HITL-3 Validate',   step: 'stage6_hitl_validation' },
  { key: 'COMPLETED',             label: 'Completed',         step: 'stage6_validation' },
] as const;

export type RunState = typeof PIPELINE_STAGES[number]['key'] | 'ABORTED' | 'FAILED' | 'ON_HOLD';
