import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// Generated by GitHub Copilot
export default defineConfig({
  plugins: [react()],
  server: {
    port: 5173,
    proxy: {
      // Proxy all /api/* requests to FastAPI backend during development
      '/api': {
        target: 'http://localhost:8080',
        changeOrigin: true,
      },
    },
  },
})
