# Generated by GitHub Copilot
"""
Central configuration — all values loaded from environment / .env file.
Flip USE_MOCK_* flags to False individually as real access lands.
"""
import os
from dotenv import load_dotenv

load_dotenv()

# ── Azure OpenAI via Azure AI Foundry ────────────────────────────────────────
AZURE_OPENAI_ENDPOINT: str = os.getenv(
    "AZURE_OPENAI_ENDPOINT",
    "https://pds-dev-agenticai-dashboard-azureopenai-foundry.openai.azure.com/",
)
# Full /openai/v1 path used by the openai SDK's base_url parameter
AZURE_OPENAI_ENDPOINT_V1: str = AZURE_OPENAI_ENDPOINT.rstrip("/") + "/openai/v1"

AZURE_OPENAI_DEPLOYMENT: str = os.getenv(
    "AZURE_OPENAI_DEPLOYMENT",
    "pds-dev-agenticai-project-gpt-5.4-nano",
)
# API key for Azure OpenAI — set in .env, never committed to source control
AZURE_OPENAI_API_KEY: str = os.getenv("AZURE_OPENAI_API_KEY", "")

# ── SOTI group path — BRT parent folder containing Production & LTM sub-folders ─
# GET /api/devices is paginated; searching this path returns only BRT devices.
# Adjust if the SOTI folder hierarchy is ever renamed.
SOTI_BRT_GROUP_PATH: str = os.getenv(
    "SOTI_BRT_GROUP_PATH",
    "//Presto/Brampton Transit(BRT)/1.Production",
)

# ── SOTI MCP Server (individual device reads — enrichment & reconciliation) ──
SOTI_MCP_TRANSPORT: str = os.getenv("SOTI_MCP_TRANSPORT", "stdio")   # "stdio" | "http"
# stdio: launch soti_mcp_server/server.py as a subprocess
SOTI_MCP_COMMAND: str = os.getenv("SOTI_MCP_COMMAND", "python")
SOTI_MCP_ARGS: list[str] = os.getenv("SOTI_MCP_ARGS", "server.py").split()
SOTI_MCP_CWD: str = os.getenv(
    "SOTI_MCP_CWD",
    r"C:\Users\ayush.ai.srivastava\OneDrive - Accenture\Ayush Space\projects\metrolinx\soti_mcp_server",
)
SOTI_MCP_HTTP_URL: str = os.getenv("SOTI_MCP_HTTP_URL", "http://localhost:8000/mcp")

# ── Cosmos DB for MongoDB vCore (intake record store) ────────────────────
# Authentication: SCRAM-SHA-256 via connection string.
# Store the full connection string (including password) ONLY in .env — never in code.
COSMOS_CONNECTION_STRING: str = os.getenv("COSMOS_CONNECTION_STRING", "")
COSMOS_DATABASE: str = os.getenv("COSMOS_DATABASE", "fmi-db")
COSMOS_INTAKE_COLLECTION: str = os.getenv("COSMOS_INTAKE_COLLECTION", "intake")
COSMOS_MOVEMENT_COLLECTION: str = os.getenv("COSMOS_MOVEMENT_COLLECTION", "movement")

# ── Mock flags — flip to False when real access lands ────────────────────────
USE_MOCK_LLM: bool = os.getenv("USE_MOCK_LLM", "true").lower() == "true"
USE_MOCK_SOTI: bool = os.getenv("USE_MOCK_SOTI", "true").lower() == "true"
USE_MOCK_HITL: bool = os.getenv("USE_MOCK_HITL", "false").lower() == "true"
USE_MOCK_COSMOS: bool = os.getenv("USE_MOCK_COSMOS", "true").lower() == "true"
# Set to false once Storage Blob Data Reader role is confirmed for the runner identity
USE_MOCK_BLOB: bool = os.getenv("USE_MOCK_BLOB", "true").lower() == "true"

# ── SOTI device naming convention ────────────────────────────────────────────
# Production BRT naming:
#   BRT_DCU_{bus:04d}_1   → SOTI_BUS_DIGITS=4, SOTI_DCU_SUFFIX=_1
#   BRT_BFTP_{bus:04d}_2  → SOTI_BUS_DIGITS=4, SOTI_BFTP_SUFFIX=_2
# Test SOTI (5-digit sequential, no suffix):
#   BRT_DCU_{bus:05d} / BRT_BFTP_{bus:05d} → SOTI_BUS_DIGITS=5, both suffixes empty
SOTI_BUS_DIGITS: int   = int(os.getenv("SOTI_BUS_DIGITS", "4"))
SOTI_DCU_SUFFIX: str   = os.getenv("SOTI_DCU_SUFFIX",  "_1")  # DCU devices
SOTI_BFTP_SUFFIX: str  = os.getenv("SOTI_BFTP_SUFFIX", "_2")  # BFTP devices

# Movable device types per agency — only these types participate in fleet moves
MOVABLE_DEVICE_TYPES: dict[str, list[str]] = {"BRT": ["DCU", "BFTP"]}

# ── Paths ────────────────────────────────────────────────────────────────────
STATE_DIR: str = os.getenv("STATE_DIR", "output")      # all outputs go here
OUTPUT_DIR: str = STATE_DIR                             # alias used by new code
SAMPLE_DVA: str = os.getenv("SAMPLE_DVA", "samples/sample_dva.xlsx")

# ── ServiceNow defaults (mirrored from snow_mcp_server/.env) ────────────────
# Used by the HITL requestor prompt as a pre-filled default.
# The operator can override the value at runtime; it is passed to SNOW API.
SNOW_REQUESTED_FOR: str = os.getenv("SNOW_REQUESTED_FOR", "")

# ── Ops Dashboard Portal ─────────────────────────────────────────────────────
# Set USE_WEB_HITL=true to route HITL gates through the web portal instead of
# the console. The portal must be running at OPS_PORTAL_URL.
USE_WEB_HITL: bool = os.getenv("USE_WEB_HITL", "false").lower() == "true"
OPS_PORTAL_URL: str = os.getenv("OPS_PORTAL_URL", "http://localhost:8080")

# ── Azure Blob Storage (optional key for local dev without RBAC) ─────────────
# Set AZURE_STORAGE_ACCOUNT_KEY in .env for local dev when Storage Blob Data
# Reader role is not assigned. Leave empty to use AzureCliCredential instead.
AZURE_STORAGE_ACCOUNT_NAME: str = os.getenv(
    "AZURE_STORAGE_ACCOUNT_NAME", "agenticaidashboardsa"
)
AZURE_STORAGE_CONTAINER_NAME: str = os.getenv("AZURE_STORAGE_CONTAINER_NAME", "fmi")
AZURE_STORAGE_ACCOUNT_KEY: str = os.getenv("AZURE_STORAGE_ACCOUNT_KEY", "")
# SAS token URL for container-level access. When set, takes priority over
# AzureCliCredential and account key. Generate via Azure portal or CLI.
# Format: https://<account>.blob.core.windows.net/<container>?sp=racw&...
AZURE_STORAGE_SAS_URL: str = os.getenv("AZURE_STORAGE_SAS_URL", "")
