# Generated by GitHub Copilot
"""
7-stage BRT Fleet Movement orchestrator.

State machine:
  RECEIVED → PARSING → PLANNED → AWAITING_PRE_APPROVAL →
  MOVING → RECONCILING → DRAFTING_SR → AWAITING_VALIDATION → COMPLETED
  (or ABORTED / FAILED / ON_HOLD at gates)

Hybrid design principle:
  - All routing, comparisons, and decisions are pure Python
  - LLM is invoked ONLY via narrator.narrate() calls for prose generation
"""
import time
import os
import logging
from datetime import datetime, timezone

import config
from agents.narrators import (
    ParserNarrator,
    ReconciliationNarrator,
    ExceptionTriageAgent,
    RunSummaryNarrator,
    ErrorTriageAgent,
)
from mcp_clients.soti_client import SotiMcpClient
from mcp_clients.fleet_client import FleetMovementClient
from mcp_clients.snow_client import SnowClient
from core.reconciler import reconcile
from core.cosmos_client import get_intake_record, get_movements_from_db
from core.state_store import (
    save_run_doc,
    append_step,
    append_tool_call,
    append_approval,
)
import core.cosmos_audit as cosmos_audit
from schemas.run_doc import RunDoc
from tools.hitl_console import (
    prompt_missing_dva,
    prompt_pre_move_approval,
    prompt_post_move_validation,
    prompt_schema_fix,
    prompt_subset_selection,
    prompt_hitl_error,
    prompt_sr_requestor,
)
from tools.sr_tracker import record_sr_result

log = logging.getLogger(__name__)

# All known SOTI API field names that carry the device's current group/folder path.
# The SOTI REST API uses PascalCase; some integrations normalise to camelCase or
# snake_case — cover all variants so a field-name mismatch never silently produces UNKNOWN.
_SOTI_FOLDER_FIELDS = (
    "CurrentGroupPath",   # most common in SOTI MobiControl REST API
    "currentGroupPath",
    "DeviceGroupPath",
    "deviceGroupPath",
    "GroupPath",
    "groupPath",
    "CurrentGroup",
    "currentGroup",
    "PathToDevice",
    "pathToDevice",
    "folder",             # mock / normalised name used internally
    "Path",
    "path",
)


def _folder_category(folder: str) -> str:
    """Map a SOTI folder path to 'Production', 'LTM', or 'Unknown'."""
    if not folder or folder == "UNKNOWN":
        return "Unknown"
    f = folder.lower()
    if "ltm" in f:
        return "LTM"
    if "production" in f:
        return "Production"
    return "Unknown"


def _extract_soti_folder(device_info: dict, device_name: str) -> str:
    """
    Extract the current folder/group path from a SOTI device response dict.
    Tries all known field names in order; logs the raw keys when none match
    so field-name mismatches are immediately visible in the logs.
    """
    if not device_info:
        return "UNKNOWN"
    for field in _SOTI_FOLDER_FIELDS:
        value = device_info.get(field)
        if value:
            return str(value)
    log.warning(
        "SOTI folder field not found for '%s'. "
        "Raw SOTI response keys: %s | scalar values: %s",
        device_name,
        list(device_info.keys()),
        {k: v for k, v in device_info.items() if not isinstance(v, (dict, list))},
    )
    return "UNKNOWN"


class Orchestrator:
    """
    Drives the 8-stage BRT fleet movement pipeline.
    LLM is invoked ONLY for narrator calls — all routing is pure Python.
    """

    def __init__(self, run_id: str):
        self.run_id = run_id
        self.run_doc: RunDoc | None = None
        self.soti = SotiMcpClient()
        self.fleet = FleetMovementClient()
        self.snow = SnowClient()
        self.parser_narrator = ParserNarrator()
        self.recon_narrator = ReconciliationNarrator()
        self.exception_triage = ExceptionTriageAgent()
        self.summary_narrator = RunSummaryNarrator()
        self.error_triage = ErrorTriageAgent()
        self._prev_state: str = "RECEIVED"

    def _transition(self, new_state: str, step: str, payload: dict | None = None,
                    triggered_by: str = "system") -> None:
        """
        Change run_doc.state, persist locally, and checkpoint to Cosmos.
        Wraps every self.run_doc.state = ... assignment so Cosmos always stays
        in sync with the local JSON store.
        """
        prev = self._prev_state
        self.run_doc.state = new_state
        self.run_doc.current_step = step
        save_run_doc(self.run_doc)
        cosmos_audit.upsert_run_state(self.run_id, new_state, step)
        cosmos_audit.append_checkpoint(
            self.run_id, prev, new_state, triggered_by, payload or {}
        )
        self._prev_state = new_state

    async def run(self) -> None:
        # ── Stage 1: Initialise ──────────────────────────────────────────────
        # Build the intake_id that the Intake Function wrote to Cosmos DB.
        # Convention: "intake_BRT_2026-05-27" from run_id "BRT-2026-05-27".
        # Split on the FIRST hyphen only: BRT | 2026-05-27 → intake_BRT_2026-05-27
        _parts = self.run_id.split("-", 1)
        intake_id = f"intake_{_parts[0]}_{_parts[1]}" if len(_parts) == 2 else f"intake_{self.run_id}"

        # Create the run document immediately so every subsequent state
        # transition is durably recorded, even if we abort at HITL-1.
        self.run_doc = RunDoc(
            run_id=self.run_id,
            intake_id=intake_id,
            agency="BRT",
            state="RECEIVED",
            current_step="stage1_trigger",
            dva_path=config.SAMPLE_DVA,    # overwritten below when record found
            started_utc=datetime.now(timezone.utc),
        )
        save_run_doc(self.run_doc)
        cosmos_audit.upsert_run_state(self.run_id, "RECEIVED", "stage1_trigger",
                                      {"intake_id": intake_id, "agency": "BRT"})

        # ── Stage 1: Check intake record (fmi-db.intake) ─────────────────────
        # Must be READY_FOR_RUN to proceed. No retries — fail immediately if not found.
        self._transition("ON_HOLD", "stage1_cosmos_check")

        intake_record = await get_intake_record(intake_id)

        if intake_record is None:
            log.error(
                "Intake record '%s' not found in fmi-db.intake or status != READY_FOR_RUN. "
                "Ensure the intake pipeline has processed today's DVA email before running.",
                intake_id,
            )
            self._transition("FAILED", "stage1_cosmos_check",
                             {"reason": "intake record not found or not READY_FOR_RUN",
                              "intake_id": intake_id})
            append_step(self.run_doc, "stage1_cosmos_check", "FAILED",
                        {"intake_id": intake_id})
            save_run_doc(self.run_doc)
            return

        self._transition("RECEIVED", "stage1_cosmos_check",
                         {"intake_id": intake_id,
                          "dva_blob_uri": intake_record.attachment.blob_uri})
        append_step(self.run_doc, "stage1_cosmos_check", "DONE",
                    {"intake_id": intake_id,
                     "dva_blob_uri": intake_record.attachment.blob_uri})
        save_run_doc(self.run_doc)

        await self.soti.connect()
        await self.fleet.connect()
        await self.snow.connect()
        log.info(
            "Stage 1 complete — intake READY_FOR_RUN | run_id=%s | intake_id=%s",
            self.run_id, intake_id,
        )

        # ── Stage 2: Build intended-move list from Cosmos DB movement collection ─
        self._transition("PARSING", "stage2_parse")

        schema_issues: list[dict] = []
        intended_moves = await get_movements_from_db(self.run_id)

        if not intended_moves:
            log.error(
                "Stage 2 — no movement records found in Cosmos DB for run_id='%s'. "
                "Ensure the movement collection in fmi-db is populated before running.",
                self.run_id,
            )
            self._transition("FAILED", "stage2_parse",
                             {"reason": "no movement records in Cosmos DB"})
            save_run_doc(self.run_doc)
            return

        log.info(
            "Stage 2 — loaded %d moves from Cosmos DB (fmi-db.movement)",
            len(intended_moves),
        )

        if schema_issues:
            decision = prompt_schema_fix(schema_issues, self.run_id)
            append_approval(self.run_doc, "HITL-schema", decision, "")
            cosmos_audit.append_hitl_event(self.run_id, "HITL-schema", decision,
                                           context={"issues": len(schema_issues)})
            if decision == "abort":
                self._transition("ABORTED", "stage2_schema_gate",
                                 {"reason": "schema errors", "count": len(schema_issues)})
                save_run_doc(self.run_doc)
                log.warning("Run aborted at schema gate | run_id=%s", self.run_id)
                return

        # Send a compact summary to the LLM — sending all 1000+ rows exceeds TPM limits.
        # The narrator only needs counts + a representative sample to produce a useful summary.
        sample_moves = [m.model_dump() for m in intended_moves[:10]]
        parser_summary = self.parser_narrator.narrate({
            "total_moves": len(intended_moves),
            "schema_issue_count": len(schema_issues),
            "schema_issues_sample": schema_issues[:5],
            "sample_moves": sample_moves,
        })

        self._transition("PLANNED", "stage2_parse",
                         {"count": len(intended_moves), "schema_issues": len(schema_issues)})
        append_step(self.run_doc, "stage2_parse", "DONE", {
            "count": len(intended_moves),
            "schema_issues": len(schema_issues),
            "summary": parser_summary,
        })
        save_run_doc(self.run_doc)
        log.info("Stage 2 complete — %d moves planned, %d schema issues",
                 len(intended_moves), len(schema_issues))

        # ── Stage 2b: Enrich moves with current SOTI location (read-only) ────
        # One bulk GET /api/devices call replaces N individual device searches.
        self.run_doc.current_step = "stage2b_soti_enrich"
        save_run_doc(self.run_doc)

        t0 = time.monotonic()
        device_lookup = await self.soti.build_device_lookup()
        lookup_ms = int((time.monotonic() - t0) * 1000)
        append_tool_call(
            self.run_doc, "soti.build_device_lookup (bulk)",
            {}, {"device_count": len(device_lookup)}, lookup_ms,
        )
        log.info("Stage 2b — bulk SOTI lookup: %d devices fetched in %dms",
                 len(device_lookup), lookup_ms)

        for move in intended_moves:
            device_info = self.soti.get_device_from_lookup(device_lookup, move.current_device)
            current_folder = _extract_soti_folder(device_info, move.current_device)

            # ── Check if device exists under LTM_ prefix ──────────────────
            # A device moving Prod→LTM would already have LTM_ if previously renamed.
            # A device moving LTM→Prod was renamed LTM_BRT_* when it went to LTM.
            ltm_device_name = f"LTM_{move.current_device}"
            ltm_device_info = self.soti.get_device_from_lookup(device_lookup, ltm_device_name)
            ltm_folder = _extract_soti_folder(ltm_device_info, ltm_device_name) if ltm_device_info else "UNKNOWN"

            # ── Classify per truth table ───────────────────────────────────
            target = move.target_folder  # "Production" or "LTM"
            current_cat = _folder_category(current_folder)
            ltm_cat     = _folder_category(ltm_folder)

            if device_info and current_cat == "Production" and target == "Production":
                move.classification   = "MATCHED_PRODUCTION"
                move.execution_status = "SKIPPED"
                move.current_soti_folder = current_folder

            elif device_info and current_cat == "LTM" and target == "LTM":
                move.classification   = "MATCHED_LTM"
                move.execution_status = "SKIPPED"
                move.current_soti_folder = current_folder

            elif device_info and current_cat == "Production" and target == "LTM":
                move.classification   = "NEEDS_MOVE_TO_LTM"
                move.execution_status = "PENDING"
                move.current_soti_folder = current_folder

            elif (device_info and current_cat == "LTM" and target == "Production") or \
                 (ltm_device_info and ltm_cat == "LTM" and target == "Production"):
                # Device is in LTM (possibly already renamed with LTM_ prefix)
                move.classification   = "NEEDS_MOVE_TO_PRODUCTION"
                move.execution_status = "PENDING"
                if ltm_device_info and not device_info:
                    # Device was already renamed LTM_BRT_* — update current_device
                    move.stale_ltm_tag   = True
                    move.current_device  = ltm_device_name
                    move.current_soti_folder = ltm_folder
                    log.warning("Stage 2b — STALE LTM TAG: bus %s found as %s",
                                move.bus_number, ltm_device_name)
                else:
                    move.current_soti_folder = current_folder

            else:
                move.classification   = "NOT_FOUND"
                move.execution_status = "BLOCKED"
                move.block_reason     = (
                    f"Device '{move.current_device}' not found in SOTI "
                    f"(also checked '{ltm_device_name}')"
                )
                move.current_soti_folder = "UNKNOWN"

            log.info("Stage 2b — %s → target=%s | current=%s | class=%s [%s]",
                     move.current_device, target,
                     move.current_soti_folder, move.classification, move.execution_status)

        # ── Summarise classifications ─────────────────────────────────────
        pending_count   = sum(1 for m in intended_moves if m.execution_status == "PENDING")
        skipped_count   = sum(1 for m in intended_moves if m.execution_status == "SKIPPED")
        blocked_count   = sum(1 for m in intended_moves if m.execution_status == "BLOCKED")
        stale_devices   = [
            {"device": m.current_device, "bus": m.bus_number, "soti_folder": m.current_soti_folder}
            for m in intended_moves if m.stale_ltm_tag
        ]
        blocked_devices = [
            {"device": m.current_device, "bus": m.bus_number, "reason": m.block_reason}
            for m in intended_moves if m.execution_status == "BLOCKED"
        ]

        # ── Exception triage (LLM) — only when something looks off ───────────
        triage_2b = ""
        if blocked_count or stale_devices:
            log.warning(
                "Stage 2b — %d PENDING | %d SKIPPED | %d BLOCKED | %d stale-LTM",
                pending_count, skipped_count, blocked_count, len(stale_devices),
            )
            triage_2b = self.exception_triage.narrate({
                "stage": "stage2b_enrich",
                "blocked": blocked_devices,
                "stale_ltm": stale_devices,
            })
            log.info("Stage 2b triage: %s", triage_2b)

        append_step(self.run_doc, "stage2b_enrich", "DONE",
                    {"enriched":  len(intended_moves),
                     "pending":   pending_count,
                     "skipped":   skipped_count,
                     "blocked":   blocked_count,
                     "stale_ltm": len(stale_devices),
                     "exception_triage": triage_2b,
                     "intended_moves": [m.model_dump() for m in intended_moves]})
        save_run_doc(self.run_doc)

        # ── Stage 3: HITL pre-move approval ──────────────────────────────────
        self._transition("AWAITING_PRE_APPROVAL", "stage3_hitl_pre")

        # Run MOCK dry-run via brampton.py before showing HITL-2 gate.
        # Operator sees what WOULD happen — no SOTI calls made.
        mock_result = await self.fleet.run_fleet_movement(
            run_id=self.run_id,
            intended_moves=[m.model_dump() for m in intended_moves],
            mode="MOCK",
        )
        append_step(self.run_doc, "stage3_mock_preview", "DONE", {
            "simulated_moves": len(mock_result.get("moved", [])),
            "workbook_path":   mock_result.get("workbook_path", ""),
        })
        save_run_doc(self.run_doc)
        log.info("Stage 3 — MOCK preview generated: %d moves simulated", len(mock_result.get("moved", [])))

        decision = prompt_pre_move_approval(intended_moves, self.run_id)
        append_approval(self.run_doc, "HITL-2", decision, "")
        cosmos_audit.append_hitl_event(self.run_id, "HITL-2", decision,
                                       context={"moves": len(intended_moves)})

        if decision == "reject":
            self._transition("ABORTED", "stage3_approval", {"reason": "HITL-2 reject"})
            append_step(self.run_doc, "stage3_approval", "REJECTED", {})
            save_run_doc(self.run_doc)
            return

        approved_moves = intended_moves
        if decision == "approve_subset":
            indices = prompt_subset_selection(intended_moves)
            approved_moves = [intended_moves[i] for i in indices]

        # Post-HITL-2 narrator: compact summary only — avoid TPM limits
        post_approval_summary = self.parser_narrator.narrate({
            "event": "post_hitl2_decision",
            "decision": decision,
            "approved_count": len(approved_moves),
            "total_count": len(intended_moves),
            "excluded_count": len(intended_moves) - len(approved_moves),
            "sample_approved": [m.model_dump() for m in approved_moves[:5]],
        })
        log.info("Post-HITL-2 LLM: %s", post_approval_summary)

        append_step(self.run_doc, "stage3_approval", "DONE", {
            "decision": decision,
            "approved_count": len(approved_moves),
            "post_decision_summary": post_approval_summary,
        })
        save_run_doc(self.run_doc)

        # ── Stage 4: Execute moves via Fleet Movement MCP (brampton.py) ─────
        # Only PENDING moves (NEEDS_MOVE_TO_LTM / NEEDS_MOVE_TO_PRODUCTION) are sent.
        # SKIPPED moves are already correct; BLOCKED moves cannot be executed.
        self._transition("MOVING", "stage4_execute")

        pending_moves = [m for m in approved_moves if m.execution_status == "PENDING"]
        skipped_moves = [m for m in approved_moves if m.execution_status == "SKIPPED"]
        blocked_moves = [m for m in approved_moves if m.execution_status == "BLOCKED"]
        log.info(
            "Stage 4 — executing %d PENDING moves | %d SKIPPED | %d BLOCKED",
            len(pending_moves), len(skipped_moves), len(blocked_moves),
        )
        if blocked_moves:
            log.warning("Stage 4 — BLOCKED devices (will not be moved): %s",
                        [m.current_device for m in blocked_moves])

        t0 = time.monotonic()
        try:
            fleet_result = await self.fleet.run_fleet_movement(
                run_id=self.run_id,
                intended_moves=[m.model_dump() for m in pending_moves],
                mode="LIVE",
            )
        except Exception as _exc:
            _err = str(_exc)
            log.error("Stage 4 — fleet_movement failed: %s", _err)
            # Error triage (LLM): diagnose probable cause + recommend retry/escalate
            _diagnosis = self.error_triage.narrate({
                "component": "brampton.py (fleet movement)",
                "error": _err,
                "run_id": self.run_id,
            })
            log.info("Stage 4 error triage: %s", _diagnosis)
            append_step(self.run_doc, "stage4_error_triage", "DONE",
                        {"error": _err, "diagnosis": _diagnosis})
            save_run_doc(self.run_doc)
            _err_decision = prompt_hitl_error("brampton.py", _err, self.run_id, _diagnosis)
            append_approval(self.run_doc, "HITL-Error:fleet_movement", _err_decision, _err)
            cosmos_audit.append_hitl_event(
                self.run_id, "HITL-Error", _err_decision,
                context={"error": _err},
            )
            if _err_decision != "retry":
                self._transition("FAILED", "stage4_execute",
                                 {"reason": "fleet_movement failed", "error": _err})
                save_run_doc(self.run_doc)
                await self.soti.disconnect()
                await self.fleet.disconnect()
                await self.snow.disconnect()
                return
            # Retry once on operator request
            fleet_result = await self.fleet.run_fleet_movement(
                run_id=self.run_id,
                intended_moves=[m.model_dump() for m in pending_moves],
                mode="LIVE",
            )

        duration_ms = int((time.monotonic() - t0) * 1000)
        _fleet_moved        = fleet_result.get("moved", [])
        _fleet_unmoved      = fleet_result.get("unmoved", [])
        _fleet_unidentified = fleet_result.get("unidentified", [])
        _workbook_path      = fleet_result.get("workbook_path", "")

        append_tool_call(
            self.run_doc, "fleet.run_fleet_movement",
            {"run_id": self.run_id, "mode": "LIVE", "move_count": len(approved_moves)},
            {"moved": len(_fleet_moved), "unmoved": len(_fleet_unmoved),
             "unidentified": len(_fleet_unidentified), "workbook_path": _workbook_path},
            duration_ms,
        )
        append_step(self.run_doc, "stage4_execute", "DONE", {
            "moved":         len(_fleet_moved),
            "unmoved":       len(_fleet_unmoved),
            "unidentified":  len(_fleet_unidentified),
            "workbook_path": _workbook_path,
        })
        save_run_doc(self.run_doc)
        log.info(
            "Stage 4 complete — brampton.py: moved=%d unmoved=%d unidentified=%d | workbook=%s",
            len(_fleet_moved), len(_fleet_unmoved), len(_fleet_unidentified), _workbook_path,
        )

        # ── Stage 5: Auto-reconcile (pure code) ──────────────────────────────
        self._transition("RECONCILING", "stage5_reconcile")

        # Refresh the bulk lookup after moves to get current locations
        t0 = time.monotonic()
        post_move_lookup = await self.soti.build_device_lookup()
        lookup_ms = int((time.monotonic() - t0) * 1000)
        append_tool_call(self.run_doc, "soti.build_device_lookup (reconcile)",
                         {}, {"device_count": len(post_move_lookup)}, lookup_ms)

        actual_locations: dict[str, str] = {}
        for move in approved_moves:
            r = self.soti.get_device_from_lookup(post_move_lookup, move.current_device)
            actual_locations[move.current_device] = _extract_soti_folder(r, move.current_device)

        recon_result = reconcile(approved_moves, actual_locations)

        # Persist move exceptions to Cosmos for audit
        for exc_item in recon_result.unmoved + recon_result.unidentified:
            cosmos_audit.append_move_exception(
                self.run_id,
                device=exc_item.get("device", "?"),
                intended_folder=next(
                    (m.target_folder for m in approved_moves
                     if m.current_device == exc_item.get("device")), "?"),
                actual_folder=actual_locations.get(exc_item.get("device", ""), "UNKNOWN"),
                reason=exc_item.get("reason", ""),
            )

        # Recon narrator: send counts + small sample only — avoid TPM limits
        recon_result.summary_text = self.recon_narrator.narrate({
            "moved_count": len(recon_result.moved),
            "unmoved_count": len(recon_result.unmoved),
            "unidentified_count": len(recon_result.unidentified),
            "sample_moved": recon_result.moved[:5],
            "sample_unmoved": recon_result.unmoved[:5],
            "sample_unidentified": recon_result.unidentified[:5],
        })

        # Exception triage (LLM): classify probable cause for reconciliation residuals
        recon_triage = ""
        if recon_result.unmoved or recon_result.unidentified:
            recon_triage = self.exception_triage.narrate({
                "stage": "stage5_reconcile",
                "unmoved_count": len(recon_result.unmoved),
                "unidentified_count": len(recon_result.unidentified),
                "sample_unmoved": recon_result.unmoved[:5],
                "sample_unidentified": recon_result.unidentified[:5],
            })
            log.info("Stage 5 triage: %s", recon_triage)

        # Workbook was written by brampton.py (Stage 4). Record its path here.
        output_wb_path = _workbook_path
        log.info("Stage 5 — 5-tab workbook from Stage 4: %s", output_wb_path)

        append_step(self.run_doc, "stage5_reconcile", "DONE", {
            "moved": len(recon_result.moved),
            "unmoved": len(recon_result.unmoved),
            "unidentified": len(recon_result.unidentified),
            "summary": recon_result.summary_text,
            "exception_triage": recon_triage,
            "output_workbook": output_wb_path,
            # Persist the exception device lists so the portal Q&A agent can reason
            # about specific failed/unidentified devices after the run completes.
            "unmoved_list": recon_result.unmoved,
            "unidentified_list": recon_result.unidentified,
        })
        save_run_doc(self.run_doc)
        log.info("Stage 5 complete — %d moved, %d unmoved, %d unidentified",
                 len(recon_result.moved), len(recon_result.unmoved),
                 len(recon_result.unidentified))

        # ── Stage 7 pre-step: collect requestor identity at HITL gate ────────
        requestor_name = prompt_sr_requestor(
            run_id=self.run_id,
            default_requestor=config.SNOW_REQUESTED_FOR,
        )
        log.info("Stage 7 requestor confirmed: %s", requestor_name or "<env default>")

        # ── Stage 7: Create Device Monitoring SR in ServiceNow ────────────────
        self._transition("DRAFTING_SR", "stage7_create_sr")

        # Pre-initialise so stage7b always has values regardless of SR success/failure
        sr_sys_id = ""
        ritm_number = ""
        sctask_number = ""

        try:
            sr_short_desc = f"Device Monitoring SR for BRT Fleet Movement {self.run_id}"
            sr_description = (
                f"BRT Fleet Movement Run ID: {self.run_id}\n"
                f"Summary: {len(recon_result.moved)} devices successfully moved, "
                f"{len(recon_result.unmoved)} unmoved, {len(recon_result.unidentified)} unidentified.\n"
                f"Output workbook: {output_wb_path}\n\n"
                f"Reconciliation details:\n{recon_result.summary_text}"
            )

            t0 = time.monotonic()
            sr_result = await self.snow.create_device_monitoring_sr(
                run_id=self.run_id,
                short_description=sr_short_desc,
                description=sr_description,
                requestor_name=requestor_name,
            )
            sr_duration_ms = int((time.monotonic() - t0) * 1000)

            sr_number     = sr_result.get("sr_number", "UNKNOWN")
            sr_sys_id     = sr_result.get("sr_sys_id", "")
            ritm_number   = sr_result.get("ritm_number", "")
            sctask_number = sr_result.get("sctask_number", "")

            append_tool_call(
                self.run_doc, "snow.create_device_monitoring_sr",
                {"run_id": self.run_id, "moved": len(recon_result.moved), "requestor": requestor_name},
                {"sr_number": sr_number, "ritm_number": ritm_number, "sctask_number": sctask_number},
                sr_duration_ms,
            )
            append_step(self.run_doc, "stage7_create_sr", "DONE", {
                "sr_number":     sr_number,
                "sr_sys_id":     sr_sys_id,
                "ritm_number":   ritm_number,
                "sctask_number": sctask_number,
                "requestor":     requestor_name,
            })
            log.info(
                "Stage 7 complete — SNOW SR created: sr_number=%s ritm_number=%s sctask=%s",
                sr_number, ritm_number, sctask_number,
            )
        except Exception as sr_exc:
            sr_err = str(sr_exc)
            log.error("Stage 7 — SNOW SR creation failed: %s", sr_err, exc_info=True)
            # Log the error but don't block the pipeline — SR creation is async/best-effort
            append_step(self.run_doc, "stage7_create_sr", "ERROR", {
                "error": sr_err,
                "note": "SR creation failed but pipeline continues",
            })
            # Store a placeholder SR number so downstream can reference it
            sr_number = f"SR-ERROR-{self.run_id}"

        save_run_doc(self.run_doc)

        # ── Stage 7b: Record SR result → fleet.xlsx + result.json + blob ─────
        try:
            tracker_out = record_sr_result(
                run_id=self.run_id,
                sr_number=sr_number,
                ritm_number=ritm_number,
                sr_sys_id=sr_sys_id,
                sctask_number=sctask_number,
                recon_result=recon_result,
                output_workbook_path=output_wb_path,
                requestor_name=requestor_name,
                run_summary=recon_result.summary_text,
            )
            append_step(self.run_doc, "stage7b_sr_tracking", "DONE", tracker_out)
            save_run_doc(self.run_doc)
            log.info(
                "Stage 7b complete — fleet.xlsx updated, result.json written | run_id=%s",
                self.run_id,
            )
        except Exception as track_exc:
            log.error("Stage 7b — SR tracking failed: %s", track_exc, exc_info=True)
            append_step(self.run_doc, "stage7b_sr_tracking", "ERROR",
                        {"error": str(track_exc)})
            save_run_doc(self.run_doc)

        # ── Stage 6: HITL post-move validation ───────────────────────────────
        self._transition("AWAITING_VALIDATION", "stage6_hitl_validation")

        decision = prompt_post_move_validation(recon_result, self.run_id)
        append_approval(self.run_doc, "HITL-3", decision, "")
        cosmos_audit.append_hitl_event(self.run_id, "HITL-3", decision,
                                       context={"moved": len(recon_result.moved),
                                                "unmoved": len(recon_result.unmoved)})

        if decision == "rerun":
            self._transition("FAILED", "stage6_validation", {"reason": "HITL-3 rerun"})
            append_step(self.run_doc, "stage6_validation", "RERUN_REQUESTED", {})
            save_run_doc(self.run_doc)
            log.warning("Rerun requested by L2 | run_id=%s", self.run_id)
            return

        # Post-HITL-3 narrator: compact summary only — avoid TPM limits
        post_validation_summary = self.recon_narrator.narrate({
            "event": "post_hitl3_decision",
            "decision": decision,
            "moved_count": len(recon_result.moved),
            "unmoved_count": len(recon_result.unmoved),
            "unidentified_count": len(recon_result.unidentified),
            "sample_unmoved": recon_result.unmoved[:5],
            "sample_unidentified": recon_result.unidentified[:5],
        })
        log.info("Post-HITL-3 LLM: %s", post_validation_summary)
        append_step(self.run_doc, "stage6_post_hitl3", "DONE",
                    {"post_decision_summary": post_validation_summary})
        save_run_doc(self.run_doc)

        # ── Stage 7: Complete ───────────────────────────────────────────────────
        # Run summary (LLM): stakeholder summary email composed from run results.
        # Run summary narrator: compact — avoid TPM limits
        run_summary = self.summary_narrator.narrate({
            "run_id": self.run_id,
            "moved_count": len(recon_result.moved),
            "unmoved_count": len(recon_result.unmoved),
            "unidentified_count": len(recon_result.unidentified),
            "sample_moved": recon_result.moved[:5],
            "sample_unmoved": recon_result.unmoved[:5],
        })
        log.info("Run summary:\n%s", run_summary)

        self._transition("COMPLETED", "stage6_validation", triggered_by="system")
        append_step(self.run_doc, "stage6_validation", "COMPLETED", {
            "moved": len(recon_result.moved),
            "unmoved": len(recon_result.unmoved),
            "run_summary": run_summary,
        })
        save_run_doc(self.run_doc)
        log.info("Pipeline complete — %d moved, %d unmoved | run_id=%s",
                 len(recon_result.moved), len(recon_result.unmoved), self.run_id)

        await self.soti.disconnect()
        await self.fleet.disconnect()
        await self.snow.disconnect()
