# Generated by GitHub Copilot
"""
8-stage BRT Fleet Movement orchestrator.

State machine:
  RECEIVED → PARSING → PLANNED → AWAITING_PRE_APPROVAL →
  MOVING → RECONCILING → AWAITING_VALIDATION →
  DRAFTING_SR → AWAITING_SR_APPROVAL → COMPLETED
  (or ABORTED / FAILED / ON_HOLD at gates)

Hybrid design principle:
  - All routing, comparisons, and decisions are pure Python
  - LLM is invoked ONLY via narrator.narrate() calls for prose generation
"""
import time
import os
import logging
from datetime import datetime, timezone

import config
from agents.sub_agents.parser_narrator import ParserNarrator
from agents.sub_agents.reconciliation_narrator import ReconciliationNarrator
from agents.sub_agents.execution_narrator import ExecutionNarrator
from mcp_clients.soti_client import SotiMcpClient
from mcp_clients.fleet_client import FleetMovementClient
from core.excel_parser import parse_dva
from core.reconciler import reconcile
from core.cosmos_client import get_intake_record
from core.state_store import (
    save_run_doc,
    append_step,
    append_tool_call,
    append_approval,
)
import core.cosmos_audit as cosmos_audit
from schemas.run_doc import RunDoc
from tools.hitl_console import (
    prompt_missing_dva,
    prompt_pre_move_approval,
    prompt_post_move_validation,
    prompt_schema_fix,
    prompt_sr_closure,
    prompt_subset_selection,
    prompt_hitl_error,
)

log = logging.getLogger(__name__)


class Orchestrator:
    """
    Drives the 8-stage BRT fleet movement pipeline.
    LLM is invoked ONLY for narrator calls — all routing is pure Python.
    """

    def __init__(self, run_id: str):
        self.run_id = run_id
        self.run_doc: RunDoc | None = None
        self.soti = SotiMcpClient()
        self.fleet = FleetMovementClient()
        self.parser_narrator = ParserNarrator()
        self.recon_narrator = ReconciliationNarrator()
        self.exec_narrator = ExecutionNarrator()
        self._prev_state: str = "RECEIVED"

    def _transition(self, new_state: str, step: str, payload: dict | None = None,
                    triggered_by: str = "system") -> None:
        """
        Change run_doc.state, persist locally, and checkpoint to Cosmos.
        Wraps every self.run_doc.state = ... assignment so Cosmos always stays
        in sync with the local JSON store.
        """
        prev = self._prev_state
        self.run_doc.state = new_state
        self.run_doc.current_step = step
        save_run_doc(self.run_doc)
        cosmos_audit.upsert_run_state(self.run_id, new_state, step)
        cosmos_audit.append_checkpoint(
            self.run_id, prev, new_state, triggered_by, payload or {}
        )
        self._prev_state = new_state

    async def run(self) -> None:
        # ── Stage 1: Initialise ──────────────────────────────────────────────
        # Build the intake_id that the Intake Function wrote to Cosmos DB.
        # Convention: "intake_BRT_2026-05-27" from run_id "BRT-2026-05-27".
        # Split on the FIRST hyphen only: BRT | 2026-05-27 → intake_BRT_2026-05-27
        _parts = self.run_id.split("-", 1)
        intake_id = f"intake_{_parts[0]}_{_parts[1]}" if len(_parts) == 2 else f"intake_{self.run_id}"

        # Create the run document immediately so every subsequent state
        # transition is durably recorded, even if we abort at HITL-1.
        self.run_doc = RunDoc(
            run_id=self.run_id,
            intake_id=intake_id,
            agency="BRT",
            state="RECEIVED",
            current_step="stage1_trigger",
            dva_path=config.SAMPLE_DVA,    # overwritten below when record found
            started_utc=datetime.now(timezone.utc),
        )
        save_run_doc(self.run_doc)
        cosmos_audit.upsert_run_state(self.run_id, "RECEIVED", "stage1_trigger",
                                      {"intake_id": intake_id, "agency": "BRT"})

        # ── Cosmos DB intake-record check (HITL-1 gate) ──────────────────────
        self._transition("ON_HOLD", "stage1_cosmos_check")

        intake_record = await get_intake_record(intake_id)

        _hitl1_attempts = 0
        _MAX_HITL1_RETRIES = 3

        while intake_record is None:
            _hitl1_attempts += 1
            log.warning(
                "Intake record '%s' not found in Cosmos DB (status != READY_FOR_RUN)",
                intake_id,
            )
            decision = prompt_missing_dva(intake_id, self.run_id)
            append_approval(self.run_doc, "HITL-1", decision, "")
            cosmos_audit.append_hitl_event(self.run_id, "HITL-1", decision)

            if decision == "abort" or _hitl1_attempts >= _MAX_HITL1_RETRIES:
                if _hitl1_attempts >= _MAX_HITL1_RETRIES:
                    log.error(
                        "HITL-1 max retries (%d) reached — aborting | run_id=%s",
                        _MAX_HITL1_RETRIES, self.run_id,
                    )
                self._transition("ABORTED", "stage1_cosmos_check",
                                 {"reason": "intake record not found", "attempts": _hitl1_attempts})
                append_step(self.run_doc, "stage1_cosmos_check", "ABORTED",
                            {"reason": "intake record not found", "attempts": _hitl1_attempts})
                save_run_doc(self.run_doc)
                return

            intake_record = await get_intake_record(intake_id)
            if intake_record is None:
                log.info("Still no intake record after wait — re-prompting L2 (attempt %d/%d)",
                         _hitl1_attempts, _MAX_HITL1_RETRIES)

        # Record found — bind DVA path from the blob URI in the intake record
        self.run_doc.dva_path = intake_record.attachment.blob_uri
        self._transition("RECEIVED", "stage1_cosmos_check",
                         {"intake_id": intake_id,
                          "dva_blob_uri": intake_record.attachment.blob_uri})
        append_step(self.run_doc, "stage1_cosmos_check", "DONE", {
            "intake_id": intake_id,
            "dva_blob_uri": intake_record.attachment.blob_uri,
            "structural_check": intake_record.structural_check.model_dump(),
        })
        save_run_doc(self.run_doc)

        await self.soti.connect()
        await self.fleet.connect()
        log.info(
            "Stage 1 complete — intake record bound | run_id=%s | blob=%s",
            self.run_id,
            intake_record.attachment.blob_uri,
        )

        # ── Stage 2: Parse DVA (pure code) ───────────────────────────────────
        self._transition("PARSING", "stage2_parse")

        intended_moves, schema_issues = parse_dva(self.run_doc.dva_path)

        if schema_issues:
            decision = prompt_schema_fix(schema_issues, self.run_id)
            append_approval(self.run_doc, "HITL-schema", decision, "")
            cosmos_audit.append_hitl_event(self.run_id, "HITL-schema", decision,
                                           context={"issues": len(schema_issues)})
            if decision == "abort":
                self._transition("ABORTED", "stage2_schema_gate",
                                 {"reason": "schema errors", "count": len(schema_issues)})
                save_run_doc(self.run_doc)
                log.warning("Run aborted at schema gate | run_id=%s", self.run_id)
                return

        parser_summary = self.parser_narrator.narrate({
            "intended_moves": [m.model_dump() for m in intended_moves],
            "schema_issues": schema_issues,
        })

        self._transition("PLANNED", "stage2_parse",
                         {"count": len(intended_moves), "schema_issues": len(schema_issues)})
        append_step(self.run_doc, "stage2_parse", "DONE", {
            "count": len(intended_moves),
            "schema_issues": len(schema_issues),
            "summary": parser_summary,
        })
        save_run_doc(self.run_doc)
        log.info("Stage 2 complete — %d moves planned, %d schema issues",
                 len(intended_moves), len(schema_issues))

        # ── Stage 2b: Enrich moves with current SOTI location (read-only) ────
        self.run_doc.current_step = "stage2b_soti_enrich"
        save_run_doc(self.run_doc)

        for move in intended_moves:
            t0 = time.monotonic()
            device_info = await self.soti.get_device(move.current_device)
            duration_ms = int((time.monotonic() - t0) * 1000)
            current_folder = (
                (device_info.get("folder")
                 or device_info.get("CurrentGroup")
                 or device_info.get("GroupPath")
                 or "UNKNOWN")
                if device_info else "UNKNOWN"
            )
            append_tool_call(
                self.run_doc, "soti.get_device (enrich)",
                {"device": move.current_device}, device_info, duration_ms,
            )

            # ── Stale LTM tag detection ────────────────────────────────────
            if current_folder == "UNKNOWN" and move.target_folder == "Production":
                _ltm_name = f"LTM_{move.current_device}"
                _t1 = time.monotonic()
                _ltm_info = await self.soti.get_device(_ltm_name)
                _ltm_dur = int((time.monotonic() - _t1) * 1000)
                if _ltm_info:
                    _ltm_folder = (
                        _ltm_info.get("folder")
                        or _ltm_info.get("CurrentGroup")
                        or _ltm_info.get("GroupPath")
                        or "UNKNOWN"
                    )
                    move.stale_ltm_tag = True
                    move.current_soti_folder = (
                        f"\u26a0 STALE LTM TAG (found as {_ltm_name} in {_ltm_folder})"
                    )
                    move.current_device = _ltm_name
                    current_folder = move.current_soti_folder
                    log.warning(
                        "Stage 2b \u2014 STALE LTM TAG: bus %s found as %s in SOTI folder '%s'",
                        move.bus_number, _ltm_name, _ltm_folder,
                    )
                    append_tool_call(
                        self.run_doc, "soti.get_device (stale_ltm_check)",
                        {"device": _ltm_name}, _ltm_info, _ltm_dur,
                    )

            if move.current_soti_folder is None:
                move.current_soti_folder = current_folder
            log.info("Stage 2b \u2014 %s current SOTI folder: %s",
                     move.current_device, move.current_soti_folder)

        append_step(self.run_doc, "stage2b_enrich", "DONE",
                    {"enriched": len(intended_moves)})
        save_run_doc(self.run_doc)

        # ── Stage 3: HITL pre-move approval ──────────────────────────────────
        self._transition("AWAITING_PRE_APPROVAL", "stage3_hitl_pre")

        # Run MOCK dry-run via brampton.py before showing HITL-2 gate.
        # Operator sees what WOULD happen — no SOTI calls made.
        mock_result = await self.fleet.run_fleet_movement(
            run_id=self.run_id,
            intended_moves=[m.model_dump() for m in intended_moves],
            mode="MOCK",
        )
        append_step(self.run_doc, "stage3_mock_preview", "DONE", {
            "simulated_moves": len(mock_result.get("moved", [])),
            "workbook_path":   mock_result.get("workbook_path", ""),
        })
        save_run_doc(self.run_doc)
        log.info("Stage 3 — MOCK preview generated: %d moves simulated", len(mock_result.get("moved", [])))

        decision = prompt_pre_move_approval(intended_moves, self.run_id)
        append_approval(self.run_doc, "HITL-2", decision, "")
        cosmos_audit.append_hitl_event(self.run_id, "HITL-2", decision,
                                       context={"moves": len(intended_moves)})

        if decision == "reject":
            self._transition("ABORTED", "stage3_approval", {"reason": "HITL-2 reject"})
            append_step(self.run_doc, "stage3_approval", "REJECTED", {})
            save_run_doc(self.run_doc)
            return

        approved_moves = intended_moves
        if decision == "approve_subset":
            indices = prompt_subset_selection(intended_moves)
            approved_moves = [intended_moves[i] for i in indices]

        # Post-HITL-2 narrator: LLM responds to the human's approval decision
        post_approval_summary = self.parser_narrator.narrate({
            "event": "post_hitl2_decision",
            "decision": decision,
            "approved_count": len(approved_moves),
            "total_count": len(intended_moves),
            "approved_moves": [m.model_dump() for m in approved_moves],
            "excluded_count": len(intended_moves) - len(approved_moves),
        })
        log.info("Post-HITL-2 LLM: %s", post_approval_summary)

        append_step(self.run_doc, "stage3_approval", "DONE", {
            "decision": decision,
            "approved_count": len(approved_moves),
            "post_decision_summary": post_approval_summary,
        })
        save_run_doc(self.run_doc)

        # ── Stage 4: Execute moves via Fleet Movement MCP (brampton.py) ─────
        # brampton.py calls SOTI REST API directly — not via SOTI MCP.
        # This is the only code path that moves devices in SOTI MobiControl.
        self._transition("MOVING", "stage4_execute")

        t0 = time.monotonic()
        try:
            fleet_result = await self.fleet.run_fleet_movement(
                run_id=self.run_id,
                intended_moves=[m.model_dump() for m in approved_moves],
                mode="LIVE",
            )
        except Exception as _exc:
            _err = str(_exc)
            log.error("Stage 4 — fleet_movement failed: %s", _err)
            _err_decision = prompt_hitl_error("brampton.py", _err, self.run_id)
            append_approval(self.run_doc, "HITL-Error:fleet_movement", _err_decision, _err)
            cosmos_audit.append_hitl_event(
                self.run_id, "HITL-Error", _err_decision,
                context={"error": _err},
            )
            if _err_decision != "retry":
                self._transition("FAILED", "stage4_execute",
                                 {"reason": "fleet_movement failed", "error": _err})
                save_run_doc(self.run_doc)
                await self.soti.disconnect()
                await self.fleet.disconnect()
                return
            # Retry once on operator request
            fleet_result = await self.fleet.run_fleet_movement(
                run_id=self.run_id,
                intended_moves=[m.model_dump() for m in approved_moves],
                mode="LIVE",
            )

        duration_ms = int((time.monotonic() - t0) * 1000)
        _fleet_moved        = fleet_result.get("moved", [])
        _fleet_unmoved      = fleet_result.get("unmoved", [])
        _fleet_unidentified = fleet_result.get("unidentified", [])
        _workbook_path      = fleet_result.get("workbook_path", "")

        append_tool_call(
            self.run_doc, "fleet.run_fleet_movement",
            {"run_id": self.run_id, "mode": "LIVE", "move_count": len(approved_moves)},
            {"moved": len(_fleet_moved), "unmoved": len(_fleet_unmoved),
             "unidentified": len(_fleet_unidentified), "workbook_path": _workbook_path},
            duration_ms,
        )
        append_step(self.run_doc, "stage4_execute", "DONE", {
            "moved":         len(_fleet_moved),
            "unmoved":       len(_fleet_unmoved),
            "unidentified":  len(_fleet_unidentified),
            "workbook_path": _workbook_path,
        })
        save_run_doc(self.run_doc)
        log.info(
            "Stage 4 complete — brampton.py: moved=%d unmoved=%d unidentified=%d | workbook=%s",
            len(_fleet_moved), len(_fleet_unmoved), len(_fleet_unidentified), _workbook_path,
        )

        # ── Stage 5: Auto-reconcile (pure code) ──────────────────────────────
        self._transition("RECONCILING", "stage5_reconcile")

        actual_locations: dict[str, str] = {}
        for move in approved_moves:
            t0 = time.monotonic()
            r = await self.soti.get_device(move.current_device)
            duration_ms = int((time.monotonic() - t0) * 1000)
            actual_locations[move.current_device] = r.get("folder", "UNKNOWN")
            append_tool_call(self.run_doc, "soti.get_device",
                             {"device": move.current_device}, r, duration_ms)

        recon_result = reconcile(approved_moves, actual_locations)

        # Persist move exceptions to Cosmos for audit
        for exc_item in recon_result.unmoved + recon_result.unidentified:
            cosmos_audit.append_move_exception(
                self.run_id,
                device=exc_item.get("device", "?"),
                intended_folder=next(
                    (m.target_folder for m in approved_moves
                     if m.current_device == exc_item.get("device")), "?"),
                actual_folder=actual_locations.get(exc_item.get("device", ""), "UNKNOWN"),
                reason=exc_item.get("reason", ""),
            )

        recon_result.summary_text = self.recon_narrator.narrate({
            "moved": recon_result.moved,
            "unmoved": recon_result.unmoved,
            "unidentified": recon_result.unidentified,
        })

        # Workbook was written by brampton.py (Stage 4). Record its path here.
        output_wb_path = _workbook_path
        log.info("Stage 5 — 5-tab workbook from Stage 4: %s", output_wb_path)

        append_step(self.run_doc, "stage5_reconcile", "DONE", {
            "moved": len(recon_result.moved),
            "unmoved": len(recon_result.unmoved),
            "unidentified": len(recon_result.unidentified),
            "summary": recon_result.summary_text,
            "output_workbook": output_wb_path,
        })
        save_run_doc(self.run_doc)
        log.info("Stage 5 complete — %d moved, %d unmoved, %d unidentified",
                 len(recon_result.moved), len(recon_result.unmoved),
                 len(recon_result.unidentified))

        # ── Stage 6: HITL post-move validation ───────────────────────────────
        self._transition("AWAITING_VALIDATION", "stage6_hitl_validation")

        decision = prompt_post_move_validation(recon_result, self.run_id)
        append_approval(self.run_doc, "HITL-3", decision, "")
        cosmos_audit.append_hitl_event(self.run_id, "HITL-3", decision,
                                       context={"moved": len(recon_result.moved),
                                                "unmoved": len(recon_result.unmoved)})

        if decision == "rerun":
            self._transition("FAILED", "stage6_validation", {"reason": "HITL-3 rerun"})
            append_step(self.run_doc, "stage6_validation", "RERUN_REQUESTED", {})
            save_run_doc(self.run_doc)
            log.warning("Rerun requested by L2 | run_id=%s", self.run_id)
            return

        # Post-HITL-3 narrator: LLM responds to the human's validation decision
        post_validation_summary = self.recon_narrator.narrate({
            "event": "post_hitl3_decision",
            "decision": decision,
            "moved_count": len(recon_result.moved),
            "unmoved_count": len(recon_result.unmoved),
            "unidentified_count": len(recon_result.unidentified),
            "unmoved": recon_result.unmoved,
            "unidentified": recon_result.unidentified,
        })
        log.info("Post-HITL-3 LLM: %s", post_validation_summary)
        append_step(self.run_doc, "stage6_post_hitl3", "DONE",
                    {"post_decision_summary": post_validation_summary})
        save_run_doc(self.run_doc)

        if len(recon_result.moved) == 0:
            self._transition("COMPLETED", "stage6_validation",
                             {"reason": "no movements"}, triggered_by="system")
            append_step(self.run_doc, "stage6_validation", "SKIPPED_NO_MOVEMENTS", {})
            save_run_doc(self.run_doc)
            log.info("No movements — run completed without SR | run_id=%s", self.run_id)
            return

        # ── Stage 7: Draft SR notes (LLM prose) ──────────────────────────────
        self._transition("DRAFTING_SR", "stage7_draft_sr")

        sr_notes = self.exec_narrator.narrate({
            "moved": recon_result.moved,
            "run_id": self.run_id,
        })

        # Append Fleet.xlsx tracker row
        _append_fleet_tracker(self.run_id, recon_result.moved)

        self._transition("AWAITING_SR_APPROVAL", "stage7_hitl4")

        decision = prompt_sr_closure(sr_notes, self.run_id)
        append_approval(self.run_doc, "HITL-4", decision, "")
        cosmos_audit.append_hitl_event(self.run_id, "HITL-4", decision,
                                       context={"sr_notes_len": len(sr_notes)})

        if decision == "hold":
            self._transition("ON_HOLD", "stage7_sr", {"reason": "HITL-4 hold"})
            append_step(self.run_doc, "stage7_sr", "ON_HOLD", {})
            save_run_doc(self.run_doc)
            return

        # Post-HITL-4 narrator: LLM generates final closure summary based on decision
        post_closure_summary = self.exec_narrator.narrate({
            "event": "post_hitl4_decision",
            "decision": decision,
            "run_id": self.run_id,
            "moved": recon_result.moved,
            "sr_notes_draft": sr_notes,
        })
        log.info("Post-HITL-4 LLM: %s", post_closure_summary)
        append_step(self.run_doc, "stage7_post_hitl4", "DONE",
                    {"post_decision_summary": post_closure_summary})
        save_run_doc(self.run_doc)

        # ── Stage 8: Wrap-up ─────────────────────────────────────────────────
        self._transition("EXECUTING", "stage8_complete")
        sr_number = f"SR-MOCK-{self.run_id}"
        # TODO: real ServiceNow MCP call — Phase 2

        self._transition("COMPLETED", "stage8_complete",
                         {"sr_number": sr_number}, triggered_by="system")
        append_step(self.run_doc, "stage8_complete", "DONE",
                    {"sr_number": sr_number, "sr_notes": sr_notes})
        save_run_doc(self.run_doc)
        log.info("Stage 8 complete — COMPLETED | sr_number=%s | run_id=%s",
                 sr_number, self.run_id)

        await self.soti.disconnect()
        await self.fleet.disconnect()


# ── Fleet.xlsx tracker ────────────────────────────────────────────────────────

def _append_fleet_tracker(run_id: str, moved: list[dict]) -> None:
    """
    Append one row per successfully moved device to the Fleet.xlsx tracker.
    File is created with headers if it doesn't exist yet.
    Stored in state/Fleet.xlsx — Phase 2 will push via Microsoft Graph API.
    """
    if not moved:
        return
    try:
        import openpyxl
        from openpyxl import Workbook, load_workbook

        tracker_path = os.path.join(config.STATE_DIR, "Fleet.xlsx")
        os.makedirs(config.STATE_DIR, exist_ok=True)

        headers = ["Run ID", "Device", "From Folder", "To Folder", "Timestamp UTC"]

        if os.path.exists(tracker_path):
            wb = load_workbook(tracker_path)
            ws = wb.active
            # Idempotency: remove any existing rows for this run_id before re-appending
            existing_rows = [
                row for row in ws.iter_rows(min_row=2, values_only=False)
                if row[0].value == run_id
            ]
            for row in existing_rows:
                ws.delete_rows(row[0].row)
        else:
            wb = Workbook()
            ws = wb.active
            ws.title = "Fleet Movements"
            ws.append(headers)

        ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        for item in moved:
            ws.append([
                run_id,
                item.get("device", ""),
                item.get("from_folder", ""),
                item.get("to_folder", ""),
                ts,
            ])

        wb.save(tracker_path)
        log.info("Fleet.xlsx tracker updated — %d row(s) appended | path=%s",
                 len(moved), tracker_path)
    except Exception as exc:
        log.warning("Fleet.xlsx tracker update failed (non-fatal): %s", exc)
