# Generated by GitHub Copilot
"""
CLI entry point for the BRT Fleet Movement orchestrator.

Usage:
    python run.py BRT-2026-06-16
    python run.py BRT-2026-06-16 --auto       # auto-approve all HITL gates
    python run.py BRT-2026-06-16 --resume     # resume existing run
"""
import sys
import asyncio
import argparse
import logging

# Ensure UTF-8 output on Windows (handles → and other Unicode in log messages)
if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")
if sys.stderr.encoding and sys.stderr.encoding.lower() != "utf-8":
    sys.stderr.reconfigure(encoding="utf-8", errors="replace")

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    datefmt="%Y-%m-%dT%H:%M:%S",
)

import config  # noqa: E402 — load .env before parsing args


def main() -> None:
    """Parse CLI args and launch the orchestrator."""
    parser = argparse.ArgumentParser(
        description="BRT Fleet Movement orchestrator (Phase 1)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    parser.add_argument(
        "run_id",
        help="Unique run identifier, e.g. BRT-2026-06-16",
    )
    parser.add_argument(
        "--auto",
        action="store_true",
        help="Auto-approve all HITL gates (sets USE_MOCK_HITL=True)",
    )
    parser.add_argument(
        "--resume",
        action="store_true",
        help="Print existing run state and continue (informational for Phase 1)",
    )
    args = parser.parse_args()

    # --auto overrides env; safe because it only affects HITL prompts
    if args.auto:
        config.USE_MOCK_HITL = True

    if args.resume:
        from core.state_store import load_run_doc
        existing = load_run_doc(args.run_id)
        if existing:
            logging.getLogger(__name__).info(
                "Existing run found: state=%s step=%s",
                existing.state,
                existing.current_step,
            )
        else:
            logging.getLogger(__name__).info(
                "No saved run for '%s' — starting fresh.", args.run_id
            )

    from orchestrator import Orchestrator
    orch = Orchestrator(args.run_id)
    asyncio.run(orch.run())


if __name__ == "__main__":
    main()
