# Generated by GitHub Copilot
"""
Azure Blob Storage writer for BRT Fleet pipeline outputs.

Upload priority (mirrors excel_parser._download_blob auth order):
  1. Storage account key  (AZURE_STORAGE_ACCOUNT_KEY — local dev)
  2. ManagedIdentityCredential  (Container Apps Job in Azure — production)
  3. AzureCliCredential  (local dev after az login)

Returns the public blob URL (no SAS token) — the portal/dashboard resolves
access via the job's managed identity or a separately issued read SAS.
"""
import logging
import os

import config

log = logging.getLogger(__name__)

_ACCOUNT_URL_TMPL = "https://{account}.blob.core.windows.net"


def _get_blob_service_client():
    from azure.storage.blob import BlobServiceClient

    account_url = _ACCOUNT_URL_TMPL.format(account=config.AZURE_STORAGE_ACCOUNT_NAME)

    if config.AZURE_STORAGE_ACCOUNT_KEY:
        return BlobServiceClient(
            account_url=account_url,
            credential=config.AZURE_STORAGE_ACCOUNT_KEY,
        )

    # In Azure Container Apps Job the managed identity is available automatically
    try:
        from azure.identity import ManagedIdentityCredential
        return BlobServiceClient(
            account_url=account_url,
            credential=ManagedIdentityCredential(),
        )
    except Exception:
        pass

    # Fallback — local dev with az login
    from azure.identity import AzureCliCredential
    _AZ_WBIN = r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin"
    if os.name == "nt" and _AZ_WBIN not in os.environ.get("PATH", ""):
        os.environ["PATH"] = _AZ_WBIN + os.pathsep + os.environ.get("PATH", "")
    return BlobServiceClient(
        account_url=account_url,
        credential=AzureCliCredential(),
    )


def upload_workbook(local_path: str, run_id: str) -> str:
    """
    Upload the 5-tab movement workbook to Blob Storage.

    Blob path: workbooks/{run_id}/{filename}
    Returns the full blob URL (no SAS token).
    Raises on failure — caller should catch and treat as non-fatal.
    """
    if config.USE_MOCK_BLOB:
        log.info("blob_store.upload_workbook: USE_MOCK_BLOB=true — skipping upload")
        return ""

    if not local_path or not os.path.exists(local_path):
        log.warning("blob_store.upload_workbook: local file not found: %s", local_path)
        return ""

    filename = os.path.basename(local_path)
    blob_name = f"out/{run_id}/{filename}"
    container = config.AZURE_BLOB_OUTPUT_CONTAINER

    client = _get_blob_service_client()
    blob_client = client.get_blob_client(container=container, blob=blob_name)

    with open(local_path, "rb") as fh:
        blob_client.upload_blob(fh, overwrite=True)

    url = f"{_ACCOUNT_URL_TMPL.format(account=config.AZURE_STORAGE_ACCOUNT_NAME)}/{container}/{blob_name}"
    log.info("blob_store.upload_workbook: uploaded → %s", url)
    return url
