# Generated by GitHub Copilot
"""
Cosmos DB audit writer — persists run state, checkpoints, HITL decisions,
and move exceptions to Azure Cosmos DB for MongoDB vCore.

Uses the same COSMOS_CONNECTION_STRING as the intake reader (cosmos_client.py).
Collections mirror the design from HITL-and-Cosmos-state-capture/cosmos_client.py
but use pymongo instead of azure-cosmos SDK (MongoDB vCore uses mongo wire protocol).

Collections created automatically on first write:
  - run_states       : mutable run document (upserted on every state change)
  - checkpoints      : immutable state-transition log (append only)
  - hitl_events      : human gate decisions with context snapshot (append only)
  - move_exceptions  : reconciliation discrepancies (append only, 180-day TTL)
"""
import logging
from datetime import datetime, timezone
from typing import Any

import config

log = logging.getLogger(__name__)

# Module-level mongo client — reused within process lifetime
_client = None
_db = None


def _get_db():
    """Return cached pymongo database handle. Lazy-initialised."""
    global _client, _db
    if _db is None:
        from pymongo import MongoClient
        if not config.COSMOS_CONNECTION_STRING:
            raise RuntimeError("COSMOS_CONNECTION_STRING not set.")
        _client = MongoClient(config.COSMOS_CONNECTION_STRING)
        _db = _client[config.COSMOS_DATABASE]
    return _db


def _ts() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── All audit writes disabled — pipeline uses movement collection only ────────
# run_states, checkpoints, hitl_events, move_exceptions are not written.
# Re-enable individually when audit persistence is needed.

def upsert_run_state(run_id: str, state: str, step: str, extra: dict | None = None) -> None:
    return


def append_checkpoint(run_id: str, from_state: str, to_state: str,
                      triggered_by: str = "system", payload: dict | None = None) -> None:
    return


def append_hitl_event(run_id: str, gate: str, decision: str,
                      operator_id: str = "system", notes: str = "",
                      context: dict | None = None) -> None:
    return


def append_move_exception(run_id: str, device: str, intended_folder: str,
                          actual_folder: str, reason: str) -> None:
    return
