# Generated by GitHub Copilot
"""
Cosmos DB audit writer — persists run state, checkpoints, HITL decisions,
and move exceptions to Azure Cosmos DB for MongoDB vCore.

Uses the same COSMOS_CONNECTION_STRING as the intake reader (cosmos_client.py).
Collections mirror the design from HITL-and-Cosmos-state-capture/cosmos_client.py
but use pymongo instead of azure-cosmos SDK (MongoDB vCore uses mongo wire protocol).

Collections created automatically on first write:
  - run_states       : mutable run document (upserted on every state change)
  - checkpoints      : immutable state-transition log (append only)
  - hitl_events      : human gate decisions with context snapshot (append only)
  - move_exceptions  : reconciliation discrepancies (append only, 180-day TTL)
"""
import logging
from datetime import datetime, timezone
from typing import Any

import config

log = logging.getLogger(__name__)

# Module-level mongo client — reused within process lifetime
_client = None
_db = None


def _get_db():
    """Return cached pymongo database handle. Lazy-initialised."""
    global _client, _db
    if _db is None:
        from pymongo import MongoClient
        if not config.COSMOS_CONNECTION_STRING:
            raise RuntimeError("COSMOS_CONNECTION_STRING not set.")
        _client = MongoClient(config.COSMOS_CONNECTION_STRING)
        _db = _client[config.COSMOS_DATABASE]
    return _db


def _ts() -> str:
    return datetime.now(timezone.utc).isoformat()


# ── run_states ───────────────────────────────────────────────────────────────

def upsert_run_state(run_id: str, state: str, step: str, extra: dict | None = None) -> None:
    """
    Upsert the mutable run document.
    Called on every state transition so the portal always shows current state.
    """
    if config.USE_MOCK_COSMOS:
        return
    try:
        db = _get_db()
        doc: dict[str, Any] = {
            "run_id":       run_id,
            "state":        state,
            "current_step": step,
            "updated_utc":  _ts(),
        }
        if extra:
            doc.update(extra)
        db["run_states"].update_one(
            {"run_id": run_id},
            {"$set": doc, "$setOnInsert": {"created_utc": _ts()}},
            upsert=True,
        )
    except Exception as exc:
        log.warning("cosmos_audit.upsert_run_state failed (non-fatal): %s", exc)


# ── checkpoints ──────────────────────────────────────────────────────────────

def append_checkpoint(run_id: str, from_state: str, to_state: str,
                      triggered_by: str = "system", payload: dict | None = None) -> None:
    """
    Append one immutable checkpoint document.
    Mirrors Checkpoint dataclass from HITL-and-Cosmos-state-capture/models.py.
    """
    if config.USE_MOCK_COSMOS:
        return
    try:
        db = _get_db()
        db["checkpoints"].insert_one({
            "run_id":       run_id,
            "from_state":   from_state,
            "to_state":     to_state,
            "triggered_by": triggered_by,
            "payload":      payload or {},
            "timestamp":    _ts(),
            "partition_key": run_id,
        })
    except Exception as exc:
        log.warning("cosmos_audit.append_checkpoint failed (non-fatal): %s", exc)


# ── hitl_events ──────────────────────────────────────────────────────────────

def append_hitl_event(run_id: str, gate: str, decision: str,
                      operator_id: str = "system", notes: str = "",
                      context: dict | None = None) -> None:
    """
    Record a human gate decision.
    Mirrors HITLEvent dataclass from HITL-and-Cosmos-state-capture/models.py.
    """
    if config.USE_MOCK_COSMOS:
        return
    try:
        db = _get_db()
        db["hitl_events"].insert_one({
            "run_id":           run_id,
            "gate":             gate,
            "decision":         decision,
            "operator_id":      operator_id,
            "notes":            notes,
            "context_snapshot": context or {},
            "timestamp":        _ts(),
            "partition_key":    run_id,
        })
    except Exception as exc:
        log.warning("cosmos_audit.append_hitl_event failed (non-fatal): %s", exc)


# ── move_exceptions ───────────────────────────────────────────────────────────

def append_move_exception(run_id: str, device: str, intended_folder: str,
                          actual_folder: str, reason: str) -> None:
    """
    Record a reconciliation discrepancy (intended vs actual SOTI path).
    180-day TTL is set by creating a TTL index on first use — done once.
    """
    if config.USE_MOCK_COSMOS:
        return
    try:
        db = _get_db()
        col = db["move_exceptions"]
        # Ensure TTL index exists (idempotent — Mongo ignores if already present)
        col.create_index("timestamp", expireAfterSeconds=60 * 60 * 24 * 180,
                         background=True)
        col.insert_one({
            "run_id":          run_id,
            "device":          device,
            "intended_folder": intended_folder,
            "actual_folder":   actual_folder,
            "reason":          reason,
            "timestamp":       datetime.now(timezone.utc),   # datetime for TTL index
            "partition_key":   run_id,
        })
    except Exception as exc:
        log.warning("cosmos_audit.append_move_exception failed (non-fatal): %s", exc)
