# Generated by GitHub Copilot
"""
Cosmos DB for MongoDB vCore client — reads intake records written by the
upstream Intake Function.

Authentication: SCRAM-SHA-256 via connection string stored in .env.
The connection string MUST live in COSMOS_CONNECTION_STRING env var only —
never hard-coded in source.

Collection document schema matches schemas/intake_record.py (IntakeRecord).
"""
import logging
from datetime import datetime, timezone

import config
from schemas.intake_record import AttachmentDetails, IntakeRecord, StructuralCheck
from schemas.intended_move import IntendedMove

log = logging.getLogger(__name__)

# Module-level client — reused across calls within a single process lifetime
_mongo_client = None


def _get_client():
    """
    Return a cached pymongo MongoClient.
    Lazy-initialised on first real (non-mock) call.
    TLS is enforced by the connection string itself.
    """
    global _mongo_client
    if _mongo_client is None:
        from pymongo import MongoClient

        if not config.COSMOS_CONNECTION_STRING:
            raise RuntimeError(
                "COSMOS_CONNECTION_STRING not set. "
                "Add it to .env — see .env.example for the format. "
                "Keep USE_MOCK_COSMOS=True until the credential is configured."
            )

        _mongo_client = MongoClient(config.COSMOS_CONNECTION_STRING)
    return _mongo_client


async def get_intake_record(intake_id: str) -> IntakeRecord | None:
    """
    Fetch a single intake record by its _id / id field.
    Returns None when no READY_FOR_RUN record exists — caller triggers HITL-1.

    Note: pymongo is synchronous; the async signature is kept for interface
    consistency with the orchestrator. For Phase 1 the call is fast (point read)
    so blocking the event loop is acceptable. Phase 2 can swap in motor (async).
    """
    if config.USE_MOCK_COSMOS:
        return _mock_intake_record(intake_id)

    if not config.COSMOS_DATABASE:
        raise RuntimeError(
            "COSMOS_DATABASE not set. "
            "Check Data Explorer in the portal and add the database name to .env."
        )

    try:
        client = _get_client()
        db = client[config.COSMOS_DATABASE]
        collection = db[config.COSMOS_INTAKE_COLLECTION]

        # Point read — Cosmos stores the intake id as the Mongo _id; some
        # writers also set a separate "id" field. Match either.
        doc = collection.find_one({"_id": intake_id}) or collection.find_one({"id": intake_id})

        if doc is None:
            log.warning("No document found in Cosmos for intake_id='%s'", intake_id)
            return None

        if doc.get("status") != "READY_FOR_RUN":
            log.warning(
                "Intake record '%s' found but status='%s' — expected READY_FOR_RUN",
                intake_id,
                doc.get("status"),
            )
            return None

        # Expose the Mongo _id as "id" for the mapper, then drop the raw _id.
        if not doc.get("id"):
            doc["id"] = doc.get("_id")
        doc.pop("_id", None)
        return _map_doc_to_intake_record(doc)

    except Exception as exc:
        log.error("Cosmos DB read failed for '%s': %s", intake_id, exc)
        return None


def _map_doc_to_intake_record(doc: dict) -> IntakeRecord:
    """
    Map the camelCase Cosmos DB document fields to the IntakeRecord Pydantic schema.
    Cosmos document uses nested objects (email, attachment, structuralCheck);
    IntakeRecord uses flat fields.
    """
    email = doc.get("email", {})
    att = doc.get("attachment", {})
    sc = doc.get("structuralCheck", {})

    return IntakeRecord(
        id=doc.get("id") or doc.get("_id"),
        agency=doc.get("agency", "BRT"),
        source=doc.get("source", "email"),
        email_message_id=email.get("messageId"),
        sender=email.get("from"),
        subject=email.get("subject"),
        received_utc=email.get("receivedUtc"),
        attachment=AttachmentDetails(
            file_name=att.get("fileName", "DVA.xlsx"),
            blob_uri=att.get("blobUri", ""),
            file_size_bytes=att.get("sizeBytes"),
            sha256=att.get("sha256"),
        ),
        structural_check=StructuralCheck(
            is_xlsx=sc.get("isXlsx", True),
            has_vehicle_status_column=sc.get("hasVehicleStatusColumn", True),
            sheet_name=sc.get("sheetName"),
        ),
        status=doc.get("status", ""),
        created_utc=doc.get("createdUtc", datetime.now(timezone.utc)),
    )


def _agency_from_intake_id(intake_id: str) -> str:
    """
    Derive agency from intake ID.
    e.g. "intake_BRT-2026-05-27" → "BRT"
    """
    parts = intake_id.replace("-", "_").split("_")
    return parts[1] if len(parts) >= 2 else "BRT"


async def get_movements_from_db(run_id: str) -> list[IntendedMove]:
    """
    Fetch movement records from the Cosmos DB `movement` collection and
    convert them into IntendedMove objects — replacing Excel file parsing.

    Each document has:
        dva.busNumber    → bus number
        dva.vehicleStatus → ON / In Maintenance / Off-Site (LTM)

    Returns an empty list if the collection has no records for this run_id,
    causing the orchestrator to fall back to Excel parsing.
    """
    try:
        client = _get_client()
        db = client[config.COSMOS_DATABASE]
        collection = db[config.COSMOS_MOVEMENT_COLLECTION]

        docs = list(collection.find({"runId": run_id}))
        if not docs:
            log.warning(
                "No movement records found in Cosmos for runId='%s' — will fall back to Excel",
                run_id,
            )
            return []

        log.info(
            "Fetched %d movement records from Cosmos for runId='%s'",
            len(docs), run_id,
        )

        moves: list[IntendedMove] = []
        for doc in docs:
            dva = doc.get("dva", {})
            bus = str(dva.get("busNumber", "")).strip()
            status = str(dva.get("vehicleStatus", "")).strip()

            if not bus or not status:
                continue

            # Derive target folder from vehicle status (same logic as excel_parser)
            s = status.lower()
            if s in ("on", "in maintenance"):
                target: str = "Production"
            elif any(kw in s for kw in ("off-site", "ltm")):
                target = "LTM"
            else:
                log.warning("Unrecognised vehicleStatus '%s' for bus %s — skipping", status, bus)
                continue

            # Derive device names using per-type suffix convention:
            #   DCU:  BRT_DCU_{bus}_1  (SOTI_DCU_SUFFIX=_1)
            #   BFTP: BRT_BFTP_{bus}_2 (SOTI_BFTP_SUFFIX=_2)
            bus_padded = bus.lstrip("0").zfill(config.SOTI_BUS_DIGITS) if bus.isdigit() else bus
            for dev_type, device_name in (
                ("DCU",  f"BRT_DCU_{bus_padded}{config.SOTI_DCU_SUFFIX}"),
                ("BFTP", f"BRT_BFTP_{bus_padded}{config.SOTI_BFTP_SUFFIX}"),
            ):
                moves.append(IntendedMove(
                    bus_number=bus,
                    current_device=device_name,
                    device_type=dev_type,  # type: ignore[arg-type]
                    target_folder=target,  # type: ignore[arg-type]
                    vehicle_status=status,
                    reason=f"[{dev_type}] Status '{status}' maps to {target} (from Cosmos DB)",
                ))

        log.info(
            "Built %d IntendedMove objects from %d Cosmos movement records",
            len(moves), len(docs),
        )
        return moves

    except Exception as exc:
        log.error("Cosmos movement fetch failed for runId='%s': %s", run_id, exc)
        return []


# ── Mock implementation ───────────────────────────────────────────────────────

def _mock_intake_record(intake_id: str) -> IntakeRecord:
    """
    Return a synthetic READY_FOR_RUN record so the pipeline runs immediately
    without a real Cosmos DB connection.
    The mock blob_uri points to the local sample file so excel_parser works.
    """
    log.debug("[MOCK COSMOS] Returning synthetic intake record for '%s'", intake_id)
    return IntakeRecord(
        id=intake_id,
        agency=_agency_from_intake_id(intake_id),
        source="email",
        email_message_id="mock-message-id-001",
        sender="PRESTODeviceAvailability@brampton.ca",
        subject=f"Brampton DVA | {intake_id}",
        received_utc=datetime.now(timezone.utc),
        attachment=AttachmentDetails(
            file_name="DVA.xlsx",
            blob_uri=config.SAMPLE_DVA,
            file_size_bytes=None,
            sha256=None,
        ),
        structural_check=StructuralCheck(
            is_xlsx=True,
            has_vehicle_status_column=True,
            sheet_name="Sheet1",
        ),
        status="READY_FOR_RUN",
        created_utc=datetime.now(timezone.utc),
    )
