# Generated by GitHub Copilot
"""
Cosmos DB audit writer — persists run state, HITL decisions, and move exceptions
to the `runs` collection in Azure Cosmos DB for MongoDB vCore.

The `runs` document is created by the intake pipeline before the orchestrator
runs. All functions here only update (never insert) the existing document,
except upsert_run_state which uses upsert=True as a safety net.

Document structure (abbreviated):
  _id / runId        : run_id (e.g. "BRT-2026-06-18")
  state              : current run state string
  currentStep        : current step name
  phase              : current phase letter (A-E)
  steps[]            : 21 fixed step objects — status updated in-place via arrayFilters
  hitl[]             : 6 gate objects — status/decidedUtc updated in-place via $
  revisions[]        : append-only state-transition log
  exceptions[]       : append-only move failure log
  counts             : aggregated move counts (updated at RECONCILE)
  outputs            : workbookBlobUri, srNumber, etc.
  updatedUtc         : updated on every write
"""
import logging
from datetime import datetime, timezone

import config

log = logging.getLogger(__name__)

# ── Step metadata — seq and phase for each of the 21 workflow steps ───────────
_STEP_META: dict[str, dict] = {
    "RECEIVE_DVA":      {"seq": 1,  "phase": "A"},
    "BIND_INTAKE":      {"seq": 2,  "phase": "A"},
    "PARSE_DVA":        {"seq": 3,  "phase": "B"},
    "STRUCTURAL_CHECK": {"seq": 4,  "phase": "B"},
    "SOTI_SNAPSHOT":    {"seq": 5,  "phase": "B"},
    "PLAN_MOVES":       {"seq": 6,  "phase": "B"},
    "RAISE_HITL2":      {"seq": 7,  "phase": "C"},
    "APPLY_EDITS":      {"seq": 8,  "phase": "C"},
    "RECHECK_SOTI":     {"seq": 9,  "phase": "C"},
    "APPROVE_HITL2":    {"seq": 10, "phase": "C"},
    "MOVE_DEVICES":     {"seq": 11, "phase": "D"},
    "VERIFY_MOVES":     {"seq": 12, "phase": "D"},
    "RECONCILE":        {"seq": 13, "phase": "D"},
    "RAISE_HITL3":      {"seq": 14, "phase": "D"},
    "APPROVE_HITL3":    {"seq": 15, "phase": "D"},
    "DRAFT_SR":         {"seq": 16, "phase": "E"},
    "RAISE_HITL4":      {"seq": 17, "phase": "E"},
    "CREATE_SR":        {"seq": 18, "phase": "E"},
    "WRITE_TRACKER":    {"seq": 19, "phase": "E"},
    "ISSUE_SUMMARY":    {"seq": 20, "phase": "E"},
    "COMPLETE":         {"seq": 21, "phase": "E"},
}

# HITL decision string → DB status (covers portal strings + internal strings)
_DECISION_STATUS: dict[str, str] = {
    "approve":        "APPROVED",
    "approve_all":    "APPROVED",
    "approve_subset": "APPROVED",
    "confirm":        "APPROVED",
    "reject":         "REJECTED",
    "rerun":          "RERUN_REQUESTED",
    "retry":          "RETRY",
}

# Module-level mongo client — reused within process lifetime
_client = None
_db = None


def _get_db():
    """Return cached pymongo database handle. Lazy-initialised."""
    global _client, _db
    if _db is None:
        from pymongo import MongoClient
        if not config.COSMOS_CONNECTION_STRING:
            raise RuntimeError("COSMOS_CONNECTION_STRING not set.")
        _client = MongoClient(config.COSMOS_CONNECTION_STRING)
        _db = _client[config.COSMOS_DATABASE]
    return _db


def _ts() -> str:
    return datetime.now(timezone.utc).isoformat()


def _col():
    return _get_db()[config.COSMOS_RUNS_COLLECTION]


# ── Public API ────────────────────────────────────────────────────────────────

def mark_step_started(run_id: str, step: str) -> None:
    """
    Mark a step as IN_PROGRESS, set startUtc, and increment attempts.
    Called at the beginning of each step (before work starts).
    Steps not in _STEP_META are silently skipped.
    """
    if step not in _STEP_META:
        return
    try:
        now = _ts()
        _col().update_one(
            {"_id": run_id},
            {
                "$set": {
                    "steps.$[elem].status":   "IN_PROGRESS",
                    "steps.$[elem].startUtc": now,
                    "updatedUtc":             now,
                },
                "$inc": {"steps.$[elem].attempts": 1},
            },
            array_filters=[{"elem.step": step}],
            upsert=True,
        )
        log.debug("cosmos_audit.mark_step_started: run=%s step=%s", run_id, step)
    except Exception:
        log.exception("cosmos_audit.mark_step_started failed (non-fatal): run=%s", run_id)


def upsert_run_state(run_id: str, state: str, step: str, extra: dict | None = None) -> None:
    """
    Update state, currentStep, phase, updatedUtc in the runs document.
    Also marks the matching step in steps[] as SUCCEEDED or FAILED.
    Any key/value pairs in `extra` are merged into the $set payload directly
    (use dotted paths for nested fields, e.g. "outputs.srNumber").
    Steps not in _STEP_META (e.g. MOVE_DEVICES_ERROR) are silently skipped
    for the steps[] array update.
    """
    try:
        now = _ts()
        meta = _STEP_META.get(step, {})
        phase = meta.get("phase", "?")
        step_status = "FAILED" if state in ("FAILED", "ABORTED") else "SUCCEEDED"

        set_fields: dict = {
            "state": state,
            "currentStep": step,
            "phase": phase,
            "updatedUtc": now,
        }
        if extra:
            # Only accept dotted-path keys (e.g. "outputs.srNumber", "counts.moved").
            # Reject plain keys that would pollute the document root.
            for k, v in extra.items():
                if "." in k:
                    set_fields[k] = v
                else:
                    log.warning("cosmos_audit: ignoring non-dotted extra key '%s'", k)

        update: dict = {"$set": set_fields}
        kwargs: dict = {"upsert": True}

        if step in _STEP_META:
            set_fields[f"steps.$[elem].status"] = step_status
            set_fields[f"steps.$[elem].endUtc"] = now
            kwargs["array_filters"] = [{"elem.step": step}]

        _col().update_one({"_id": run_id}, update, **kwargs)
        log.debug("cosmos_audit.upsert_run_state: run=%s state=%s step=%s", run_id, state, step)
    except Exception:
        log.exception("cosmos_audit.upsert_run_state failed (non-fatal): run=%s", run_id)


def append_checkpoint(run_id: str, from_state: str, to_state: str,
                      triggered_by: str = "system", payload: dict | None = None) -> None:
    """
    Push a revision entry to runs.revisions[].
    Maps directly to the {by, at, change} structure in the runs schema.
    """
    try:
        now = _ts()
        revision: dict = {
            "by": triggered_by,
            "at": now,
            "change": f"{from_state} \u2192 {to_state}",
        }
        if payload:
            revision["payload"] = payload

        _col().update_one(
            {"_id": run_id},
            {"$push": {"revisions": revision}, "$set": {"updatedUtc": now}},
            upsert=True,
        )
        log.debug("cosmos_audit.append_checkpoint: run=%s %s→%s", run_id, from_state, to_state)
    except Exception:
        log.exception("cosmos_audit.append_checkpoint failed (non-fatal): run=%s", run_id)


def append_hitl_event(run_id: str, gate: str, decision: str,
                      operator_id: str = "system", notes: str = "",
                      context: dict | None = None) -> None:
    """
    Update the matching gate in runs.hitl[] with decision status and timestamps.
    Sets raisedUtc only if it is currently null (first time the gate is touched).
    decidedBy is kept null until operator identity is captured.
    """
    try:
        now = _ts()
        status = _DECISION_STATUS.get(decision, decision.upper())

        # Use arrayFilters to safely target the specific gate by name.
        # Avoids the MongoDB array query trap where positional $ matches
        # the first element satisfying ANY part of the compound query.
        _col().update_one(
            {"_id": run_id},
            {"$set": {"hitl.$[elem].raisedUtc": now}},
            array_filters=[{"elem.gate": gate, "elem.raisedUtc": None}],
        )

        set_fields: dict = {
            "hitl.$[elem].status":      status,
            "hitl.$[elem].decidedUtc":  now,
            "hitl.$[elem].decidedBy":   None,  # operator identity not yet captured
            "hitl.$[elem].decisionNote": notes or None,
            "updatedUtc":               now,
        }
        _col().update_one(
            {"_id": run_id},
            {"$set": set_fields},
            array_filters=[{"elem.gate": gate}],
        )
        log.debug("cosmos_audit.append_hitl_event: run=%s gate=%s decision=%s", run_id, gate, decision)
    except Exception:
        log.exception("cosmos_audit.append_hitl_event failed (non-fatal): run=%s", run_id)


def append_tool_call(run_id: str, tool: str, args: dict, result: dict, duration_ms: int) -> None:
    """
    Push an external API call record to runs.toolCalls[].
    Mirrors state_store.append_tool_call but persists to Cosmos DB.
    """
    try:
        now = _ts()
        entry = {
            "tool":        tool,
            "args":        args,
            "result":      result,
            "durationMs":  duration_ms,
            "calledAt":    now,
        }
        _col().update_one(
            {"_id": run_id},
            {"$push": {"toolCalls": entry}, "$set": {"updatedUtc": now}},
            upsert=True,
        )
        log.debug("cosmos_audit.append_tool_call: run=%s tool=%s", run_id, tool)
    except Exception:
        log.exception("cosmos_audit.append_tool_call failed (non-fatal): run=%s", run_id)


def append_snapshot(run_id: str, trigger: str, device_lookup: dict) -> None:
    """
    Push a point-in-time SOTI device state snapshot to runs.snapshots[].
    Called at SOTI_SNAPSHOT (pre-move) and RECONCILE (post-move).
    Stores device name → folder mapping for audit purposes.
    """
    try:
        now = _ts()
        devices = [
            {"name": name, "folder": info.get("CurrentGroupFullName", "UNKNOWN")}
            for name, info in device_lookup.items()
        ]
        snapshot = {
            "takenAt":     now,
            "trigger":     trigger,
            "deviceCount": len(devices),
            "devices":     devices,
        }
        _col().update_one(
            {"_id": run_id},
            {"$push": {"snapshots": snapshot}, "$set": {"updatedUtc": now}},
            upsert=True,
        )
        log.debug("cosmos_audit.append_snapshot: run=%s trigger=%s devices=%d",
                  run_id, trigger, len(devices))
    except Exception:
        log.exception("cosmos_audit.append_snapshot failed (non-fatal): run=%s", run_id)


def append_move_exception(run_id: str, device: str, intended_folder: str,
                          actual_folder: str, reason: str) -> None:
    """
    Push a move failure entry to runs.exceptions[].
    Called once per unreconciled or unidentified device after Stage 5.
    """
    try:
        now = _ts()
        exception = {
            "device":          device,
            "intendedFolder":  intended_folder,
            "actualFolder":    actual_folder,
            "reason":          reason,
            "timestamp":       now,
        }
        _col().update_one(
            {"_id": run_id},
            {"$push": {"exceptions": exception}, "$set": {"updatedUtc": now}},
            upsert=True,
        )
        log.debug("cosmos_audit.append_move_exception: run=%s device=%s", run_id, device)
    except Exception:
        log.exception("cosmos_audit.append_move_exception failed (non-fatal): run=%s", run_id)


def mark_hitl_pending(run_id: str, gate: str, payload: dict) -> None:
    """
    Mark a HITL gate as PENDING in Cosmos with its payload.
    Called by hitl_console when the pipeline raises a gate.
    The portal reads this to render the approval UI.

    Strategy: try to update an existing hitl[] entry first (arrayFilters).
    If the document has no hitl[] array or no entry for this gate yet
    (matched_count == 0 / modified_count == 0), push a new entry so the
    gate is always visible regardless of whether intake pre-populated hitl[].
    """
    try:
        now = _ts()
        result = _col().update_one(
            {"_id": run_id},
            {
                "$set": {
                    "hitl.$[elem].status":    "PENDING",
                    "hitl.$[elem].raisedUtc": now,
                    "hitl.$[elem].payload":   payload,
                    "updatedUtc":             now,
                }
            },
            array_filters=[{"elem.gate": gate}],
        )
        # If no existing entry was updated, push a new gate entry into hitl[]
        if result.modified_count == 0:
            new_entry = {
                "gate":       gate,
                "status":     "PENDING",
                "raisedUtc":  now,
                "payload":    payload,
                "decidedUtc": None,
                "decidedBy":  None,
                "decidedDecision": None,
                "decisionNote":    None,
            }
            _col().update_one(
                {"_id": run_id},
                {"$push": {"hitl": new_entry}, "$set": {"updatedUtc": now}},
                upsert=True,
            )
            log.debug("cosmos_audit.mark_hitl_pending: pushed new entry run=%s gate=%s", run_id, gate)
        else:
            log.debug("cosmos_audit.mark_hitl_pending: updated existing run=%s gate=%s", run_id, gate)
    except Exception:
        log.exception("cosmos_audit.mark_hitl_pending failed (non-fatal): run=%s", run_id)


def record_hitl_decision(run_id: str, gate: str, decision: str,
                         decided_by: str = "ops-portal", note: str = "") -> None:
    """
    Write operator decision to hitl[] in Cosmos.
    Called by the ops portal after the operator approves/rejects.
    Stores both the raw decision string (decidedDecision) and the computed
    status (APPROVED / REJECTED / etc.) so the pipeline can poll either.
    """
    try:
        now = _ts()
        status = _DECISION_STATUS.get(decision, decision.upper())
        _col().update_one(
            {"_id": run_id},
            {
                "$set": {
                    "hitl.$[elem].status":           status,
                    "hitl.$[elem].decidedDecision":  decision,
                    "hitl.$[elem].decidedUtc":       now,
                    "hitl.$[elem].decidedBy":        decided_by,
                    "hitl.$[elem].decisionNote":     note or None,
                    "updatedUtc":                    now,
                }
            },
            array_filters=[{"elem.gate": gate}],
        )
        log.debug("cosmos_audit.record_hitl_decision: run=%s gate=%s decision=%s",
                  run_id, gate, decision)
    except Exception:
        log.exception("cosmos_audit.record_hitl_decision failed (non-fatal): run=%s", run_id)


def poll_hitl_decision(run_id: str, gate: str) -> str | None:
    """
    Return the raw decision string if the gate has been decided, or None if
    the gate is still PENDING (or not yet raised).
    Used by hitl_console to poll Cosmos instead of the local decision file.
    Falls back gracefully — any exception returns None so local-file polling
    continues to work as a backup.
    """
    try:
        doc = _col().find_one({"_id": run_id}, {"hitl": 1})
        if not doc:
            return None
        for entry in doc.get("hitl", []):
            if entry.get("gate") == gate and entry.get("status") not in (None, "PENDING"):
                # Return the raw decision string the portal submitted; fall back
                # to lowercased status if the field is missing (legacy records).
                return entry.get("decidedDecision") or entry.get("status", "").lower()
        return None
    except Exception:
        log.exception("cosmos_audit.poll_hitl_decision failed (non-fatal): run=%s", run_id)
        return None
