# Generated by GitHub Copilot
"""
DVA Excel parser — pure deterministic code, no LLM.
Reads the DVA spreadsheet and applies movement rules to produce IntendedMove objects.

Movement rules (pure code — no LLM involved):
  "ON" | "In Maintenance"        → Production
  "Off-Site" | contains "LTM"   → LTM
  anything else                  → schema_issue

Device name pattern: BRT_DCU_<bus>_<n>  OR  LTM_BRT_DCU_<bus>_<n>

If the DVA file does not exist and USE_MOCK_SOTI is True, a synthetic
sample file is created automatically so the pipeline runs immediately.
"""
import os
import re
import tempfile
from typing import Tuple

import pandas as pd

import config
from schemas.intended_move import IntendedMove

# ── Column name aliases — fuzzy-matched at parse time ───────────────────────
# If Metrolinx renames a column, add the new name here; the parser auto-detects.
_BUS_ALIASES    = ["bus #", "bus#", "bus number", "bus no", "bus no.", "vehicle #", "fleet #"]
# Ordered most-specific first — first match wins
_STATUS_ALIASES = ["vehicle status", "fleet status", "vehicle state", "device status", "status"]
# The real DVA has no Device Name column — device is derived as BRT_DCU_<bus>_1

_PRODUCTION_STATUSES = {"on", "in maintenance"}
_LTM_KEYWORDS = {"off-site", "ltm"}

_DEVICE_RE = re.compile(r"^(?:LTM_)?BRT_DCU_\d+_\d+$", re.IGNORECASE)


def _infer_target(vehicle_status: str) -> str | None:
    """
    Deterministically map vehicle status → target SOTI folder.
    Returns None when the status is unrecognised (caller emits schema_issue).
    """
    s = vehicle_status.strip().lower()
    if s in _PRODUCTION_STATUSES:
        return "Production"
    if any(kw in s for kw in _LTM_KEYWORDS):
        return "LTM"
    return None


def _create_sample_dva(path: str) -> None:
    """Create a synthetic DVA Excel matching the real Brampton DVA column structure."""
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    data = {
        "Bus #": [
            "601", "602", "603", "604", "605", "606", "607", "608",
            "609", "610", "611", "612",
        ],
        "Vendor": ["PDS"] * 12,
        "Bus Year/Type": ["2005 NOVA LFS40102"] * 12,
        "Garage": ["Clark"] * 6 + ["Bramalea"] * 6,
        "Vehicle Status": [
            "ON", "ON", "In Maintenance", "ON",
            "Off-Site", "LTM Stored", "ON", "In Maintenance",
            "LTM Stored", "ON", "Off-Site", "ON",
        ],
        "Updated On": ["2026-05-27"] * 12,
        "Reason for Maintenance": [
            "", "", "Scheduled PM", "",
            "", "", "", "Body repair",
            "", "", "", "",
        ],
        "Unit Status": ["Active"] * 12,
    }
    pd.DataFrame(data).to_excel(path, index=False)


def _download_blob(blob_uri: str) -> str:
    """
    Download a file from Azure Blob Storage to a local temp file.
    Uses DefaultAzureCredential (AzureCliCredential, ManagedIdentity, etc.).
    When USE_MOCK_BLOB is True the download is skipped and the local sample
    DVA is returned instead — use this for local dev without RBAC configured.
    Returns the local temp file path (or local sample path in mock mode).
    """
    if config.USE_MOCK_BLOB:
        import logging
        logging.getLogger(__name__).info(
            "USE_MOCK_BLOB=true — skipping Blob download, using local sample DVA"
        )
        # Auto-create the sample file if it doesn't exist yet
        if not os.path.exists(config.SAMPLE_DVA):
            _create_sample_dva(config.SAMPLE_DVA)
        return config.SAMPLE_DVA

    from azure.storage.blob import BlobClient
    from urllib.parse import urlparse, urlencode, parse_qs, urlunparse, urljoin

    # Priority 1 — container-level SAS URL (sp=r token from Azure portal).
    # Reconstruct the full blob URL by appending the SAS query string.
    sas_url = config.AZURE_STORAGE_SAS_URL
    if sas_url:
        # sas_url is the container SAS URL; extract just the query string (the token)
        parsed_sas = urlparse(sas_url)
        blob_parsed = urlparse(blob_uri.split("?")[0])  # strip any existing token
        # Build blob URL with SAS token appended
        blob_with_sas = blob_parsed._replace(query=parsed_sas.query).geturl()
        blob_client = BlobClient.from_blob_url(blob_with_sas)
    # Priority 2 — storage account key.
    elif config.AZURE_STORAGE_ACCOUNT_KEY:
        blob_client = BlobClient.from_blob_url(blob_uri, credential=config.AZURE_STORAGE_ACCOUNT_KEY)
    else:
        # Priority 3 — AzureCliCredential (requires az.cmd on PATH).
        from azure.identity import AzureCliCredential
        _AZ_WBIN = r"C:\Program Files\Microsoft SDKs\Azure\CLI2\wbin"
        if os.name == "nt" and _AZ_WBIN not in os.environ.get("PATH", ""):
            os.environ["PATH"] = _AZ_WBIN + os.pathsep + os.environ.get("PATH", "")
        blob_client = BlobClient.from_blob_url(blob_uri, credential=AzureCliCredential())

    suffix = os.path.splitext(blob_uri.split("?")[0])[-1] or ".xlsx"
    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=suffix)
    with open(tmp.name, "wb") as fh:
        fh.write(blob_client.download_blob().readall())
    return tmp.name


def parse_dva(file_path: str) -> Tuple[list[IntendedMove], list[dict]]:
    """
    Read DVA Excel and build the intended-moves list.
    Returns (intended_moves, schema_issues). Pure code — no LLM.

    file_path may be:
      - a local path (mock mode or local DVA file)
      - an Azure Blob Storage HTTPS URL (real mode — downloaded to a temp file)
    """
    _tmp_path = None

    if file_path.startswith("https://"):
        # Real mode: download from Blob Storage, parse the temp file
        _tmp_path = _download_blob(file_path)
        local_path = _tmp_path
    elif not os.path.exists(file_path):
        if config.USE_MOCK_SOTI:
            _create_sample_dva(file_path)
        else:
            raise FileNotFoundError(
                f"DVA file not found: {file_path}. "
                "Copy your DVA Excel into samples/sample_dva.xlsx"
            )
        local_path = file_path
    else:
        local_path = file_path

    try:
        df = pd.read_excel(local_path, dtype=str)
        df.columns = [c.strip() for c in df.columns]
        df = df.fillna("")

        # ── Auto-detect column names by fuzzy matching aliases ────────────────
        col_map = {c.lower(): c for c in df.columns}
        col_bus = next((col_map[a] for a in _BUS_ALIASES if a in col_map), None)
        col_status = next((col_map[a] for a in _STATUS_ALIASES if a in col_map), None)

        if col_bus is None:
            raise ValueError(
                f"DVA file has no recognised bus-number column. "
                f"Found: {list(df.columns)}. Expected one of: {sorted(_BUS_ALIASES)}"
            )
        if col_status is None:
            raise ValueError(
                f"DVA file has no recognised vehicle-status column. "
                f"Found: {list(df.columns)}. Expected one of: {sorted(_STATUS_ALIASES)}"
            )

        import logging
        logging.getLogger(__name__).info(
            "DVA columns detected — bus=%r  status=%r", col_bus, col_status
        )

        intended_moves: list[IntendedMove] = []
        schema_issues: list[dict] = []

        for idx, row in df.iterrows():
            bus = str(row.get(col_bus, "")).strip()
            status = str(row.get(col_status, "")).strip()

            if not bus:
                schema_issues.append(
                    {"row": int(idx), "issue": "missing bus number", "data": row.to_dict()}
                )
                continue

            # Derive device name from bus number (convention: BRT_DCU_<bus>_1)
            # Derive device names from bus number (brampton.py convention):
            #   DCU  → BRT_DCU_{bus}_1   (device type 136)
            #   BFTP → BRT_BFTP_{bus}_1  (device type 130)
            # Bus number is zero-padded to 4 digits to match SOTI naming.
            bus_padded = bus.lstrip("0").zfill(4) if bus.isdigit() else bus
            dcu_device  = f"BRT_DCU_{bus_padded}_1"
            bftp_device = f"BRT_BFTP_{bus_padded}_1"

            target = _infer_target(status)
            if target is None:
                schema_issues.append({
                    "row": int(idx),
                    "issue": f"unrecognised vehicle status '{status}'",
                    "data": row.to_dict(),
                })
                continue

            for device, dev_type in ((dcu_device, "DCU"), (bftp_device, "BFTP")):
                intended_moves.append(IntendedMove(
                    bus_number=bus,
                    current_device=device,
                    target_folder=target,  # type: ignore[arg-type]
                    vehicle_status=status,
                    reason=f"[{dev_type}] Status '{status}' maps to {target}",
                ))

        return intended_moves, schema_issues

    finally:
        # Clean up temp file downloaded from Blob Storage
        if _tmp_path and os.path.exists(_tmp_path):
            os.unlink(_tmp_path)
