# Generated by GitHub Copilot
"""
Reconciler — pure Python, no LLM.
Compares intended moves against actual device locations polled from SOTI
and classifies each outcome as moved / unmoved / unidentified.

summary_text is intentionally left empty here; ReconciliationNarrator fills it.
"""
from schemas.intended_move import IntendedMove
from schemas.agent_outputs import ReconciliationResult


def reconcile(
    intended_moves: list[IntendedMove],
    actual_locations: dict[str, str],   # {device_name: actual_folder}
) -> ReconciliationResult:
    """
    Deterministic reconciliation — no LLM.
    summary_text is populated later by ReconciliationNarrator.narrate().
    """
    moved: list[dict] = []
    unmoved: list[dict] = []
    unidentified: list[dict] = []

    for move in intended_moves:
        device = move.current_device

        if device not in actual_locations:
            unidentified.append({
                "device": device,
                "reason": "not found in SOTI poll response",
            })
            continue

        actual_folder = actual_locations[device]
        if actual_folder.lower() == move.target_folder.lower():
            moved.append({
                "device": device,
                "from_folder": "prior_state_unknown",   # SOTI mock omits prior folder
                "to_folder": actual_folder,
            })
        else:
            unmoved.append({
                "device": device,
                "reason": (
                    f"actual folder '{actual_folder}' "
                    f"!= expected '{move.target_folder}'"
                ),
            })

    return ReconciliationResult(
        moved=moved,
        unmoved=unmoved,
        unidentified=unidentified,
    )
