# Generated by GitHub Copilot
"""
Lightweight JSON state store — persists run documents to state/ directory.
No external DB required for Phase 1. Each run produces one file:
    state/run_<run_id>.json
"""
import json
import os
from datetime import datetime, timezone

import config
from schemas.run_doc import RunDoc


def _run_path(run_id: str) -> str:
    """Return absolute path for a run document, ensuring state/ exists."""
    os.makedirs(config.STATE_DIR, exist_ok=True)
    return os.path.join(config.STATE_DIR, f"run_{run_id}.json")


def save_run_doc(run_doc: RunDoc) -> None:
    """Persist the run document to disk as indented JSON."""
    path = _run_path(run_doc.run_id)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(run_doc.model_dump_json(indent=2))


def load_run_doc(run_id: str) -> RunDoc | None:
    """Load an existing run document; returns None if not found."""
    path = _run_path(run_id)
    if not os.path.exists(path):
        return None
    with open(path, "r", encoding="utf-8") as fh:
        return RunDoc.model_validate_json(fh.read())


def append_step(
    run_doc: RunDoc,
    step_name: str,
    status: str,
    output: dict,
) -> None:
    """Record a completed pipeline step with a UTC timestamp."""
    run_doc.steps.append({
        "step": step_name,
        "status": status,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
        "output": output,
    })


def append_tool_call(
    run_doc: RunDoc,
    tool: str,
    args: dict,
    result: dict,
    duration_ms: int,
) -> None:
    """Record an MCP tool call with arguments, result, and timing."""
    run_doc.tool_calls.append({
        "tool": tool,
        "args": args,
        "result": result,
        "duration_ms": duration_ms,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
    })


def append_approval(
    run_doc: RunDoc,
    gate: str,
    decision: str,
    note: str,
) -> None:
    """Record a HITL gate decision with operator note."""
    run_doc.approvals.append({
        "gate": gate,
        "decision": decision,
        "note": note,
        "timestamp_utc": datetime.now(timezone.utc).isoformat(),
    })
