# Generated by GitHub Copilot
"""
FleetMovementClient — calls brampton.py directly (no MCP stdio transport).

Importing brampton.py via sys.path avoids the Windows anyio/asyncio stdio
pipe deadlock that occurs when the 40-move JSON payload exceeds the pipe
buffer on the MCP subprocess transport.

The brampton_mcp_server/ still exists for external use. The orchestrator's
fleet_client API (connect, disconnect, run_fleet_movement) is unchanged.
"""

import json
import logging
import os
import sys

import config

logger = logging.getLogger(__name__)

# Lazy import — populated in connect()
_brampton = None


class FleetMovementClient:
    """
    Client for the BRT Fleet Movement executor (brampton.py).
    Calls brampton.run_fleet_movement() directly to avoid Windows stdio hangs.
    """

    def __init__(self):
        self._use_mock: bool = config.USE_MOCK_SOTI
        self.session = None      # kept for API compatibility
        self._stdio_ctx = None   # kept for API compatibility

    async def connect(self) -> None:
        """Load brampton.py from brampton_mcp_server/ into the current process."""
        if self._use_mock:
            return

        global _brampton
        if _brampton is None:
            mcp_cwd = config.FLEET_MCP_CWD
            # Load SOTI credentials from brampton_mcp_server/.env before import
            from dotenv import load_dotenv
            load_dotenv(os.path.join(mcp_cwd, ".env"), override=True)

            if mcp_cwd not in sys.path:
                sys.path.insert(0, mcp_cwd)
            import brampton as _brampton_module
            _brampton = _brampton_module

        logger.info("Fleet Movement client ready (direct brampton import)")

    async def disconnect(self) -> None:
        """No-op — no subprocess or socket to close."""
        pass

    async def run_fleet_movement(
        self,
        run_id: str,
        intended_moves: list[dict],
        mode: str = "MOCK",
        output_dir: str | None = None,
    ) -> dict:
        """
        Execute fleet device movements via brampton.run_fleet_movement().

        Parameters
        ----------
        run_id         : Unique run identifier
        intended_moves : List of IntendedMove dicts (current_device, target_folder, ...)
        mode           : "MOCK" (dry-run preview) | "LIVE" (real SOTI execution)
        output_dir     : Where to write the 5-tab workbook. Defaults to STATE_DIR.

        Returns
        -------
        dict: { run_id, mode, moved, unmoved, unidentified, workbook_path }
        """
        if output_dir is None:
            output_dir = os.path.abspath(config.STATE_DIR)

        if self._use_mock:
            return self._mock_result(run_id, intended_moves, mode, output_dir)

        logger.info(
            "Calling run_fleet_movement via brampton | run_id=%s mode=%s moves=%d",
            run_id, mode, len(intended_moves),
        )

        result = await _brampton.run_fleet_movement(
            run_id=run_id,
            intended_moves=intended_moves,
            mode=mode.upper(),
            output_dir=output_dir,
        )
        return result

    # ── Mock fallback ────────────────────────────────────────────────────────

    def _mock_result(
        self,
        run_id: str,
        intended_moves: list[dict],
        mode: str,
        output_dir: str,
    ) -> dict:
        """
        Return a simulated result without calling brampton.
        Used when USE_MOCK_SOTI=true.
        """
        mode = mode.upper()
        moved = [
            {
                "device":      m["current_device"],
                "bus_number":  m.get("bus_number", ""),
                "from_folder": "MOCK_CURRENT_FOLDER",
                "to_folder":   m["target_folder"],
                "mock":        True,
            }
            for m in intended_moves
        ]
        logger.info(
            "FleetMovementClient MOCK %s — run_id=%s simulated %d moves",
            mode, run_id, len(moved),
        )
        return {
            "run_id":        run_id,
            "mode":          mode,
            "moved":         moved,
            "unmoved":       [],
            "unidentified":  [],
            "workbook_path": os.path.join(output_dir, f"BRT_FleetMovement_{run_id}.xlsx"),
        }
