# Generated by GitHub Copilot
"""
SnowClient — calls snow_mcp_server directly (no MCP stdio transport).

Wraps snow_mcp_server.snow_client functions for consistent orchestrator API.
"""

import logging
import sys
import os

import config

# Add snow_mcp_server to path for direct import
snow_server_path = os.path.join(
    os.path.dirname(os.path.dirname(os.path.dirname(__file__))),
    "snow_mcp_server"
)
if snow_server_path not in sys.path:
    sys.path.insert(0, snow_server_path)

logger = logging.getLogger(__name__)


class SnowClient:
    """
    Client for ServiceNow Device Monitoring SR creation.
    Calls snow_mcp_server.snow_client.create_sr() directly.
    """

    async def connect(self) -> None:
        """Initialize SNOW client. No-op for direct import."""
        if config.USE_MOCK_SNOW:
            logger.info("SnowClient connected (MOCK mode — SR creation disabled)")
        else:
            logger.info("SnowClient connected (direct import mode)")

    async def disconnect(self) -> None:
        """Disconnect from SNOW. No-op for direct import."""
        logger.info("SnowClient disconnected")

    async def create_device_monitoring_sr(
        self,
        run_id: str,
        short_description: str,
        description: str,
    ) -> dict:
        """
        Create a Device Monitoring SR in ServiceNow.

        Args:
            run_id: BRT run identifier (e.g., "BRT-2026-06-18")
            short_description: SR short description
            description: Full SR description/notes

        Returns:
            dict with keys:
                - sr_number: ServiceNow request number (e.g., "REQ0123456")
                - sr_sys_id: ServiceNow sys_id
                - ritm_number: Request Item number (e.g., "RITM0123456")
                - ritm_sys_id: Request Item sys_id
        """
        if config.USE_MOCK_SNOW:
            sr_number = f"SR-MOCK-{run_id}"
            logger.info("SNOW mock mode — skipping real SR creation, placeholder=%s", sr_number)
            return {"sr_number": sr_number, "sr_sys_id": "", "ritm_number": "", "ritm_sys_id": ""}

        try:
            # Import here to allow lazy loading
            from snow_client import create_sr

            logger.info("Creating SNOW SR for run_id=%s", run_id)
            result = await create_sr(short_description, description)
            logger.info(
                "SNOW SR created: sr_number=%s ritm_number=%s",
                result.get("sr_number"),
                result.get("ritm_number"),
            )
            return result
        except Exception as e:
            logger.error("Failed to create SNOW SR: %s", str(e), exc_info=True)
            raise
