# Generated by GitHub Copilot
"""
SotiMcpClient — wraps the official `mcp` Python SDK to call the SOTI MCP server.
Supports stdio transport (default): launches soti_mcp_server/server.py as a subprocess.

Real tool names are taken directly from soti_mcp_server/tools.py:
  - search_devices_by_reference_id  -> find a device by reference ID
  - move_device_by_id               -> move a device to a parent group path
  - search_devices_by_group_path    -> search devices by group path
"""
import json
import logging
import config

logger = logging.getLogger(__name__)


def _safe_parse(text: str) -> any:
    """Parse JSON, returning None on empty or invalid response."""
    if not text or not text.strip():
        return None
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        logger.warning("SOTI MCP returned non-JSON: %s", text[:200])
        return {"raw": text}


class SotiMcpClient:
    """
    Async MCP client for the SOTI MobiControl server.
    All public methods are safe to call in mock mode before SOTI access is available.
    """

    def __init__(self):
        self.session = None
        self._use_mock: bool = config.USE_MOCK_SOTI
        self._stdio_ctx = None
        self._http_ctx = None

    async def connect(self) -> None:
        """Open the MCP transport and initialise the protocol session."""
        if self._use_mock:
            return

        if config.SOTI_MCP_TRANSPORT == "stdio":
            from mcp import ClientSession, StdioServerParameters
            from mcp.client.stdio import stdio_client

            params = StdioServerParameters(
                command=config.SOTI_MCP_COMMAND,
                args=config.SOTI_MCP_ARGS,
                cwd=config.SOTI_MCP_CWD,
            )
            self._stdio_ctx = stdio_client(params)
            read, write = await self._stdio_ctx.__aenter__()
            self.session = ClientSession(read, write)
            await self.session.__aenter__()
            await self.session.initialize()
            logger.info("SOTI MCP stdio session initialised")

        elif config.SOTI_MCP_TRANSPORT == "http":
            from mcp.client.streamable_http import streamablehttp_client

            self._http_ctx = streamablehttp_client(url=config.SOTI_MCP_HTTP_URL)
            read, write, _ = await self._http_ctx.__aenter__()
            self.session = ClientSession(read, write)
            await self.session.__aenter__()
            await self.session.initialize()
            logger.info("SOTI MCP HTTP session initialised")

        else:
            raise ValueError(
                f"Unknown SOTI_MCP_TRANSPORT: '{config.SOTI_MCP_TRANSPORT}'. "
                "Expected 'stdio' or 'http'."
            )

    async def list_tools(self) -> list[dict]:
        """List all tools exposed by the SOTI MCP server."""
        if self._use_mock:
            return self._mock_tools()
        result = await self.session.list_tools()
        return [{"name": t.name, "description": t.description} for t in result.tools]

    async def get_device(self, device_name: str) -> dict:
        """
        Fetch current device info from SOTI by reference ID (device name).
        Real tool: search_devices_by_reference_id
        Returns the first matching device dict, or empty dict if not found.
        """
        if self._use_mock:
            return self._mock_get_device(device_name)
        result = await self.session.call_tool(
            "search_devices_by_reference_id", {"reference_id": device_name}
        )
        text = result.content[0].text if result.content else ""
        data = _safe_parse(text)
        if data is None:
            return {}
        devices = data if isinstance(data, list) else data.get("devices", [])
        return devices[0] if devices else {}

    async def move_device(self, device_name: str, target_folder: str) -> dict:
        """
        Move a device to a SOTI group by device ID.
        Strategy: search by reference ID first to get the device ID, then move.
        Real tools: search_devices_by_reference_id -> move_device_by_id
        """
        if self._use_mock:
            return self._mock_move_device(device_name, target_folder)

        # Step 1 — resolve device name -> device ID
        search_result = await self.session.call_tool(
            "search_devices_by_reference_id", {"reference_id": device_name}
        )
        search_text = search_result.content[0].text if search_result.content else ""
        search_data = _safe_parse(search_text)
        if search_data is None:
            return {"name": device_name, "target": target_folder, "success": False,
                    "error": "empty response from SOTI search"}
        devices = search_data if isinstance(search_data, list) else search_data.get("devices", [])
        if not devices:
            return {"name": device_name, "target": target_folder, "success": False,
                    "error": "device not found in SOTI"}

        device = devices[0]
        device_id = (device.get("DeviceId") or device.get("deviceId")
                     or device.get("id") or device.get("DeviceID") or "")
        if not device_id:
            return {"name": device_name, "target": target_folder, "success": False,
                    "error": f"device found but DeviceId missing — keys: {list(device.keys())}"}

        # Step 2 — move to target folder path
        move_result = await self.session.call_tool(
            "move_device_by_id", {"device_id": device_id, "parent_path": target_folder}
        )
        move_text = move_result.content[0].text if move_result.content else ""
        move_data = _safe_parse(move_text) or {}
        return {"name": device_name, "device_id": device_id,
                "target": target_folder, "success": True, "response": move_data}

    async def search_devices(self, pattern: str) -> list[dict]:
        """
        Search for devices by group path pattern.
        Real tool: search_devices_by_group_path
        """
        if self._use_mock:
            return self._mock_search_devices(pattern)
        result = await self.session.call_tool(
            "search_devices_by_group_path", {"path": pattern}
        )
        text = result.content[0].text if result.content else ""
        data = _safe_parse(text)
        if data is None:
            return []
        return data if isinstance(data, list) else data.get("devices", [])

    async def disconnect(self) -> None:
        """Close MCP transport cleanly; safe to call even if never connected."""
        if self.session is not None:
            try:
                await self.session.__aexit__(None, None, None)
            except Exception:
                pass
        if self._stdio_ctx is not None:
            try:
                await self._stdio_ctx.__aexit__(None, None, None)
            except Exception:
                pass
        elif self._http_ctx is not None:
            try:
                await self._http_ctx.__aexit__(None, None, None)
            except Exception:
                pass

    # -- Mock implementations -------------------------------------------------

    def _mock_tools(self) -> list[dict]:
        return [
            {"name": "search_devices_by_reference_id", "description": "Find device by reference ID"},
            {"name": "move_device_by_id",               "description": "Move device to parent group"},
            {"name": "search_devices_by_group_path",    "description": "Search devices by group path"},
        ]

    def _mock_get_device(self, name: str) -> dict:
        folder = "LTM" if name.upper().startswith("LTM_") else "Production"
        return {"name": name, "folder": folder, "status": "online", "mock": True}

    def _mock_move_device(self, name: str, target: str) -> dict:
        return {"name": name, "target": target, "success": True, "mock": True}

    def _mock_search_devices(self, pattern: str) -> list[dict]:
        return [
            {"name": f"BRT_DCU_{pattern}_1", "folder": "Production", "mock": True},
        ]
