#!/usr/bin/env bash
# Generated by GitHub Copilot
# trigger.sh – Executed by the Azure Container Apps Job on cron schedule.
# Cron: "30 5 * * *"  →  5:30 AM UTC = 12:30 AM EST (UTC-5) / 1:30 AM EDT (UTC-4)
#
# NOTE on DST: EST is UTC-5 (Nov–Mar), EDT is UTC-4 (Mar–Nov).
# "30 5 * * *" targets 12:30 AM EST (winter).
# During EDT (summer) this fires at 1:30 AM local – adjust to "30 4 * * *" if
# strict local midnight-half is required year-round.

set -euo pipefail

# ── Configuration ───────────────────────────────────────────────────────────
# FUNC_APP_URL and FUNC_KEY are injected as environment variables when the
# Container Apps Job is created (see deploy/deploy_job.sh).
FUNC_APP_URL="${FUNC_APP_URL:-http://localhost:7071}"
FUNC_KEY="${FUNC_KEY:-}"  # Default empty for local testing

# Validate that required environment variables are set (fail fast)
if [ -z "${FUNC_APP_URL}" ]; then
  echo "[trigger.sh] ERROR: FUNC_APP_URL not set" >&2
  exit 1
fi

# Build a date-stamped run identifier  e.g. BRT-2026-06-16
RUN_ID="BRT-$(date +%Y-%m-%d)"

echo "[trigger.sh] Firing at $(date -u +%Y-%m-%dT%H:%M:%SZ) | runId=${RUN_ID}"

# ── POST to the HTTP starter ─────────────────────────────────────────────────
# -f  : fail on HTTP 4xx/5xx
# -s  : silent progress meter
# -S  : show errors even in silent mode
# -w  : print HTTP status code after the body
# Include ?code=${FUNC_KEY} for authentication; runId for tracking
STARTER_URL="${FUNC_APP_URL}/api/start?code=${FUNC_KEY}&runId=${RUN_ID}"

HTTP_STATUS=$(curl -fsS \
  -X POST \
  "${STARTER_URL}" \
  -H "Content-Type: application/json" \
  -w "\n%{http_code}" \
  | tee /dev/stderr | tail -1)

echo "[trigger.sh] HTTP response status: ${HTTP_STATUS}"

# Treat anything outside 2xx as a failure so the job reports non-zero exit
if [[ "${HTTP_STATUS}" -lt 200 || "${HTTP_STATUS}" -gt 299 ]]; then
  echo "[trigger.sh] ERROR: unexpected HTTP status ${HTTP_STATUS}" >&2
  exit 1
fi

echo "[trigger.sh] Orchestration started successfully."
