# Generated by GitHub Copilot
from typing import Literal
from pydantic import BaseModel
from .intended_move import IntendedMove


class ParserResult(BaseModel):
    status: Literal["success", "schema_error"]
    intended_moves: list[IntendedMove]
    schema_issues: list[dict]
    unidentified: list[dict]
    summary_text: str        # LLM-generated narrative for L2
    needs_hitl: bool


class ReconciliationResult(BaseModel):
    moved: list[dict]         # {device, from_folder, to_folder}
    unmoved: list[dict]       # {device, reason}
    unidentified: list[dict]  # {device, reason}
    summary_text: str = ""    # LLM-generated narrative for L2; populated post-reconcile


class ExecutionResult(BaseModel):
    sr_number: str | None
    sr_notes: str                   # LLM-generated SR notes
    summary_email_body: str         # LLM-generated email body
    fleet_xlsx_row_appended: bool
    status: Literal["success", "skipped_no_movements", "failed"]
