# Generated by GitHub Copilot
"""
Pydantic model for the Cosmos DB intake record created by the Intake Function
before the orchestrator starts (Section 4.2 of the design spec).

One record per agency per day, partition key = agency.
Partition key path: /agency
"""
from datetime import datetime
from pydantic import BaseModel


class AttachmentDetails(BaseModel):
    """DVA Excel attachment stored in Azure Blob storage (raw zone)."""
    file_name: str
    blob_uri: str        # e.g. raw/fleet/BRT/2026/05/27/{messageId}/DVA.xlsx
    file_size_bytes: int | None = None
    sha256: str | None = None


class StructuralCheck(BaseModel):
    """Lightweight structural validation done by the Intake Function."""
    is_xlsx: bool
    has_vehicle_status_column: bool
    sheet_name: str | None = None


class IntakeRecord(BaseModel):
    """
    Normalised intake record written to Cosmos DB by the Intake Function.
    Status is READY_FOR_RUN when the orchestrator may proceed.
    """
    id: str                          # e.g. "intake_BRT_2026-05-27"
    agency: str                      # "BRT"
    source: str                      # "email"
    email_message_id: str | None = None
    sender: str | None = None
    subject: str | None = None
    received_utc: datetime | None = None
    attachment: AttachmentDetails
    structural_check: StructuralCheck
    status: str                      # "READY_FOR_RUN" | "PROCESSING" | "COMPLETED"
    created_utc: datetime
