# Generated by GitHub Copilot
from typing import Literal, Optional
from pydantic import BaseModel


class IntendedMove(BaseModel):
    """A single device movement derived deterministically from the DVA Excel."""

    bus_number: str
    current_device: str
    target_folder: Literal["Production", "LTM"]
    vehicle_status: str
    reason: str
    # Populated by Stage 2b (read-only SOTI query) before approval
    current_soti_folder: Optional[str] = None
    # Set True when Stage 2b finds the device registered as LTM_BRT_DCU_* in SOTI
    # but the DVA says it should be in Production — indicates a stale LTM rename tag.
    # current_device is updated to the LTM_ prefixed name so Stage 4 moves the right device.
    stale_ltm_tag: bool = False
