# Generated by GitHub Copilot
from datetime import datetime
from pydantic import BaseModel, Field


class RunDoc(BaseModel):
    """Persistent record of a single fleet-movement run — written to state/run_<id>.json."""

    run_id: str
    intake_id: str
    agency: str
    state: str
    current_step: str
    dva_path: str
    started_utc: datetime
    steps: list[dict] = Field(default_factory=list)
    approvals: list[dict] = Field(default_factory=list)
    tool_calls: list[dict] = Field(default_factory=list)
    revisions: list[dict] = Field(default_factory=list)
