// Generated by GitHub Copilot
import type { RunStep, ToolCall } from '../types'

interface Props {
  steps: RunStep[]
  toolCalls: unknown[]
}

/** Chronological audit trail — steps + tool calls, oldest first. */
export default function AuditTail({ steps, toolCalls }: Props) {
  const reversed = [...steps].reverse()

  if (reversed.length === 0) {
    return <p className="text-sm text-slate-400 italic">No audit entries yet.</p>
  }

  return (
    <div className="space-y-1 max-h-72 overflow-y-auto pr-1" aria-label="Audit trail">
      {reversed.map((s, i) => (
        <div key={i} className="flex items-start gap-3 py-1.5 border-b border-slate-50 last:border-0">
          <span
            className={`w-2 h-2 rounded-full mt-1.5 shrink-0 ${
              s.status === 'DONE'   ? 'bg-green-400' :
              s.status === 'FAILED' ? 'bg-red-400'   :
              s.status === 'RUNNING'? 'bg-blue-400 animate-pulse' : 'bg-slate-300'
            }`}
            aria-hidden="true"
          />
          <div className="flex-1 min-w-0">
            <div className="flex items-center gap-2 flex-wrap">
              <span className="text-xs font-mono text-slate-700">{s.step}</span>
              <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded ${
                s.status === 'DONE'   ? 'bg-green-100 text-green-700' :
                s.status === 'FAILED' ? 'bg-red-100 text-red-700'     : 'bg-blue-100 text-blue-700'
              }`}>
                {s.status}
              </span>
              {s.output && Object.keys(s.output).length > 0 && (
                <span className="text-[10px] text-slate-400">
                  {Object.entries(s.output)
                    .filter(([k]) => ['count', 'moved', 'unmoved', 'approved_count', 'simulated_moves'].includes(k))
                    .map(([k, v]) => `${k}: ${v}`)
                    .join(' · ')}
                </span>
              )}
            </div>
            <div className="text-[10px] text-slate-400 mt-0.5 font-mono">
              {s.timestamp_utc ? new Date(s.timestamp_utc).toLocaleString() : ''}
            </div>
          </div>
        </div>
      ))}

      {(toolCalls as ToolCall[]).length > 0 && (
        <details className="mt-2">
          <summary className="text-xs text-slate-500 cursor-pointer hover:text-slate-700">
            {(toolCalls as ToolCall[]).length} tool calls (click to expand)
          </summary>
          <div className="mt-2 space-y-1">
            {(toolCalls as ToolCall[]).map((tc, i) => (
              <div key={i} className="text-[10px] font-mono text-slate-500 bg-slate-50 px-2 py-1 rounded">
                {tc.tool} {tc.duration_ms != null ? `(${tc.duration_ms}ms)` : ''}
              </div>
            ))}
          </div>
        </details>
      )}
    </div>
  )
}
