// Generated by GitHub Copilot
import { useState } from 'react'
import type { PendingGate, DecisionForm } from '../types'
import { submitDecision } from '../api'

const GATE_CHOICES: Record<string, { value: string; label: string; colour: string }[]> = {
  'HITL-1': [
    { value: 'wait',         label: '⏳ Wait for file',      colour: 'bg-slate-100 text-slate-700 hover:bg-slate-200' },
    { value: 'abort',        label: '✕ Abort today\'s run',  colour: 'bg-red-100 text-red-700 hover:bg-red-200' },
  ],
  'HITL-schema': [
    { value: 'retry',        label: '↺ Fix & Retry',          colour: 'bg-blue-100 text-blue-700 hover:bg-blue-200' },
    { value: 'override',     label: '⚡ Override Accept',      colour: 'bg-amber-100 text-amber-700 hover:bg-amber-200' },
    { value: 'abort',        label: '✕ Abort',                colour: 'bg-red-100 text-red-700 hover:bg-red-200' },
  ],
  'HITL-2': [
    { value: 'approve_all',    label: '✓ Approve All',         colour: 'bg-green-100 text-green-700 hover:bg-green-200' },
    { value: 'approve_subset', label: '◑ Approve Subset',      colour: 'bg-blue-100 text-blue-700 hover:bg-blue-200' },
    { value: 'reject',         label: '✕ Reject',              colour: 'bg-red-100 text-red-700 hover:bg-red-200' },
  ],
  'HITL-3': [
    { value: 'confirm',      label: '✓ Confirm',              colour: 'bg-green-100 text-green-700 hover:bg-green-200' },
    { value: 'flag_manual',  label: '⚑ Flag for Manual Fix',  colour: 'bg-amber-100 text-amber-700 hover:bg-amber-200' },
    { value: 'rerun',        label: '↺ Request Rerun',        colour: 'bg-slate-100 text-slate-700 hover:bg-slate-200' },
  ],
  'HITL-4': [
    { value: 'approve',      label: '✓ Approve & Close SR',   colour: 'bg-green-100 text-green-700 hover:bg-green-200' },
    { value: 'edit',         label: '✏ Edit Details',         colour: 'bg-blue-100 text-blue-700 hover:bg-blue-200' },
    { value: 'hold',         label: '⏸ Keep Open',            colour: 'bg-amber-100 text-amber-700 hover:bg-amber-200' },
  ],
}

const GATE_DESCRIPTIONS: Record<string, string> = {
  'HITL-1':      'No DVA file intake record found. Choose how to proceed.',
  'HITL-schema': 'The DVA file has schema issues. Review and decide.',
  'HITL-2':      'Review the planned device moves. Approve to execute in SOTI.',
  'HITL-3':      'Reconciliation complete. Validate the results below.',
  'HITL-4':      'Review the auto-drafted SR notes. Approve to close the ticket.',
}

function gateChoices(gate: string) {
  if (gate.startsWith('HITL-Error')) return [
    { value: 'skip',  label: '→ Skip device',     colour: 'bg-slate-100 text-slate-700 hover:bg-slate-200' },
    { value: 'retry', label: '↺ Retry',            colour: 'bg-blue-100 text-blue-700 hover:bg-blue-200' },
    { value: 'abort', label: '✕ Abort run',        colour: 'bg-red-100 text-red-700 hover:bg-red-200' },
  ]
  return GATE_CHOICES[gate] ?? [
    { value: 'approve', label: '✓ Approve', colour: 'bg-green-100 text-green-700 hover:bg-green-200' },
    { value: 'reject',  label: '✕ Reject',  colour: 'bg-red-100 text-red-700 hover:bg-red-200' },
  ]
}

interface Props {
  pending: PendingGate
  onSubmit: () => void
}

export default function HITLPanel({ pending, onSubmit }: Props) {
  const choices = gateChoices(pending.gate)
  const [selected, setSelected] = useState(choices[0].value)
  const [note, setNote] = useState('')
  const [subsetIndices, setSubsetIndices] = useState('')
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    setSubmitting(true)
    setError(null)
    try {
      const form: DecisionForm = {
        gate: pending.gate,
        decision: selected,
        note,
        subset_indices: subsetIndices,
      }
      await submitDecision(pending.run_id, form)
      onSubmit()
    } catch (err) {
      setError(String(err))
    } finally {
      setSubmitting(false)
    }
  }

  const desc = GATE_DESCRIPTIONS[pending.gate] ?? `Gate: ${pending.gate}`

  return (
    <form onSubmit={handleSubmit} aria-label={`HITL decision for ${pending.gate}`}>
      <p className="text-sm text-slate-600 mb-4">{desc}</p>

      {/* Decision buttons */}
      <div className="flex flex-wrap gap-2 mb-4">
        {choices.map(c => (
          <button
            key={c.value}
            type="button"
            onClick={() => setSelected(c.value)}
            className={`px-4 py-2 rounded-lg text-sm font-semibold border-2 transition-all ${c.colour} ${selected === c.value ? 'ring-2 ring-offset-1 ring-slate-400 border-slate-400' : 'border-transparent'}`}
            aria-pressed={selected === c.value}
          >
            {c.label}
          </button>
        ))}
      </div>

      {/* Subset indices input */}
      {selected === 'approve_subset' && (
        <div className="mb-4">
          <label htmlFor="subset-input" className="block text-sm font-medium text-slate-700 mb-1">
            Device indices to approve <span className="text-slate-400 font-normal">(comma-separated, 0-based row numbers from the table above)</span>
          </label>
          <input
            id="subset-input"
            type="text"
            placeholder="e.g. 0,1,3,5"
            value={subsetIndices}
            onChange={e => setSubsetIndices(e.target.value)}
            className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:ring-2 focus:ring-blue-400 focus:border-blue-400"
          />
        </div>
      )}

      {/* Note */}
      <div className="mb-4">
        <label htmlFor="note-input" className="block text-sm font-medium text-slate-700 mb-1">
          Note <span className="text-slate-400 font-normal">(optional — saved to audit trail)</span>
        </label>
        <textarea
          id="note-input"
          rows={2}
          value={note}
          onChange={e => setNote(e.target.value)}
          placeholder="Add a note for the audit trail…"
          className="w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:ring-2 focus:ring-blue-400 focus:border-blue-400 resize-none"
        />
      </div>

      {error && (
        <p role="alert" className="text-red-600 text-sm bg-red-50 rounded-lg px-3 py-2 mb-3">{error}</p>
      )}

      <button
        type="submit"
        disabled={submitting}
        className="w-full bg-slate-800 hover:bg-slate-700 disabled:bg-slate-400 text-white font-semibold py-2.5 rounded-lg text-sm transition-colors"
      >
        {submitting ? 'Submitting…' : `Submit: ${choices.find(c => c.value === selected)?.label ?? selected}`}
      </button>
    </form>
  )
}
