// Generated by GitHub Copilot
import { useState } from 'react'
import { parseNLEdit } from '../api'
import type { NLEditResult } from '../types'

interface MoveRow {
  index?: number
  device?: string
  bus?: string
  target?: string
  [k: string]: unknown
}

interface Props {
  runId: string
  moves: MoveRow[]
  /** Called when the operator chooses to apply the proposal as a subset
   *  selection: receives the comma-separated indices to APPROVE (the rest). */
  onApplySubset: (indicesCsv: string) => void
}

/**
 * Natural-language edit accelerator for HITL-2. The reviewer types free text;
 * the LLM proposes structured exclude/retarget edits. Nothing is auto-applied —
 * the operator explicitly clicks to turn excludes into a subset approval.
 */
export default function NLEditBox({ runId, moves, onApplySubset }: Props) {
  const [text, setText] = useState('')
  const [result, setResult] = useState<NLEditResult | null>(null)
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const preview = async () => {
    if (!text.trim() || busy) return
    setBusy(true); setError(null)
    try {
      setResult(await parseNLEdit(runId, text))
    } catch (e) {
      setError(String(e))
    } finally {
      setBusy(false)
    }
  }

  const excluded = result?.edits.filter(e => e.action === 'exclude') ?? []

  const applyExcludesAsSubset = () => {
    const excludedDevices = new Set(excluded.map(e => e.device.toLowerCase()))
    const excludedBuses = new Set(excluded.map(e => e.bus))
    const keepIndices = moves
      .filter(m =>
        !excludedDevices.has(String(m.device ?? '').toLowerCase()) &&
        !excludedBuses.has(String(m.bus ?? '')))
      .map(m => m.index)
      .filter((i): i is number => typeof i === 'number')
    onApplySubset(keepIndices.join(','))
  }

  return (
    <div className="rounded-lg border border-purple-200 bg-purple-50 p-3 mb-4">
      <h4 className="text-xs font-semibold text-purple-700 uppercase tracking-wide mb-2">
        🤖 Natural-language edits <span className="font-normal text-purple-400">(proposed, not applied)</span>
      </h4>
      <div className="flex gap-2">
        <textarea
          rows={2}
          value={text}
          onChange={e => setText(e.target.value)}
          placeholder="e.g. exclude bus 1234; move 5678 to LTM"
          className="flex-1 rounded-lg border border-purple-200 px-3 py-2 text-sm focus:ring-2 focus:ring-purple-400 focus:border-purple-400 resize-none bg-white"
        />
        <button
          type="button"
          onClick={preview}
          disabled={busy || !text.trim()}
          className="bg-purple-600 hover:bg-purple-700 disabled:bg-purple-300 text-white font-semibold px-4 rounded-lg text-sm transition-colors whitespace-nowrap"
        >
          {busy ? '…' : 'Preview'}
        </button>
      </div>

      {error && (
        <p role="alert" className="text-red-600 text-xs bg-red-50 rounded-lg px-3 py-2 mt-2">{error}</p>
      )}

      {result && (
        <div className="mt-3 text-sm">
          <p className="text-purple-800 mb-2">{result.summary}</p>

          {result.edits.length > 0 && (
            <div className="space-y-1 mb-2">
              {result.edits.map((e, i) => (
                <div key={i} className="flex items-center gap-2 text-xs bg-white rounded px-2 py-1 border border-purple-100">
                  <span className={`px-1.5 py-0.5 rounded font-semibold ${e.action === 'exclude' ? 'bg-red-100 text-red-700' : 'bg-blue-100 text-blue-700'}`}>
                    {e.action}
                  </span>
                  <span className="font-mono text-slate-700">{e.device || e.bus}</span>
                  {e.action === 'retarget' && (
                    <span className="text-slate-500">→ {e.target_folder}</span>
                  )}
                  {e.reason && <span className="text-slate-400 italic ml-auto truncate">{e.reason}</span>}
                </div>
              ))}
            </div>
          )}

          {result.unmatched.length > 0 && (
            <div className="text-xs text-amber-700 bg-amber-50 rounded px-2 py-1 mb-2">
              ⚠ Couldn't map: {result.unmatched.join(' · ')}
            </div>
          )}

          {excluded.length > 0 && (
            <button
              type="button"
              onClick={applyExcludesAsSubset}
              className="text-xs bg-purple-600 hover:bg-purple-700 text-white font-semibold px-3 py-1.5 rounded-lg transition-colors"
            >
              Approve the rest as subset (drop {excluded.length} excluded)
            </button>
          )}
        </div>
      )}
    </div>
  )
}
