// Generated by GitHub Copilot
import { useState } from 'react'
import { askQuestion } from '../api'

interface Turn {
  role: 'user' | 'agent'
  text: string
}

const SUGGESTIONS = [
  'How many devices go to LTM?',
  'What failed in reconciliation?',
  'What is the current status?',
]

/**
 * Conversational Q&A over a single run's data. Calls POST /api/runs/{id}/ask.
 * The agent answers strictly from run context — it never changes state.
 */
export default function QAChat({ runId }: { runId: string }) {
  const [turns, setTurns] = useState<Turn[]>([])
  const [question, setQuestion] = useState('')
  const [busy, setBusy] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const ask = async (q: string) => {
    const text = q.trim()
    if (!text || busy) return
    setError(null)
    setBusy(true)
    setTurns(t => [...t, { role: 'user', text }])
    setQuestion('')
    try {
      const answer = await askQuestion(runId, text)
      setTurns(t => [...t, { role: 'agent', text: answer }])
    } catch (e) {
      setError(String(e))
    } finally {
      setBusy(false)
    }
  }

  return (
    <div>
      <p className="text-sm text-slate-600 mb-3">
        Ask about this run — planned moves, target folders, current SOTI locations,
        failures, or status. Answers come from this run's data only.
      </p>

      {turns.length > 0 && (
        <div className="space-y-2 mb-3 max-h-72 overflow-auto rounded-lg border border-slate-200 p-3 bg-slate-50">
          {turns.map((t, i) => (
            <div
              key={i}
              className={`text-sm rounded-lg px-3 py-2 ${
                t.role === 'user'
                  ? 'bg-blue-100 text-blue-900 ml-8'
                  : 'bg-white border border-slate-200 text-slate-700 mr-8'
              }`}
            >
              <span className="block text-[10px] uppercase tracking-wide opacity-60 mb-0.5">
                {t.role === 'user' ? 'You' : '🤖 Assistant'}
              </span>
              <span className="whitespace-pre-wrap">{t.text}</span>
            </div>
          ))}
          {busy && <div className="text-xs text-slate-400 italic mr-8">🤖 thinking…</div>}
        </div>
      )}

      {turns.length === 0 && (
        <div className="flex flex-wrap gap-2 mb-3">
          {SUGGESTIONS.map(s => (
            <button
              key={s}
              type="button"
              onClick={() => ask(s)}
              disabled={busy}
              className="text-xs bg-slate-100 hover:bg-slate-200 text-slate-600 px-2.5 py-1 rounded-full transition-colors disabled:opacity-50"
            >
              {s}
            </button>
          ))}
        </div>
      )}

      <form
        onSubmit={e => { e.preventDefault(); ask(question) }}
        className="flex gap-2"
      >
        <input
          type="text"
          value={question}
          onChange={e => setQuestion(e.target.value)}
          placeholder="e.g. why isn't bus 1234 moving?"
          disabled={busy}
          className="flex-1 rounded-lg border border-slate-300 px-3 py-2 text-sm focus:ring-2 focus:ring-blue-400 focus:border-blue-400 disabled:bg-slate-100"
        />
        <button
          type="submit"
          disabled={busy || !question.trim()}
          className="bg-slate-800 hover:bg-slate-700 disabled:bg-slate-400 text-white font-semibold px-4 py-2 rounded-lg text-sm transition-colors"
        >
          Ask
        </button>
      </form>

      {error && (
        <p role="alert" className="text-red-600 text-xs bg-red-50 rounded-lg px-3 py-2 mt-2">
          {error}
        </p>
      )}
    </div>
  )
}
