// Generated by GitHub Copilot
import { useState, useEffect } from 'react'
import type { RunDoc, PendingGate, WorkbookTabs } from '../types'
import { PIPELINE_STAGES } from '../types'
import { fetchPending, fetchWorkbook } from '../api'
import StateBadge from './StateBadge'
import HITLPanel from './HITLPanel'
import WorkbookViewer from './WorkbookViewer'
import AuditTail from './AuditTail'
import QAChat from './QAChat'

// ── Helpers ────────────────────────────────────────────────────────────────

function elapsed(from: string): string {
  const ms = Date.now() - new Date(from).getTime()
  if (ms < 60_000) return `${Math.round(ms / 1000)}s ago`
  if (ms < 3_600_000) return `${Math.round(ms / 60_000)}m ago`
  return `${Math.round(ms / 3_600_000)}h ago`
}

// ── Stage Timeline ─────────────────────────────────────────────────────────

function StageTimeline({ run }: { run: RunDoc }) {
  const stateOrder = PIPELINE_STAGES.map(s => s.key)
  const currentIdx = stateOrder.indexOf(run.state as never)

  return (
    <div className="overflow-x-auto">
      <div className="flex items-center gap-0 min-w-max py-3 px-1">
        {PIPELINE_STAGES.map((stage, idx) => {
          const isDone = currentIdx > idx
          const isActive = run.state === stage.key
          const isFailed = ['ABORTED', 'FAILED'].includes(run.state) && currentIdx === idx
          const isPending = run.state.startsWith('AWAITING') && isActive

          let circleClass = 'bg-slate-200 text-slate-400 border-2 border-slate-200'
          if (isFailed) circleClass = 'bg-red-500 text-white border-2 border-red-500'
          else if (isDone) circleClass = 'bg-green-500 text-white border-2 border-green-500'
          else if (isPending) circleClass = 'bg-amber-400 text-white border-2 border-amber-400 animate-pulse'
          else if (isActive) circleClass = 'bg-blue-500 text-white border-2 border-blue-500'

          return (
            <div key={stage.key} className="flex items-center">
              <div className="flex flex-col items-center">
                <div className={`w-8 h-8 rounded-full flex items-center justify-center text-xs font-bold ${circleClass}`}>
                  {isDone ? '✓' : isFailed ? '✕' : idx + 1}
                </div>
                <span className={`text-[10px] mt-1 text-center leading-tight max-w-[72px] ${isActive ? 'font-semibold text-slate-700' : 'text-slate-400'}`}>
                  {stage.label}
                </span>
              </div>
              {idx < PIPELINE_STAGES.length - 1 && (
                <div className={`h-0.5 w-8 mx-0.5 mb-4 ${isDone ? 'bg-green-400' : 'bg-slate-200'}`} />
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}

// ── Move Table ─────────────────────────────────────────────────────────────

function MoveTable({ moves, title }: { moves: Record<string, unknown>[]; title: string }) {
  if (!moves.length) return null
  return (
    <div>
      <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">{title} ({moves.length})</h4>
      <div className="overflow-auto max-h-56 rounded-lg border border-slate-200">
        <table className="w-full text-xs">
          <thead className="bg-slate-50 sticky top-0">
            <tr>
              {['Bus #', 'Device', 'Current Folder', 'Target Folder', 'Status', 'Reason'].map(h => (
                <th key={h} className="text-left px-3 py-2 font-semibold text-slate-600 whitespace-nowrap">{h}</th>
              ))}
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {moves.map((m, i) => {
              const target = (m.target_folder as string) || ''
              const isLTM = target.toUpperCase().includes('LTM')
              return (
                <tr key={i} className="hover:bg-slate-50">
                  <td className="px-3 py-2 font-mono">{(m.bus_number as string) || '—'}</td>
                  <td className="px-3 py-2 font-mono text-slate-600">{(m.current_device as string) || '—'}</td>
                  <td className="px-3 py-2 text-slate-500">{(m.current_soti_folder as string) || '—'}</td>
                  <td className="px-3 py-2">
                    <span className={`inline-flex px-2 py-0.5 rounded-full text-[10px] font-semibold ${isLTM ? 'bg-orange-100 text-orange-700' : 'bg-blue-100 text-blue-700'}`}>
                      {target || '—'}
                    </span>
                  </td>
                  <td className="px-3 py-2">
                    {(m.stale_ltm_tag as boolean) && (
                      <span className="text-[10px] bg-yellow-100 text-yellow-700 px-1.5 py-0.5 rounded font-medium">⚠ Stale LTM</span>
                    )}
                  </td>
                  <td className="px-3 py-2 text-slate-400">{(m.reason as string) || ''}</td>
                </tr>
              )
            })}
          </tbody>
        </table>
      </div>
    </div>
  )
}

// ── Recon Table ────────────────────────────────────────────────────────────

function ReconSection({ payload }: { payload: PendingGate['payload'] }) {
  const recon = payload.recon_result as { moved?: unknown[]; unmoved?: unknown[]; unidentified?: unknown[]; summary_text?: string } | undefined
  if (!recon) return null
  return (
    <div className="space-y-3">
      {recon.summary_text && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg px-4 py-3 text-sm text-blue-800">
          🤖 <span className="font-medium">AI Summary:</span> {recon.summary_text}
        </div>
      )}
      <div className="grid grid-cols-3 gap-3 text-center">
        <div className="bg-green-50 rounded-lg px-3 py-3">
          <div className="text-2xl font-bold text-green-700">{recon.moved?.length ?? 0}</div>
          <div className="text-xs text-green-600">Moved</div>
        </div>
        <div className="bg-red-50 rounded-lg px-3 py-3">
          <div className="text-2xl font-bold text-red-700">{recon.unmoved?.length ?? 0}</div>
          <div className="text-xs text-red-600">Failed</div>
        </div>
        <div className="bg-amber-50 rounded-lg px-3 py-3">
          <div className="text-2xl font-bold text-amber-700">{recon.unidentified?.length ?? 0}</div>
          <div className="text-xs text-amber-600">Unidentified</div>
        </div>
      </div>
      {(recon.unmoved?.length ?? 0) + (recon.unidentified?.length ?? 0) > 0 && (
        <div className="bg-red-50 border border-red-200 rounded-lg px-4 py-3">
          <h4 className="text-xs font-semibold text-red-700 uppercase tracking-wide mb-2">Exceptions requiring attention</h4>
          <div className="space-y-1">
            {([...(recon.unmoved ?? []), ...(recon.unidentified ?? [])] as Record<string, unknown>[]).map((d, i) => (
              <div key={i} className="flex gap-2 text-xs text-red-700">
                <span className="font-mono">{d.device as string}</span>
                <span className="text-red-400">—</span>
                <span>{(d.reason as string) || 'unknown reason'}</span>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  )
}

// ── LLM Insights Panel ────────────────────────────────────────────────────

const INSIGHT_STEPS: { stepKey: string; field: string; label: string; colour: string }[] = [
  { stepKey: 'stage2_parse',        field: 'summary',              label: 'Parse Summary',          colour: 'blue'   },
  { stepKey: 'stage3_approval',     field: 'post_decision_summary', label: 'Pre-Move Approval',      colour: 'indigo' },
  { stepKey: 'stage5_reconcile',    field: 'summary',              label: 'Reconciliation Summary',  colour: 'teal'   },
  { stepKey: 'stage5_reconcile',    field: 'exception_triage',     label: 'Exception Triage',        colour: 'rose'   },
  { stepKey: 'stage6_post_hitl3',   field: 'post_decision_summary', label: 'Post-Validation',        colour: 'violet' },
  { stepKey: 'stage6_validation',   field: 'run_summary',          label: 'Final Run Summary',       colour: 'green'  },
]

const COLOUR_CLASSES: Record<string, string> = {
  blue:   'bg-blue-50   border-blue-200   text-blue-800',
  indigo: 'bg-indigo-50 border-indigo-200 text-indigo-800',
  teal:   'bg-teal-50   border-teal-200   text-teal-800',
  rose:   'bg-rose-50   border-rose-200   text-rose-800',
  violet: 'bg-violet-50 border-violet-200 text-violet-800',
  green:  'bg-green-50  border-green-200  text-green-800',
}

/** Render markdown bold (**text**) as <strong> */
function renderMarkdown(text: string) {
  const parts = text.split(/(\*\*[^*]+\*\*)/)
  return parts.map((p, i) =>
    p.startsWith('**') && p.endsWith('**')
      ? <strong key={i}>{p.slice(2, -2)}</strong>
      : p
  )
}

function LLMInsights({ steps }: { steps: RunDoc['steps'] }) {
  const insights: { label: string; text: string; colour: string }[] = []

  for (const cfg of INSIGHT_STEPS) {
    const step = steps.find(s => s.step === cfg.stepKey)
    const text = step?.output?.[cfg.field] as string | undefined
    if (text && text.trim() && !text.startsWith('[MOCK]')) {
      insights.push({ label: cfg.label, text, colour: cfg.colour })
    }
  }

  if (insights.length === 0) return (
    <p className="text-sm text-slate-400 italic">No AI write-ups generated yet — they appear as each stage completes.</p>
  )

  return (
    <div className="space-y-3">
      {insights.map((ins, i) => (
        <div key={i} className={`rounded-lg border px-4 py-3 ${COLOUR_CLASSES[ins.colour]}`}>
          <div className="flex items-center gap-2 mb-1.5">
            <span className="text-base">🤖</span>
            <span className="text-xs font-bold uppercase tracking-wide opacity-70">{ins.label}</span>
          </div>
          <p className="text-sm leading-relaxed">{renderMarkdown(ins.text)}</p>
        </div>
      ))}
    </div>
  )
}

// ── Section Panel (collapsible within the card) ────────────────────────────

function Section({ title, badge, defaultOpen = false, children }: {
  title: string; badge?: string; defaultOpen?: boolean; children: React.ReactNode
}) {
  const [open, setOpen] = useState(defaultOpen)
  return (
    <div className="border border-slate-200 rounded-xl overflow-hidden">
      <button
        onClick={() => setOpen(o => !o)}
        className="w-full flex items-center justify-between px-4 py-3 bg-slate-50 hover:bg-slate-100 transition-colors text-left"
        aria-expanded={open}
      >
        <span className="font-semibold text-sm text-slate-700">{title}</span>
        <div className="flex items-center gap-2">
          {badge && <span className="text-xs bg-slate-200 text-slate-600 px-2 py-0.5 rounded-full">{badge}</span>}
          <span className="text-slate-400 text-xs">{open ? '▲' : '▼'}</span>
        </div>
      </button>
      {open && <div className="px-4 py-4 bg-white">{children}</div>}
    </div>
  )
}

// ── Main RunCard ───────────────────────────────────────────────────────────

interface Props {
  run: RunDoc
  expanded: boolean
  onToggle: () => void
  onDecisionSubmit: () => void
}

export default function RunCard({ run, expanded, onToggle, onDecisionSubmit }: Props) {
  const [pending, setPending] = useState<PendingGate | null>(null)
  const [workbook, setWorkbook] = useState<WorkbookTabs | null>(null)
  const [loadingDetails, setLoadingDetails] = useState(false)

  const isAwaiting = run.state.startsWith('AWAITING') || run.state === 'ON_HOLD'
  const isCompleted = run.state === 'COMPLETED'
  const isFailed = ['ABORTED', 'FAILED'].includes(run.state)

  // Load details when expanded
  useEffect(() => {
    if (!expanded) return
    let cancelled = false
    async function load() {
      setLoadingDetails(true)
      try {
        const [p, wb] = await Promise.all([
          fetchPending(run.run_id),
          fetchWorkbook(run.run_id),
        ])
        if (cancelled) return
        setPending('gate' in p ? p as PendingGate : null)
        setWorkbook(Object.keys(wb).length > 0 ? wb : null)
      } finally {
        if (!cancelled) setLoadingDetails(false)
      }
    }
    load()
    // Re-poll pending gate every 5s while expanded
    const id = setInterval(async () => {
      const p = await fetchPending(run.run_id)
      if (!cancelled) setPending('gate' in p ? p as PendingGate : null)
    }, 5_000)
    return () => { cancelled = true; clearInterval(id) }
  }, [expanded, run.run_id])

  // Extract move list from steps
  const planStep = run.steps.find(s => s.step === 'stage2_parse')
  const intendedMoves = (planStep?.output as Record<string, unknown>)?.intended_moves as Record<string, unknown>[] | undefined

  // Approvals
  const approvals = run.approvals ?? []

  // Card header colour
  const headerBorder = isAwaiting ? 'border-l-amber-400' : isCompleted ? 'border-l-green-500' : isFailed ? 'border-l-red-500' : 'border-l-blue-400'

  return (
    <div className={`bg-white rounded-2xl shadow-sm border border-slate-200 border-l-4 ${headerBorder} overflow-hidden transition-all`}>
      {/* ── Collapsed header ── */}
      <button
        onClick={onToggle}
        className="w-full text-left px-5 py-4 hover:bg-slate-50 transition-colors"
        aria-expanded={expanded}
      >
        <div className="flex items-center justify-between gap-4 flex-wrap">
          <div className="flex items-center gap-3">
            <span className="font-bold text-slate-800 font-mono text-sm">{run.run_id}</span>
            <StateBadge state={run.state} />
            {isAwaiting && (
              <span className="text-xs bg-amber-100 text-amber-700 px-2 py-0.5 rounded-full font-medium animate-pulse">
                ⏳ Awaiting L2
              </span>
            )}
          </div>
          <div className="flex items-center gap-4 text-xs text-slate-400">
            <span>{run.agency}</span>
            <span>{run.steps.length} steps</span>
            <span>{approvals.length} approvals</span>
            <span>{elapsed(run.started_utc)}</span>
            <span className="text-slate-300">{expanded ? '▲ collapse' : '▼ expand'}</span>
          </div>
        </div>

        {/* Mini pipeline bar — always visible */}
        {!expanded && (
          <div className="mt-3">
            <StageTimeline run={run} />
          </div>
        )}
      </button>

      {/* ── Expanded body ── */}
      {expanded && (
        <div className="border-t border-slate-100 px-5 py-5 space-y-4">
          {/* Full pipeline timeline */}
          <div className="bg-slate-50 rounded-xl px-4 py-3">
            <h3 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Pipeline Progress</h3>
            <StageTimeline run={run} />
            <div className="flex gap-6 mt-2 text-xs text-slate-500">
              <span>Run ID: <strong className="text-slate-700 font-mono">{run.run_id}</strong></span>
              <span>Agency: <strong className="text-slate-700">{run.agency}</strong></span>
              <span>Started: <strong className="text-slate-700">{new Date(run.started_utc).toLocaleString()}</strong></span>
              {run.dva_path && <span>DVA: <strong className="text-slate-700 truncate max-w-xs">{run.dva_path.split(/[\\/]/).pop()}</strong></span>}
            </div>
          </div>

          {loadingDetails && (
            <div className="text-slate-400 text-sm text-center py-4">Loading details…</div>
          )}

          {/* ── HITL Gate — always at top when pending ── */}
          {pending && (
            <div className="border-2 border-amber-300 rounded-xl overflow-hidden">
              <div className="bg-amber-50 px-4 py-2 flex items-center gap-2">
                <span className="text-amber-600 font-bold text-sm">⏳ Action Required — {pending.gate}</span>
              </div>
              <div className="px-4 py-4 bg-white">
                {/* Show mock preview if available */}
                {pending.payload.mock_result && (
                  <div className="mb-4 bg-blue-50 border border-blue-200 rounded-lg px-4 py-3 text-sm text-blue-700">
                    🔍 <strong>MOCK Preview:</strong> {(pending.payload.mock_result as { moved?: unknown[] }).moved?.length ?? 0} moves simulated
                  </div>
                )}

                {/* Move list for HITL-2 */}
                {pending.gate === 'HITL-2' && pending.payload.intended_moves && (
                  <div className="mb-4">
                    <MoveTable
                      moves={pending.payload.intended_moves as Record<string, unknown>[]}
                      title="Planned Moves"
                    />
                  </div>
                )}

                {/* Recon result for HITL-3 */}
                {pending.gate === 'HITL-3' && (
                  <div className="mb-4">
                    <ReconSection payload={pending.payload} />
                  </div>
                )}

                {/* SR notes for HITL-4 */}
                {pending.gate === 'HITL-4' && pending.payload.sr_notes && (
                  <div className="mb-4 bg-slate-50 border border-slate-200 rounded-lg px-4 py-3">
                    <h4 className="text-xs font-semibold text-slate-500 uppercase tracking-wide mb-2">Draft SR Notes</h4>
                    <pre className="text-xs text-slate-700 whitespace-pre-wrap font-sans">{pending.payload.sr_notes as string}</pre>
                  </div>
                )}

                {/* LLM summary if available */}
                {(pending.payload.post_hitl2_summary || pending.payload.post_hitl3_summary || pending.payload.post_hitl4_summary) && (
                  <div className="mb-4 bg-purple-50 border border-purple-200 rounded-lg px-4 py-3 text-sm text-purple-800">
                    🤖 <strong>AI Context:</strong> {(pending.payload.post_hitl2_summary || pending.payload.post_hitl3_summary || pending.payload.post_hitl4_summary) as string}
                  </div>
                )}

                <HITLPanel
                  pending={pending}
                  onSubmit={() => { onDecisionSubmit(); setPending(null) }}
                />
              </div>
            </div>
          )}

          {/* ── Move Plan ── */}
          {intendedMoves && intendedMoves.length > 0 && (
            <Section title="Planned Moves" badge={`${intendedMoves.length} devices`} defaultOpen={run.state === 'AWAITING_PRE_APPROVAL'}>
              <MoveTable moves={intendedMoves} title="All Planned Moves" />
            </Section>
          )}

          {/* ── Workbook ── */}
          {workbook && (
            <Section title="Output Workbook (5 tabs)" badge="Excel" defaultOpen={run.state === 'AWAITING_VALIDATION' || isCompleted}>
              <WorkbookViewer tabs={workbook} />
            </Section>
          )}

          {/* ── AI Insights ── */}
          <Section title="AI Insights" badge="🤖 LLM Write-ups" defaultOpen={true}>
            <LLMInsights steps={run.steps} />
          </Section>

          {/* ── Approvals ── */}
          {approvals.length > 0 && (
            <Section title="HITL Decisions" badge={`${approvals.length}`} defaultOpen={false}>
              <div className="space-y-2">
                {approvals.map((a, i) => (
                  <div key={i} className="flex items-start gap-3 text-sm">
                    <span className="text-xs bg-slate-100 text-slate-600 px-2 py-1 rounded font-mono whitespace-nowrap">{a.gate}</span>
                    <span className={`text-xs px-2 py-1 rounded font-semibold ${a.decision.includes('approve') || a.decision === 'confirm' ? 'bg-green-100 text-green-700' : a.decision === 'reject' ? 'bg-red-100 text-red-700' : 'bg-slate-100 text-slate-600'}`}>
                      {a.decision}
                    </span>
                    {a.note && <span className="text-xs text-slate-500 italic">"{a.note}"</span>}
                    <span className="text-xs text-slate-400 ml-auto whitespace-nowrap">{a.timestamp_utc ? new Date(a.timestamp_utc).toLocaleTimeString() : ''}</span>
                  </div>
                ))}
              </div>
            </Section>
          )}

          {/* ── Ask the Assistant (Q&A) ── */}
          <Section title="Ask the Assistant" badge="🤖 AI" defaultOpen={isAwaiting}>
            <QAChat runId={run.run_id} />
          </Section>

          {/* ── Audit Trail ── */}
          <Section title="Audit Trail" badge={`${run.steps.length} steps`} defaultOpen={false}>
            <AuditTail steps={run.steps} toolCalls={run.tool_calls ?? []} />
          </Section>
        </div>
      )}
    </div>
  )
}
