// Generated by GitHub Copilot

const STATE_STYLES: Record<string, string> = {
  RECEIVED:               'bg-slate-100 text-slate-600',
  PARSING:                'bg-blue-100 text-blue-700',
  PLANNED:                'bg-indigo-100 text-indigo-700',
  AWAITING_PRE_APPROVAL:  'bg-amber-100 text-amber-700',
  MOVING:                 'bg-purple-100 text-purple-700',
  RECONCILING:            'bg-cyan-100 text-cyan-700',
  AWAITING_VALIDATION:    'bg-amber-100 text-amber-700',
  DRAFTING_SR:            'bg-violet-100 text-violet-700',
  AWAITING_SR_APPROVAL:   'bg-amber-100 text-amber-700',
  EXECUTING:              'bg-purple-100 text-purple-700',
  COMPLETED:              'bg-green-100 text-green-700',
  ABORTED:                'bg-red-100 text-red-700',
  FAILED:                 'bg-red-100 text-red-700',
  ON_HOLD:                'bg-yellow-100 text-yellow-700',
}

const STATE_ICONS: Record<string, string> = {
  COMPLETED: '\u2713', ABORTED: '\u2715', FAILED: '\u2715',
  ON_HOLD: '\u23f8', MOVING: '\u26a1', RECONCILING: '\ud83d\udd0d',
  PARSING: '\ud83d\udcc4', DRAFTING_SR: '\ud83d\udcdd',
  AWAITING_PRE_APPROVAL: '\u23f3', AWAITING_VALIDATION: '\u23f3',
  AWAITING_SR_APPROVAL: '\u23f3',
}

export default function StateBadge({ state }: { state: string }) {
  const style = STATE_STYLES[state] ?? 'bg-slate-100 text-slate-500'
  const icon = STATE_ICONS[state] ?? '\u25cf'
  return (
    <span className={`inline-flex items-center gap-1 px-2.5 py-0.5 rounded-full text-xs font-semibold ${style}`}>
      <span aria-hidden="true">{icon}</span>
      {state.replace(/_/g, ' ')}
    </span>
  )
}
