// Generated by GitHub Copilot
import { useState } from 'react'
import type { WorkbookTabs } from '../types'

const TAB_COLOURS: Record<string, string> = {
  'Moved to LTM':       'bg-orange-600',
  'Failed - LTM':       'bg-red-600',
  'Moved to Production':'bg-blue-600',
  'Failed - Production':'bg-red-700',
  'Unidentified':       'bg-slate-500',
}

interface Props {
  tabs: WorkbookTabs
}

/**
 * 5-tab output workbook viewer.
 * Renders each tab as a searchable data table with row counts.
 */
export default function WorkbookViewer({ tabs }: Props) {
  const tabNames = Object.keys(tabs)
  const [active, setActive] = useState(tabNames[0] ?? '')
  const [search, setSearch] = useState('')

  if (tabNames.length === 0) {
    return <p className="text-sm text-slate-400 italic">No workbook data available.</p>
  }

  const rows = tabs[active] ?? []
  const header = rows[0] ?? []
  const data = rows.slice(1)
  const q = search.toLowerCase()
  const filtered = q ? data.filter(row => row.some(cell => cell.toLowerCase().includes(q))) : data

  const colour = TAB_COLOURS[active] ?? 'bg-slate-600'
  const isEmpty = data.length === 0

  return (
    <div>
      {/* Tab bar */}
      <div className="flex flex-wrap gap-1 mb-3" role="tablist">
        {tabNames.map(name => {
          const rowCount = (tabs[name]?.length ?? 1) - 1
          const tc = TAB_COLOURS[name] ?? 'bg-slate-500'
          return (
            <button
              key={name}
              role="tab"
              aria-selected={active === name}
              onClick={() => { setActive(name); setSearch('') }}
              className={`px-3 py-1.5 rounded-lg text-xs font-semibold text-white transition-all ${tc} ${active === name ? 'ring-2 ring-offset-1 ring-slate-400 opacity-100' : 'opacity-60 hover:opacity-80'}`}
            >
              {name} <span className="ml-1 opacity-75">({rowCount})</span>
            </button>
          )
        })}
      </div>

      {/* Search */}
      {!isEmpty && (
        <div className="mb-2">
          <input
            type="search"
            placeholder={`Search ${active}…`}
            value={search}
            onChange={e => setSearch(e.target.value)}
            className="w-full sm:w-64 text-xs border border-slate-200 rounded-lg px-3 py-1.5 focus:ring-2 focus:ring-blue-300 focus:border-blue-300"
            aria-label={`Search ${active}`}
          />
          {search && <span className="text-xs text-slate-400 ml-2">{filtered.length} result(s)</span>}
        </div>
      )}

      {/* Table */}
      {isEmpty ? (
        <div className={`text-xs text-white ${colour} rounded-lg px-4 py-3 opacity-70`}>
          No data for this tab — all devices in this category moved successfully.
        </div>
      ) : (
        <div className="overflow-auto max-h-64 rounded-lg border border-slate-200">
          <table className="w-full text-xs" aria-label={active}>
            <thead className={`${colour} sticky top-0`}>
              <tr>
                <th className="px-3 py-2 text-left text-white font-semibold opacity-70 w-8">#</th>
                {header.map((h, i) => (
                  <th key={i} className="px-3 py-2 text-left text-white font-semibold whitespace-nowrap">{h || `Col ${i + 1}`}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {filtered.map((row, ri) => (
                <tr key={ri} className="hover:bg-slate-50">
                  <td className="px-3 py-2 text-slate-300 font-mono">{ri + 1}</td>
                  {header.map((_, ci) => (
                    <td key={ci} className="px-3 py-2 font-mono text-slate-600 whitespace-nowrap">
                      {row[ci] || '—'}
                    </td>
                  ))}
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
