# Generated by GitHub Copilot
"""Basic stdio smoke test for the SOTI MCP server.

This script verifies that:
1. The MCP server process starts.
2. MCP initialize handshake succeeds.
3. tools/list returns at least one tool.
"""

import json
import queue
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any


class StdioMcpClient:
    """Tiny JSON-RPC-over-stdio client using newline-delimited JSON."""

    def __init__(self, process: subprocess.Popen[bytes]) -> None:
        """Store process and start reader threads for stdout/stderr."""
        self.process = process
        self._messages: queue.Queue[dict[str, Any]] = queue.Queue()
        self._stderr_lines: queue.Queue[str] = queue.Queue()
        self._reader_thread = threading.Thread(target=self._read_stdout_loop, daemon=True)
        self._stderr_thread = threading.Thread(target=self._read_stderr_loop, daemon=True)
        self._reader_thread.start()
        self._stderr_thread.start()
        self._next_id = 1

    def _read_stderr_loop(self) -> None:
        """Continuously collect stderr lines for diagnostics."""
        while True:
            line = self.process.stderr.readline()
            if not line:
                return
            text = line.decode("utf-8", errors="replace").rstrip("\r\n")
            self._stderr_lines.put(text)

    def _read_stdout_loop(self) -> None:
        """Continuously parse MCP framed messages from stdout."""
        while True:
            message = self._read_one_message()
            if message is None:
                return
            self._messages.put(message)

    def _read_one_message(self) -> dict[str, Any] | None:
        """Read and parse a single newline-delimited JSON message."""
        while True:
            line = self.process.stdout.readline()
            if not line:
                return None

            text = line.decode("utf-8", errors="replace").strip()
            if not text:
                continue

            return json.loads(text)

    def send_request(self, method: str, params: dict[str, Any] | None = None) -> int:
        """Send a JSON-RPC request and return its numeric id."""
        req_id = self._next_id
        self._next_id += 1

        payload: dict[str, Any] = {
            "jsonrpc": "2.0",
            "id": req_id,
            "method": method,
        }
        if params is not None:
            payload["params"] = params

        self._send_payload(payload)
        return req_id

    def send_notification(self, method: str, params: dict[str, Any] | None = None) -> None:
        """Send a JSON-RPC notification (no response expected)."""
        payload: dict[str, Any] = {
            "jsonrpc": "2.0",
            "method": method,
        }
        if params is not None:
            payload["params"] = params

        self._send_payload(payload)

    def _send_payload(self, payload: dict[str, Any]) -> None:
        """Write one JSON-RPC payload as newline-delimited JSON."""
        raw = (json.dumps(payload, separators=(",", ":")) + "\n").encode("utf-8")
        self.process.stdin.write(raw)
        self.process.stdin.flush()

    def wait_for_response(self, req_id: int, timeout_seconds: float = 15.0) -> dict[str, Any]:
        """Wait for a specific response id and return the parsed payload."""
        deadline = time.time() + timeout_seconds
        skipped: list[dict[str, Any]] = []

        while time.time() < deadline:
            remaining = max(0.0, deadline - time.time())
            try:
                message = self._messages.get(timeout=remaining)
            except queue.Empty as exc:
                raise TimeoutError(f"Timed out waiting for response id {req_id}") from exc

            if message.get("id") == req_id:
                for item in skipped:
                    self._messages.put(item)
                return message

            skipped.append(message)

        raise TimeoutError(f"Timed out waiting for response id {req_id}")

    def drain_stderr(self) -> list[str]:
        """Return all collected stderr lines currently available."""
        lines: list[str] = []
        while True:
            try:
                lines.append(self._stderr_lines.get_nowait())
            except queue.Empty:
                return lines


def main() -> int:
    """Run initialize + tools/list smoke test against local server.py."""
    root = Path(__file__).resolve().parent
    server_path = root / "server.py"

    if not server_path.exists():
        print("FAIL: server.py not found in current folder")
        return 1

    process = subprocess.Popen(
        [sys.executable, str(server_path)],
        cwd=str(root),
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
    )

    assert process.stdin is not None
    assert process.stdout is not None
    assert process.stderr is not None

    client = StdioMcpClient(process)

    try:
        init_id = client.send_request(
            "initialize",
            {
                "protocolVersion": "2024-11-05",
                "capabilities": {},
                "clientInfo": {"name": "mcp-smoke-test", "version": "1.0.0"},
            },
        )
        init_response = client.wait_for_response(init_id)
        if "error" in init_response:
            print("FAIL: initialize returned error")
            print(json.dumps(init_response["error"], indent=2))
            return 1

        client.send_notification("notifications/initialized")

        tools_list_id = client.send_request("tools/list", {})
        tools_response = client.wait_for_response(tools_list_id)
        if "error" in tools_response:
            print("FAIL: tools/list returned error")
            print(json.dumps(tools_response["error"], indent=2))
            return 1

        tools = tools_response.get("result", {}).get("tools", [])
        if not isinstance(tools, list):
            print("FAIL: tools/list returned unexpected payload shape")
            print(json.dumps(tools_response, indent=2))
            return 1

        print(f"PASS: MCP server responded. tools/list returned {len(tools)} tools.")
        if tools:
            preview = [tool.get("name", "<unnamed>") for tool in tools[:5]]
            print("Sample tools:", ", ".join(preview))
        return 0

    except Exception as exc:
        print(f"FAIL: {exc}")
        return 1

    finally:
        try:
            process.terminate()
            process.wait(timeout=3)
        except Exception:
            process.kill()

        stderr_output = client.drain_stderr()
        if stderr_output:
            print("--- server stderr ---")
            for line in stderr_output[-20:]:
                print(line)


if __name__ == "__main__":
    raise SystemExit(main())
