# Generated by GitHub Copilot
"""
HITL console prompts — formatted with Rich for L2 operations review.
Set USE_MOCK_HITL=True (or pass --auto) for unattended / CI runs.
Set USE_WEB_HITL=True to route all gates through the Ops Dashboard Portal.

All prompt functions follow the same pattern:
  1. If USE_MOCK_HITL is True → log the auto-decision and return immediately.
  2. If USE_WEB_HITL is True → write pending file, open browser, poll for decision.
  3. Otherwise → render a Rich table/panel and call Prompt.ask().
"""
import json
import os
import time
import webbrowser
from typing import Literal

from rich.console import Console
from rich.panel import Panel
from rich.prompt import Prompt
from rich.table import Table

import config
from schemas.agent_outputs import ReconciliationResult
from schemas.intended_move import IntendedMove

console = Console()


def _auto(label: str, value: str) -> str:
    """Log an auto-approved HITL decision and return the value."""
    console.print(f"[dim][MOCK HITL] {label} → auto-approved: '{value}'[/dim]")
    return value


def _web_hitl(gate: str, run_id: str, payload: dict, default: str) -> str:
    """
    Web HITL bridge — write a pending file, open the portal in the browser,
    then poll until the portal writes the decision file.

    Pending file : output/hitl_pending_{run_id}_{gate}.json
    Decision file: output/hitl_decision_{run_id}_{gate}.json
    """
    os.makedirs(config.OUTPUT_DIR, exist_ok=True)
    safe_gate = gate.replace(":", "_")
    pending_path  = os.path.join(config.OUTPUT_DIR, f"hitl_pending_{run_id}_{safe_gate}.json")
    decision_path = os.path.join(config.OUTPUT_DIR, f"hitl_decision_{run_id}_{safe_gate}.json")

    # Remove any stale decision file from a previous run
    if os.path.exists(decision_path):
        os.remove(decision_path)

    # Write the pending gate so the portal can render it
    with open(pending_path, "w", encoding="utf-8") as f:
        json.dump({"run_id": run_id, "gate": gate, "payload": payload,
                   "default": default, "status": "pending"}, f, indent=2, default=str)

    portal_url = f"{config.OPS_PORTAL_URL}/runs/{run_id}"
    console.print(Panel(
        f"[bold cyan]Waiting for L2 decision in Ops Portal[/bold cyan]\n\n"
        f"Gate  : [yellow]{gate}[/yellow]\n"
        f"Run   : [yellow]{run_id}[/yellow]\n"
        f"URL   : [link={portal_url}]{portal_url}[/link]\n\n"
        f"Opening portal in browser...",
        title="[WEB HITL] Pending L2 Approval",
        border_style="cyan",
    ))
    webbrowser.open(portal_url)

    # Poll every 2 seconds for up to 30 minutes
    for _ in range(900):
        time.sleep(2)
        if os.path.exists(decision_path):
            with open(decision_path, "r", encoding="utf-8") as f:
                data = json.load(f)
            decision = data.get("decision", default)
            console.print(f"[green]Portal decision received:[/green] {decision}")
            if os.path.exists(pending_path):
                os.remove(pending_path)
            return decision

    console.print(f"[red]Timeout waiting for portal decision — using default: {default}[/red]")
    if os.path.exists(pending_path):
        os.remove(pending_path)
    return default


# ── HITL-1: Late or missing intake record (Cosmos DB) ────────────────────────

def prompt_missing_dva(intake_id: str, run_id: str = "unknown") -> Literal["wait", "abort"]:
    """
    HITL-1 gate: no READY_FOR_RUN intake record found in Cosmos DB.
    Inform L2 and ask whether to hold the run until the DVA arrives,
    or abort today's run entirely.
    """
    if config.USE_MOCK_HITL:
        return _auto("HITL-1 missing DVA", "wait")  # type: ignore[return-value]
    if config.USE_WEB_HITL:
        return _web_hitl("HITL-1", run_id, {"intake_id": intake_id}, "wait")  # type: ignore[return-value]

    console.print(Panel(
        f"[bold red]No intake record found in Cosmos DB[/bold red]\n\n"
        f"Expected ID : [yellow]{intake_id}[/yellow]\n"
        f"Status expected: READY_FOR_RUN\n\n"
        f"The DVA email from Brampton Transit may not have arrived yet, "
        f"or the Intake Function may have failed to write the record.\n\n"
        f"[bold]Options[/bold]\n"
        f"  wait  — Hold this run; retry will occur when the record appears\n"
        f"  abort — Cancel today's run and record it as ABORTED",
        title="[HITL-1] Missing DVA Intake Record",
        border_style="red",
    ))

    choice = Prompt.ask(
        "[bold]Decision[/bold]",
        choices=["wait", "abort"],
        default="wait",
    )
    return choice  # type: ignore[return-value]


# ── HITL-schema: DVA schema issues ───────────────────────────────────────────

def prompt_schema_fix(issues: list[dict], run_id: str = "unknown") -> Literal["retry", "override", "abort"]:
    """Alert L2 to DVA schema issues and ask how to proceed."""
    if config.USE_MOCK_HITL:
        return _auto("HITL-schema", "override")  # type: ignore[return-value]
    if config.USE_WEB_HITL:
        return _web_hitl("HITL-schema", run_id, {"issues": issues}, "override")  # type: ignore[return-value]

    table = Table(title="DVA Schema Issues", show_lines=True)
    table.add_column("Row", style="red", no_wrap=True)
    table.add_column("Issue")
    for issue in issues:
        table.add_row(str(issue.get("row", "?")), issue.get("issue", ""))
    console.print(table)

    choice = Prompt.ask(
        "[bold]How to proceed?[/bold]",
        choices=["retry", "override", "abort"],
        default="override",
    )
    return choice  # type: ignore[return-value]


# ── HITL-2: Pre-move approval ─────────────────────────────────────────────────

def prompt_pre_move_approval(
    moves: list[IntendedMove],
    run_id: str = "unknown",
) -> Literal["approve_all", "approve_subset", "reject"]:
    """Display the full intended-moves table and request L2 pre-approval."""
    if config.USE_MOCK_HITL:
        return _auto("HITL-2 pre-move", "approve_all")  # type: ignore[return-value]
    if config.USE_WEB_HITL:
        payload = [{"index": i, "device": m.current_device, "bus": m.bus_number,
                    "target": m.target_folder, "current_soti": m.current_soti_folder,
                    "status": m.vehicle_status, "stale": m.stale_ltm_tag} for i, m in enumerate(moves)]
        return _web_hitl("HITL-2", run_id, {"moves": payload, "count": len(moves)}, "approve_all")  # type: ignore[return-value]

    table = Table(title="Intended Device Moves", show_lines=True)
    table.add_column("#", style="dim", no_wrap=True)
    table.add_column("Bus", style="cyan")
    table.add_column("Device", style="yellow")
    table.add_column("Target Folder", style="green")
    table.add_column("Current SOTI Folder", no_wrap=False)
    table.add_column("Vehicle Status")
    table.add_column("Reason")
    for i, m in enumerate(moves):
        folder = m.current_soti_folder or "?"
        if "STALE" in folder:
            folder_display = f"[bold red]{folder}[/bold red]"
        elif folder in ("UNKNOWN", "?"):
            folder_display = f"[yellow]{folder}[/yellow]"
        else:
            folder_display = f"[green]{folder}[/green]"
        table.add_row(
            str(i), m.bus_number, m.current_device,
            m.target_folder, folder_display, m.vehicle_status, m.reason,
        )

    # MOCK dry-run preview summary (counts before any real move happens)
    to_prod = sum(1 for m in moves if "LTM" not in m.target_folder.upper())
    to_ltm  = sum(1 for m in moves if "LTM" in m.target_folder.upper())
    stale   = sum(1 for m in moves if m.stale_ltm_tag)
    unknown = sum(1 for m in moves if (m.current_soti_folder or "?") in ("UNKNOWN", "?"))
    console.print(Panel(
        f"[bold]MOCK DRY-RUN PREVIEW[/bold] — no devices have moved yet\n\n"
        f"  Devices to move to [blue]Production[/blue] : [bold]{to_prod}[/bold]\n"
        f"  Devices to move to [yellow]LTM[/yellow]        : [bold]{to_ltm}[/bold]\n"
        f"  Stale LTM-tag devices          : [bold red]{stale}[/bold red]\n"
        f"  Devices not yet found in SOTI  : [bold yellow]{unknown}[/bold yellow]\n\n"
        f"Review the table below and approve to proceed with LIVE moves.",
        title="[HITL-2] Pre-Move Approval",
        border_style="cyan",
    ))
    console.print(table)

    choice = Prompt.ask(
        "[bold]Approve?[/bold]",
        choices=["approve_all", "approve_subset", "reject"],
        default="approve_all",
    )
    return choice  # type: ignore[return-value]


def prompt_subset_selection(moves: list[IntendedMove]) -> list[int]:
    """Ask L2 to select which move indices to approve (comma-separated)."""
    if config.USE_MOCK_HITL:
        console.print("[dim][MOCK HITL] subset selection → all indices[/dim]")
        return list(range(len(moves)))

    for i, m in enumerate(moves):
        console.print(f"  [{i}] {m.current_device} → {m.target_folder}")
    raw = Prompt.ask("Enter comma-separated indices to approve (e.g. 0,1,3)")
    return [int(x.strip()) for x in raw.split(",") if x.strip().isdigit()]


# ── HITL-3: Post-move validation ──────────────────────────────────────────────

def prompt_post_move_validation(
    recon: ReconciliationResult,
    run_id: str = "unknown",
) -> Literal["confirm", "flag_manual", "rerun"]:
    """Display reconciliation result and request L2 sign-off."""
    if config.USE_MOCK_HITL:
        return _auto("HITL-3 post-move", "confirm")  # type: ignore[return-value]
    if config.USE_WEB_HITL:
        return _web_hitl("HITL-3", run_id,
                         {"moved": len(recon.moved), "unmoved": len(recon.unmoved),
                          "unidentified": len(recon.unidentified),
                          "unmoved_list": recon.unmoved, "unidentified_list": recon.unidentified,
                          "summary": recon.summary_text}, "confirm")  # type: ignore[return-value]

    panel_text = (
        f"[green]✔ Moved:[/green] {len(recon.moved)}   "
        f"[red]✗ Unmoved:[/red] {len(recon.unmoved)}   "
        f"[yellow]? Unidentified:[/yellow] {len(recon.unidentified)}\n\n"
        f"{recon.summary_text}"
    )
    console.print(Panel(panel_text, title="Reconciliation Result", border_style="blue"))

    choice = Prompt.ask(
        "[bold]Validation decision[/bold]",
        choices=["confirm", "flag_manual", "rerun"],
        default="confirm",
    )
    return choice  # type: ignore[return-value]


# ── HITL-4: SR closure ────────────────────────────────────────────────────────

def prompt_sr_closure(sr_draft: str, run_id: str = "unknown") -> Literal["approve", "edit", "hold"]:
    """Display drafted SR notes and request L2 closure approval."""
    if config.USE_MOCK_HITL:
        return _auto("HITL-4 SR closure", "approve")  # type: ignore[return-value]
    if config.USE_WEB_HITL:
        return _web_hitl("HITL-4", run_id, {"sr_notes": sr_draft}, "approve")  # type: ignore[return-value]

    console.print(Panel(sr_draft, title="Draft SR Notes", border_style="magenta"))

    choice = Prompt.ask(
        "[bold]SR closure decision[/bold]",
        choices=["approve", "edit", "hold"],
        default="approve",
    )
    return choice  # type: ignore[return-value]


# ── HITL-Error: Stage 4 SOTI move failure ─────────────────────────────────────

def prompt_hitl_error(
    device: str,
    error: str,
    run_id: str = "unknown",
) -> Literal["skip", "retry", "abort"]:
    """
    HITL-Error gate: a SOTI move_device call raised an exception during Stage 4.
    L2 can skip this device and continue, retry it once, or abort the whole run.
    """
    if config.USE_MOCK_HITL:
        return _auto(f"HITL-Error [{device}]", "skip")  # type: ignore[return-value]
    if config.USE_WEB_HITL:
        return _web_hitl(f"HITL-Error:{device}", run_id, {"device": device, "error": error}, "skip")  # type: ignore[return-value]

    console.print(Panel(
        f"[bold red]SOTI move_device call failed[/bold red]\n\n"
        f"Device : [yellow]{device}[/yellow]\n"
        f"Error  : {error}\n\n"
        f"[bold]Options[/bold]\n"
        f"  skip  — Skip this device and continue with remaining moves\n"
        f"  retry — Retry this device once more\n"
        f"  abort — Abort the entire run and mark as FAILED",
        title="[HITL-Error] Move Failure",
        border_style="red",
    ))
    choice = Prompt.ask(
        "[bold]Decision[/bold]",
        choices=["skip", "retry", "abort"],
        default="skip",
    )
    return choice  # type: ignore[return-value]
