# Generated by GitHub Copilot
"""
NLEditAgent — natural-language edit accelerator for the HITL-2 pre-move gate.

The L2 reviewer types free text such as:
    "exclude bus 1234; move 5678 to LTM; BRT_DCU_0601_1 should stay in Production"

This agent parses that intent into STRUCTURED, VALIDATED edit operations against
the current move list. It only PROPOSES edits — they are never auto-applied. The
operator reviews the proposed overlay and still submits the actual decision through
the normal HITL-2 buttons.

Returned shape (always JSON-serialisable):
    {
      "edits": [
        {"action": "exclude",  "device": "...", "bus": "...", "reason": "..."},
        {"action": "retarget", "device": "...", "bus": "...",
         "target_folder": "Production|LTM", "reason": "..."}
      ],
      "unmatched": ["phrases the agent could not map to a known device"],
      "summary": "one-line plain-English description of the proposed overlay"
    }

This is a super-agent: it produces structured judgment, not just prose.
"""
import json
import re

from agents.sub_agents.base_agent import BaseAgent

_VALID_ACTIONS = {"exclude", "retarget"}
_VALID_FOLDERS = {"Production", "LTM"}


class NLEditAgent(BaseAgent):
    """Parses free-text reviewer intent into proposed, validated overlay edits."""

    def __init__(self):
        super().__init__("brt-nl-edit-v1")

    def _system_prompt(self) -> str:
        return (
            "You are an edit-parsing assistant for a transit fleet movement review. "
            "You are given a list of planned device moves (each with an index, bus "
            "number, device name, and target folder) and a free-text instruction from "
            "an L2 reviewer. Convert the instruction into structured edit operations. "
            "Allowed actions: 'exclude' (drop a device from the run) and 'retarget' "
            "(change its target folder to 'Production' or 'LTM'). "
            "Only reference devices/buses that appear in the provided move list. "
            "If part of the instruction cannot be mapped to a known device, add the raw "
            "phrase to 'unmatched'. Never invent devices. "
            "Respond with ONLY a JSON object of the form: "
            '{"edits":[{"action":"exclude|retarget","device":"<device>",'
            '"bus":"<bus>","target_folder":"Production|LTM","reason":"<why>"}],'
            '"unmatched":["..."],"summary":"<one line>"}. '
            "Omit target_folder for exclude actions."
        )

    # ── Public API ───────────────────────────────────────────────────────────

    def parse_edits(self, free_text: str, moves: list[dict]) -> dict:
        """
        Parse free_text against the current move list and return proposed edits.
        moves: list of dicts with keys index, device (current_device), bus
               (bus_number), target (target_folder).
        """
        free_text = (free_text or "").strip()
        if not free_text:
            return {"edits": [], "unmatched": [], "summary": "No instruction provided."}

        if self.config_mock():
            return self._mock_parse(free_text, moves)

        user_content = json.dumps(
            {"instruction": free_text, "moves": moves}, default=str
        )
        try:
            raw = self._complete(
                self._system_prompt(), user_content, json_mode=True, max_tokens=1500
            )
            parsed = json.loads(raw) if raw else {}
        except Exception as exc:  # noqa: BLE001 — fall back to deterministic parse
            return {
                "edits": [],
                "unmatched": [free_text],
                "summary": f"Could not parse via LLM ({exc}); review manually.",
            }
        return self._validate(parsed, moves)

    # ── Helpers ───────────────────────────────────────────────────────────────

    @staticmethod
    def config_mock() -> bool:
        import config
        return config.USE_MOCK_LLM

    def _validate(self, parsed: dict, moves: list[dict]) -> dict:
        """Drop any edit that references a device/bus not in the move list."""
        known_devices = {str(m.get("device", "")).lower() for m in moves}
        known_buses = {str(m.get("bus", "")) for m in moves}
        clean: list[dict] = []
        unmatched: list[str] = list(parsed.get("unmatched", []) or [])

        for e in parsed.get("edits", []) or []:
            action = str(e.get("action", "")).lower()
            device = str(e.get("device", "") or "")
            bus = str(e.get("bus", "") or "")
            if action not in _VALID_ACTIONS:
                unmatched.append(f"{action} {device or bus}".strip())
                continue
            if device.lower() not in known_devices and bus not in known_buses:
                unmatched.append(f"{action} {device or bus}".strip())
                continue
            edit = {"action": action, "device": device, "bus": bus,
                    "reason": str(e.get("reason", "") or "")}
            if action == "retarget":
                folder = str(e.get("target_folder", ""))
                folder = "LTM" if folder.upper() == "LTM" else (
                    "Production" if folder else "")
                if folder not in _VALID_FOLDERS:
                    unmatched.append(f"retarget {device or bus} (no valid folder)")
                    continue
                edit["target_folder"] = folder
            clean.append(edit)

        summary = parsed.get("summary") or self._summarise(clean, unmatched)
        return {"edits": clean, "unmatched": unmatched, "summary": summary}

    @staticmethod
    def _summarise(edits: list[dict], unmatched: list[str]) -> str:
        ex = sum(1 for e in edits if e["action"] == "exclude")
        rt = sum(1 for e in edits if e["action"] == "retarget")
        bits = []
        if ex:
            bits.append(f"{ex} device(s) to exclude")
        if rt:
            bits.append(f"{rt} device(s) to retarget")
        if not bits:
            bits.append("no applicable edits")
        if unmatched:
            bits.append(f"{len(unmatched)} phrase(s) unmatched")
        return "Proposed overlay: " + ", ".join(bits) + " (review before applying)."

    # ── Mock (deterministic regex parser; works without the LLM) ──────────────

    def _mock_parse(self, free_text: str, moves: list[dict]) -> dict:
        """
        Lightweight rule-based parse so the feature works with USE_MOCK_LLM=true.
        Recognises 'exclude/remove/skip <ref>' and 'move/retarget <ref> to <folder>'.
        <ref> may be a bus number or a device name token. A bus reference resolves
        to ALL devices on that bus (DCU + BFTP). Bus numbers are compared with
        leading zeros stripped so '0601' and '601' both match.
        """
        def _norm(bus: str) -> str:
            bus = str(bus).strip()
            return bus.lstrip("0") or "0"

        by_bus: dict[str, list[dict]] = {}
        for m in moves:
            by_bus.setdefault(_norm(m.get("bus", "")), []).append(m)
        by_device = {str(m.get("device", "")).lower(): m for m in moves}

        def _resolve(token: str) -> list[dict]:
            """Return all move rows a token refers to (device → 1 row, bus → N)."""
            token = token.strip().strip(".,;")
            if token.lower() in by_device:
                return [by_device[token.lower()]]
            # device-style token, e.g. BRT_DCU_0601_1 → use its embedded bus
            mnum = re.search(r"(\d{3,4})", token)
            if mnum and _norm(mnum.group(1)) in by_bus:
                return by_bus[_norm(mnum.group(1))]
            return []

        edits: list[dict] = []
        unmatched: list[str] = []
        seen: set[tuple] = set()

        def _emit(action: str, rows: list[dict], clause: str, folder: str | None = None) -> None:
            for row in rows:
                key = (action, row.get("device"))
                if key in seen:
                    continue
                seen.add(key)
                edit = {
                    "action": action,
                    "device": row.get("device", ""),
                    "bus": str(row.get("bus", "")),
                    "reason": f"NL instruction: '{clause}'",
                }
                if action == "retarget" and folder:
                    edit["target_folder"] = folder
                edits.append(edit)

        # Split on ; and newlines into clauses
        for clause in re.split(r"[;\n]+", free_text):
            c = clause.strip()
            if not c:
                continue
            low = c.lower()
            refs = re.findall(r"(BRT_[A-Z]+_\d+_\d+|\b\d{3,4}\b)", c, re.IGNORECASE)
            rows: list[dict] = []
            for r in refs:
                rows.extend(_resolve(r))

            # retarget: "...<ref>... to <folder>"
            mret = re.search(r"\bto\s+(production|ltm)\b", low)
            if mret or any(k in low for k in ("retarget", "→", "->")):
                folder = None
                if mret:
                    folder = "LTM" if mret.group(1) == "ltm" else "Production"
                if rows and folder:
                    _emit("retarget", rows, c, folder)
                    continue
                unmatched.append(c)
                continue
            # exclude: "exclude/remove/skip/drop <ref>"
            if any(k in low for k in ("exclude", "remove", "skip", "drop", "don't move", "do not move")):
                if rows:
                    _emit("exclude", rows, c)
                    continue
                unmatched.append(c)
                continue
            unmatched.append(c)

        return {
            "edits": edits,
            "unmatched": unmatched,
            "summary": self._summarise(edits, unmatched),
        }
