# Generated by GitHub Copilot
"""
8-stage BRT Fleet Movement orchestrator.

State machine:
  RECEIVED → PARSING → PLANNED → AWAITING_PRE_APPROVAL →
  MOVING → RECONCILING → AWAITING_VALIDATION →
  DRAFTING_SR → AWAITING_SR_APPROVAL → COMPLETED
  (or ABORTED / FAILED / ON_HOLD at gates)

Hybrid design principle:
  - All routing, comparisons, and decisions are pure Python
  - LLM is invoked ONLY via narrator.narrate() calls for prose generation
"""
import time
import logging
from datetime import datetime, timezone

import config
from agents.sub_agents.parser_narrator import ParserNarrator
from agents.sub_agents.reconciliation_narrator import ReconciliationNarrator
from agents.sub_agents.execution_narrator import ExecutionNarrator
from mcp_clients.soti_client import SotiMcpClient
from core.excel_parser import parse_dva
from core.reconciler import reconcile
from core.cosmos_client import get_intake_record
from core.state_store import (
    save_run_doc,
    append_step,
    append_tool_call,
    append_approval,
)
from schemas.run_doc import RunDoc
from tools.hitl_console import (
    prompt_missing_dva,
    prompt_pre_move_approval,
    prompt_post_move_validation,
    prompt_schema_fix,
    prompt_sr_closure,
    prompt_subset_selection,
    prompt_hitl_error,
)

log = logging.getLogger(__name__)


class Orchestrator:
    """
    Drives the 8-stage BRT fleet movement pipeline.
    LLM is invoked ONLY for narrator calls — all routing is pure Python.
    """

    def __init__(self, run_id: str):
        self.run_id = run_id
        self.run_doc: RunDoc | None = None
        self.soti = SotiMcpClient()
        self.parser_narrator = ParserNarrator()
        self.recon_narrator = ReconciliationNarrator()
        self.exec_narrator = ExecutionNarrator()

    async def run(self) -> None:
        # ── Stage 1: Initialise ──────────────────────────────────────────────
        # Build the intake_id that the Intake Function wrote to Cosmos DB.
        # Convention: "intake_BRT_2026-05-27" from run_id "BRT-2026-05-27".
        # Split on the FIRST hyphen only: BRT | 2026-05-27 → intake_BRT_2026-05-27
        _parts = self.run_id.split("-", 1)
        intake_id = f"intake_{_parts[0]}_{_parts[1]}" if len(_parts) == 2 else f"intake_{self.run_id}"

        # Create the run document immediately so every subsequent state
        # transition is durably recorded, even if we abort at HITL-1.
        self.run_doc = RunDoc(
            run_id=self.run_id,
            intake_id=intake_id,
            agency="BRT",
            state="RECEIVED",
            current_step="stage1_trigger",
            dva_path=config.SAMPLE_DVA,    # overwritten below when record found
            started_utc=datetime.now(timezone.utc),
        )
        save_run_doc(self.run_doc)

        # ── Cosmos DB intake-record check (HITL-1 gate) ──────────────────────
        # The Intake Function writes a READY_FOR_RUN record BEFORE this
        # orchestrator starts.  If the record is absent the DVA email has not
        # arrived (or the Intake Function failed) → pause and ask L2.
        self.run_doc.state = "ON_HOLD"
        self.run_doc.current_step = "stage1_cosmos_check"
        save_run_doc(self.run_doc)

        intake_record = await get_intake_record(intake_id)

        _hitl1_attempts = 0
        _MAX_HITL1_RETRIES = 3

        while intake_record is None:
            _hitl1_attempts += 1
            log.warning(
                "Intake record '%s' not found in Cosmos DB (status != READY_FOR_RUN)",
                intake_id,
            )
            decision = prompt_missing_dva(intake_id)
            append_approval(self.run_doc, "HITL-1", decision, "")

            if decision == "abort" or _hitl1_attempts >= _MAX_HITL1_RETRIES:
                if _hitl1_attempts >= _MAX_HITL1_RETRIES:
                    log.error(
                        "HITL-1 max retries (%d) reached — aborting | run_id=%s",
                        _MAX_HITL1_RETRIES, self.run_id,
                    )
                self.run_doc.state = "ABORTED"
                append_step(self.run_doc, "stage1_cosmos_check", "ABORTED",
                            {"reason": "intake record not found", "attempts": _hitl1_attempts})
                save_run_doc(self.run_doc)
                return

            intake_record = await get_intake_record(intake_id)
            if intake_record is None:
                log.info("Still no intake record after wait — re-prompting L2 (attempt %d/%d)",
                         _hitl1_attempts, _MAX_HITL1_RETRIES)

        # Record found — bind DVA path from the blob URI in the intake record
        self.run_doc.state = "RECEIVED"
        self.run_doc.dva_path = intake_record.attachment.blob_uri
        append_step(self.run_doc, "stage1_cosmos_check", "DONE", {
            "intake_id": intake_id,
            "dva_blob_uri": intake_record.attachment.blob_uri,
            "structural_check": intake_record.structural_check.model_dump(),
        })
        save_run_doc(self.run_doc)

        await self.soti.connect()
        log.info(
            "Stage 1 complete — intake record bound | run_id=%s | blob=%s",
            self.run_id,
            intake_record.attachment.blob_uri,
        )

        # ── Stage 2: Parse DVA (pure code) ───────────────────────────────────
        self.run_doc.state = "PARSING"
        self.run_doc.current_step = "stage2_parse"
        save_run_doc(self.run_doc)

        # dva_path was set from the Cosmos DB intake record in Stage 1
        intended_moves, schema_issues = parse_dva(self.run_doc.dva_path)

        if schema_issues:
            decision = prompt_schema_fix(schema_issues)
            append_approval(self.run_doc, "HITL-schema", decision, "")
            if decision == "abort":
                self.run_doc.state = "ABORTED"
                save_run_doc(self.run_doc)
                log.warning("Run aborted at schema gate | run_id=%s", self.run_id)
                return

        # LLM narration — prose only, no decisions
        parser_summary = self.parser_narrator.narrate({
            "intended_moves": [m.model_dump() for m in intended_moves],
            "schema_issues": schema_issues,
        })

        self.run_doc.state = "PLANNED"
        append_step(self.run_doc, "stage2_parse", "DONE", {
            "count": len(intended_moves),
            "schema_issues": len(schema_issues),
            "summary": parser_summary,
        })
        save_run_doc(self.run_doc)
        log.info("Stage 2 complete — %d moves planned, %d schema issues",
                 len(intended_moves), len(schema_issues))

        # ── Stage 2b: Enrich moves with current SOTI location (read-only) ────
        # Queries SOTI for each device's current folder before asking for approval.
        # This is purely informational — no changes are made to SOTI here.
        self.run_doc.current_step = "stage2b_soti_enrich"
        save_run_doc(self.run_doc)

        for move in intended_moves:
            t0 = time.monotonic()
            device_info = await self.soti.get_device(move.current_device)
            duration_ms = int((time.monotonic() - t0) * 1000)
            current_folder = (
                (device_info.get("folder")
                 or device_info.get("CurrentGroup")
                 or device_info.get("GroupPath")
                 or "UNKNOWN")
                if device_info else "UNKNOWN"
            )
            append_tool_call(
                self.run_doc, "soti.get_device (enrich)",
                {"device": move.current_device}, device_info, duration_ms,
            )

            # ── Stale LTM tag detection ───────────────────────────────────
            # If the expected BRT_DCU_ name is not found but the bus is being
            # sent to Production, check whether SOTI holds it as LTM_BRT_DCU_.
            # This indicates a leftover LTM rename tag from a prior maintenance
            # cycle.  We update current_device so Stage 4 moves the right object.
            if current_folder == "UNKNOWN" and move.target_folder == "Production":
                _ltm_name = f"LTM_{move.current_device}"
                _t1 = time.monotonic()
                _ltm_info = await self.soti.get_device(_ltm_name)
                _ltm_dur = int((time.monotonic() - _t1) * 1000)
                if _ltm_info:
                    _ltm_folder = (
                        _ltm_info.get("folder")
                        or _ltm_info.get("CurrentGroup")
                        or _ltm_info.get("GroupPath")
                        or "UNKNOWN"
                    )
                    move.stale_ltm_tag = True
                    move.current_soti_folder = (
                        f"\u26a0 STALE LTM TAG (found as {_ltm_name} in {_ltm_folder})"
                    )
                    move.current_device = _ltm_name   # Stage 4 must move this name
                    current_folder = move.current_soti_folder
                    log.warning(
                        "Stage 2b \u2014 STALE LTM TAG: bus %s found as %s in SOTI folder '%s'",
                        move.bus_number, _ltm_name, _ltm_folder,
                    )
                    append_tool_call(
                        self.run_doc, "soti.get_device (stale_ltm_check)",
                        {"device": _ltm_name}, _ltm_info, _ltm_dur,
                    )

            if move.current_soti_folder is None:
                move.current_soti_folder = current_folder
            log.info("Stage 2b \u2014 %s current SOTI folder: %s", move.current_device, move.current_soti_folder)

        append_step(self.run_doc, "stage2b_enrich", "DONE",
                    {"enriched": len(intended_moves)})
        save_run_doc(self.run_doc)

        # ── Stage 3: HITL pre-move approval ──────────────────────────────────
        self.run_doc.state = "AWAITING_PRE_APPROVAL"
        self.run_doc.current_step = "stage3_hitl_pre"
        save_run_doc(self.run_doc)

        decision = prompt_pre_move_approval(intended_moves)
        append_approval(self.run_doc, "HITL-2", decision, "")

        if decision == "reject":
            self.run_doc.state = "ABORTED"
            append_step(self.run_doc, "stage3_approval", "REJECTED", {})
            save_run_doc(self.run_doc)
            return

        approved_moves = intended_moves
        if decision == "approve_subset":
            indices = prompt_subset_selection(intended_moves)
            approved_moves = [intended_moves[i] for i in indices]

        append_step(self.run_doc, "stage3_approval", "DONE", {
            "decision": decision,
            "approved_count": len(approved_moves),
        })
        save_run_doc(self.run_doc)

        # ── Stage 4: Execute moves via SOTI MCP ──────────────────────────────
        self.run_doc.state = "MOVING"
        self.run_doc.current_step = "stage4_execute"
        save_run_doc(self.run_doc)

        for move in approved_moves:
            t0 = time.monotonic()
            try:
                result = await self.soti.move_device(move.current_device, move.target_folder)
            except Exception as _exc:
                _err = str(_exc)
                log.error(
                    "Stage 4 \u2014 move_device exception for %s: %s",
                    move.current_device, _err,
                )
                _err_decision = prompt_hitl_error(move.current_device, _err)
                append_approval(
                    self.run_doc,
                    f"HITL-Error:{move.current_device}",
                    _err_decision,
                    _err,
                )
                if _err_decision == "abort":
                    self.run_doc.state = "FAILED"
                    append_step(
                        self.run_doc, "stage4_execute", "FAILED",
                        {"reason": f"move_device exception on {move.current_device}", "error": _err},
                    )
                    save_run_doc(self.run_doc)
                    await self.soti.disconnect()
                    return
                elif _err_decision == "retry":
                    try:
                        result = await self.soti.move_device(move.current_device, move.target_folder)
                    except Exception as _exc2:
                        log.error(
                            "Stage 4 \u2014 retry also failed for %s: %s",
                            move.current_device, _exc2,
                        )
                        result = {"success": False, "error": str(_exc2), "skipped": True}
                else:  # skip
                    result = {"success": False, "skipped": True}
            duration_ms = int((time.monotonic() - t0) * 1000)
            append_tool_call(
                self.run_doc,
                "soti.move_device",
                {"device": move.current_device, "target": move.target_folder},
                result,
                duration_ms,
            )

        append_step(self.run_doc, "stage4_execute", "DONE",
                    {"move_calls": len(approved_moves)})
        save_run_doc(self.run_doc)
        log.info("Stage 4 complete — %d move calls issued", len(approved_moves))

        # ── Stage 5: Auto-reconcile (pure code) ──────────────────────────────
        self.run_doc.state = "RECONCILING"
        self.run_doc.current_step = "stage5_reconcile"
        save_run_doc(self.run_doc)

        actual_locations: dict[str, str] = {}
        for move in approved_moves:
            t0 = time.monotonic()
            r = await self.soti.get_device(move.current_device)
            duration_ms = int((time.monotonic() - t0) * 1000)
            actual_locations[move.current_device] = r.get("folder", "UNKNOWN")
            append_tool_call(
                self.run_doc, "soti.get_device",
                {"device": move.current_device}, r, duration_ms,
            )

        recon_result = reconcile(approved_moves, actual_locations)

        # LLM narration — prose only
        recon_result.summary_text = self.recon_narrator.narrate({
            "moved": recon_result.moved,
            "unmoved": recon_result.unmoved,
            "unidentified": recon_result.unidentified,
        })

        append_step(self.run_doc, "stage5_reconcile", "DONE", {
            "moved": len(recon_result.moved),
            "unmoved": len(recon_result.unmoved),
            "unidentified": len(recon_result.unidentified),
            "summary": recon_result.summary_text,
        })
        save_run_doc(self.run_doc)
        log.info("Stage 5 complete — %d moved, %d unmoved, %d unidentified",
                 len(recon_result.moved), len(recon_result.unmoved),
                 len(recon_result.unidentified))

        # ── Stage 6: HITL post-move validation ───────────────────────────────
        self.run_doc.state = "AWAITING_VALIDATION"
        self.run_doc.current_step = "stage6_hitl_validation"
        save_run_doc(self.run_doc)

        decision = prompt_post_move_validation(recon_result)
        append_approval(self.run_doc, "HITL-3", decision, "")

        if decision == "rerun":
            self.run_doc.state = "FAILED"
            append_step(self.run_doc, "stage6_validation", "RERUN_REQUESTED", {})
            save_run_doc(self.run_doc)
            log.warning("Rerun requested by L2 | run_id=%s", self.run_id)
            return

        if len(recon_result.moved) == 0:
            self.run_doc.state = "COMPLETED"
            append_step(self.run_doc, "stage6_validation", "SKIPPED_NO_MOVEMENTS", {})
            save_run_doc(self.run_doc)
            log.info("No movements — run completed without SR | run_id=%s", self.run_id)
            return

        # ── Stage 7: Draft SR notes + email (LLM prose) ──────────────────────
        self.run_doc.state = "DRAFTING_SR"
        self.run_doc.current_step = "stage7_draft_sr"
        save_run_doc(self.run_doc)

        sr_notes = self.exec_narrator.narrate({
            "moved": recon_result.moved,
            "run_id": self.run_id,
        })

        self.run_doc.state = "AWAITING_SR_APPROVAL"
        save_run_doc(self.run_doc)

        decision = prompt_sr_closure(sr_notes)
        append_approval(self.run_doc, "HITL-4", decision, "")

        if decision == "hold":
            self.run_doc.state = "ON_HOLD"
            append_step(self.run_doc, "stage7_sr", "ON_HOLD", {})
            save_run_doc(self.run_doc)
            return

        # ── Stage 8: Wrap-up ─────────────────────────────────────────────────
        self.run_doc.state = "EXECUTING"
        sr_number = f"SR-MOCK-{self.run_id}"
        # TODO: real ServiceNow MCP call — Phase 2
        # TODO: real Fleet.xlsx append via Microsoft Graph MCP — Phase 2
        # TODO: real summary email via Graph Send Mail — Phase 2

        self.run_doc.state = "COMPLETED"
        self.run_doc.current_step = "stage8_complete"
        append_step(self.run_doc, "stage8_complete", "DONE",
                    {"sr_number": sr_number, "sr_notes": sr_notes})
        save_run_doc(self.run_doc)
        log.info("Stage 8 complete — COMPLETED | sr_number=%s | run_id=%s",
                 sr_number, self.run_id)

        await self.soti.disconnect()
