# Generated by GitHub Copilot
"""
QAAgent — conversational Q&A over a single run's data.

During any HITL pause the L2 reviewer can ask questions like:
    "why isn't bus 1234 moving?"
    "how many devices go to LTM?"
    "what failed in reconciliation?"

The agent answers strictly from the supplied run context (run document + pending
gate payload). It explains and reasons; it never triggers moves or changes state.
"""
import json

from agents.sub_agents.base_agent import BaseAgent


class QAAgent(BaseAgent):
    """Answers reviewer questions grounded in the run/movement data."""

    def __init__(self):
        super().__init__("brt-qa-v1")

    def _system_prompt(self) -> str:
        return (
            "You are a helpful assistant for an L2 operator reviewing a Brampton "
            "Transit (BRT) fleet device-movement run. Answer the operator's question "
            "using ONLY the run context provided as JSON (run state, planned moves, "
            "current SOTI folders, reconciliation results, approvals, exceptions). "
            "If the answer is not in the context, say so plainly and suggest where the "
            "operator could look. Be concise and specific — cite bus numbers, device "
            "names, folders, and counts from the data. Plain English only; no JSON or "
            "code in your reply. Never instruct the system to move devices — you only "
            "explain and advise."
        )

    # ── Public API ───────────────────────────────────────────────────────────

    def answer(self, question: str, run_context: dict) -> str:
        """Answer `question` grounded in `run_context`. Safe in mock mode."""
        question = (question or "").strip()
        if not question:
            return "Please enter a question about this run."

        import config
        if config.USE_MOCK_LLM:
            return self._mock_answer(question, run_context)

        user_content = json.dumps(
            {"question": question, "run_context": run_context}, default=str
        )
        text = self._complete(self._system_prompt(), user_content, max_tokens=800)
        return text or "I couldn't generate an answer — please review the run details."

    # ── Mock (keyword-driven; works without the LLM) ──────────────────────────

    def _mock_answer(self, question: str, ctx: dict) -> str:
        q = question.lower()
        moves = ctx.get("intended_moves") or ctx.get("moves") or []
        recon = ctx.get("recon_result") or {}
        state = ctx.get("state", "unknown")

        # Question about a specific bus / device
        import re
        m = re.search(r"\b(\d{3,4})\b", q)
        if m:
            bus = m.group(1)
            match = [mv for mv in moves if str(mv.get("bus_number", "")) == bus
                     or bus in str(mv.get("current_device", ""))]
            if match:
                mv = match[0]
                folder = mv.get("current_soti_folder") or "unknown"
                return (
                    f"Bus {bus} ({mv.get('current_device', '?')}) is planned to move to "
                    f"{mv.get('target_folder', '?')}. Its current SOTI folder is '{folder}', "
                    f"vehicle status '{mv.get('vehicle_status', '?')}'. "
                    f"Reason: {mv.get('reason', 'n/a')}."
                    + (" Note: this device carries a stale LTM tag."
                       if mv.get("stale_ltm_tag") else "")
                )
            return (
                f"I don't see bus {bus} in this run's planned moves. It may have been "
                f"filtered out during parsing, or its status didn't map to a move."
            )

        # Counts
        if "ltm" in q and ("how many" in q or "count" in q):
            n = sum(1 for mv in moves if "LTM" in str(mv.get("target_folder", "")).upper())
            return f"{n} device(s) are targeting LTM in this run."
        if "production" in q and ("how many" in q or "count" in q):
            n = sum(1 for mv in moves if "LTM" not in str(mv.get("target_folder", "")).upper())
            return f"{n} device(s) are targeting Production in this run."
        if "how many" in q and ("move" in q or "device" in q):
            return f"This run has {len(moves)} planned device move(s)."

        # Failures / exceptions
        if any(k in q for k in ("fail", "unmoved", "exception", "error", "not move")):
            unmoved = recon.get("unmoved", [])
            unidentified = recon.get("unidentified", [])
            if not unmoved and not unidentified:
                return "No failures recorded — reconciliation shows all moves succeeded."
            parts = []
            if unmoved:
                parts.append(f"{len(unmoved)} device(s) failed to move "
                             f"({'; '.join(d.get('reason', '?') for d in unmoved[:3])})")
            if unidentified:
                parts.append(f"{len(unidentified)} device(s) were not found in SOTI")
            return ". ".join(parts) + "."

        # Status / where are we
        if any(k in q for k in ("status", "state", "where", "stage", "progress")):
            return (f"This run is currently in state '{state}'. "
                    f"{len(moves)} move(s) are planned.")

        return (
            "I can answer questions about this run's planned moves, target folders, "
            "current SOTI locations, failures, and status. Try asking e.g. "
            "'why isn't bus 1234 moving?' or 'how many devices go to LTM?'. "
            f"(This run is in state '{state}' with {len(moves)} planned move(s).)"
        )
