#!/usr/bin/env bash
# Generated by GitHub Copilot
# deploy_function.sh – Deploy the Azure Durable Functions app using Managed Identity.
# Run this FIRST before deploy_job.sh.
#
# Prerequisites:
#   - Azure CLI logged in:  az login
#   - Functions Core Tools v4 installed
#   - Python 3.11 venv present at ../function_app/.venv

set -euo pipefail

# ── Parameters ───────────────────────────────────────────────────────────────
RG="pds-dev-agenticai-dashboard"
LOCATION="canadacentral"
FUNC_APP_NAME="fleet-phase1-func"          # Must be globally unique
STORAGE_ACCOUNT="fleetphase1sa01"    # Must be 3-24 chars, lowercase alphanumeric
APP_INSIGHTS_NAME="fleet-phase1-appinsights"
FUNC_PLAN_NAME="fleet-phase1-plan"
PYTHON_VERSION="3.11"

# ── 1. Create Resource Group ─────────────────────────────────────────────────
echo ">> Verifying resource group exists: ${RG}"
az group show --name "${RG}" --output none || { echo "ERROR: RG ${RG} not found or not accessible"; exit 1; }

# ── 2. Create Storage Account (required by Functions runtime) ────────────────
echo ">> Creating storage account: ${STORAGE_ACCOUNT}"
az storage account create \
  --name "${STORAGE_ACCOUNT}" \
  --resource-group "${RG}" \
  --location "${LOCATION}" \
  --sku Standard_LRS \
  --kind StorageV2 \
  --allow-blob-public-access false \
  --min-tls-version TLS1_2

# ── 3. Create Application Insights ───────────────────────────────────────────
echo ">> Creating Application Insights workspace"
az monitor app-insights component create \
  --app "${APP_INSIGHTS_NAME}" \
  --resource-group "${RG}" \
  --location "${LOCATION}" \
  --kind web \
  --application-type web

APP_INSIGHTS_KEY=$(az monitor app-insights component show \
  --app "${APP_INSIGHTS_NAME}" \
  --resource-group "${RG}" \
  --query instrumentationKey -o tsv)

# ── 4. Create Consumption Plan ────────────────────────────────────────────────
echo ">> Creating Flex Consumption plan"
az functionapp plan create \
  --name "${FUNC_PLAN_NAME}" \
  --resource-group "${RG}" \
  --location "${LOCATION}" \
  --sku Y1 \
  --is-linux

# ── 5. Create Function App ────────────────────────────────────────────────────
echo ">> Creating Function App: ${FUNC_APP_NAME}"
az functionapp create \
  --name "${FUNC_APP_NAME}" \
  --resource-group "${RG}" \
  --storage-account "${STORAGE_ACCOUNT}" \
  --plan "${FUNC_PLAN_NAME}" \
  --runtime python \
  --runtime-version "${PYTHON_VERSION}" \
  --functions-version 4 \
  --app-insights-key "${APP_INSIGHTS_KEY}" \
  --assign-identity "[system]"

# ── 6. Grant Function App's Managed Identity access to Storage ───────────────
echo ">> Assigning Storage Blob Data Contributor role to Function App identity"
FUNC_PRINCIPAL_ID=$(az functionapp identity show \
  --name "${FUNC_APP_NAME}" \
  --resource-group "${RG}" \
  --query principalId -o tsv)

STORAGE_ID=$(az storage account show \
  --name "${STORAGE_ACCOUNT}" \
  --resource-group "${RG}" \
  --query id -o tsv)

az role assignment create \
  --assignee "${FUNC_PRINCIPAL_ID}" \
  --role "Storage Blob Data Contributor" \
  --scope "${STORAGE_ID}"

az role assignment create \
  --assignee "${FUNC_PRINCIPAL_ID}" \
  --role "Storage Queue Data Contributor" \
  --scope "${STORAGE_ID}"

az role assignment create \
  --assignee "${FUNC_PRINCIPAL_ID}" \
  --role "Storage Table Data Contributor" \
  --scope "${STORAGE_ID}"

# ── 7. Enable AzureWebJobsStorage__accountName (identity-based) ─────────────
echo ">> Configuring identity-based storage connection"
az functionapp config appsettings set \
  --name "${FUNC_APP_NAME}" \
  --resource-group "${RG}" \
  --settings \
    "AzureWebJobsStorage__accountName=${STORAGE_ACCOUNT}" \
    "AzureWebJobsFeatureFlags=EnableWorkerIndexing"

# ── 8. Deploy function code ──────────────────────────────────────────────────
echo ">> Deploying function code"
cd "$(dirname "$0")/../function_app"
func azure functionapp publish "${FUNC_APP_NAME}" --python

echo ""
echo "✔ Function App deployed."
echo "  Starter URL: https://${FUNC_APP_NAME}.azurewebsites.net/api/start"
