#!/usr/bin/env bash
# Generated by GitHub Copilot
# deploy_job.sh – Build the scheduler Docker image and create the Azure Container Apps Job.
# Run this AFTER deploy_function.sh.
#
# Prerequisites:
#   - Azure CLI logged in:  az login
#   - Container Apps extension: az extension add --name containerapp
#   - ACR created (this script creates it if missing)
#   - FUNC_APP_NAME matches what was used in deploy_function.sh

set -euo pipefail

# ── Parameters ───────────────────────────────────────────────────────────────
RG="pds-dev-agenticai-dashboard"
LOCATION="canadacentral"
FUNC_APP_NAME="fleet-phase1-func"
ACR_NAME="brtfleetacr001"               # Must be globally unique, 5-50 alphanumeric
JOB_NAME="brt-fleet-scheduler-job"
ENV_NAME="brt-fleet-cae"               # Container Apps Environment name
IMAGE_TAG="brt-scheduler:latest"
# Cron: 5:30 AM UTC = 12:30 AM EST (UTC-5).  See DST note in scheduler_job/trigger.sh.
CRON_EXPRESSION="30 5 * * *"

# ── 1. Ensure Container Apps extension is installed ──────────────────────────
echo ">> Ensuring Container Apps CLI extension"
az extension add --name containerapp --upgrade --yes 2>/dev/null || true

# ── 2. Create Azure Container Registry ───────────────────────────────────────
echo ">> Creating ACR: ${ACR_NAME}"
az acr create \
  --name "${ACR_NAME}" \
  --resource-group "${RG}" \
  --sku Basic \
  --admin-enabled false

# ── 3. Build and push image via ACR Tasks (no local Docker needed) ───────────
echo ">> Building and pushing Docker image via ACR Tasks"
az acr build \
  --registry "${ACR_NAME}" \
  --image "${IMAGE_TAG}" \
  "$(dirname "$0")/../scheduler_job/"

# ── 4. Create Container Apps Environment (Log Analytics workspace auto-created)
echo ">> Creating Container Apps Environment: ${ENV_NAME}"
az containerapp env create \
  --name "${ENV_NAME}" \
  --resource-group "${RG}" \
  --location "${LOCATION}"

# ── 5. Retrieve the Function App starter URL ──────────────────────────────────
FUNC_APP_URL="https://${FUNC_APP_NAME}.azurewebsites.net"
echo ">> Function App base URL: ${FUNC_APP_URL}"

# ── 5b. Retrieve the Function App default key for authentication ──────────────
echo ">> Retrieving Function App default key"
FUNC_KEY=$(az functionapp keys list \
  --name "${FUNC_APP_NAME}" \
  --resource-group "${RG}" \
  --query "functionKeys.default" -o tsv)

if [ -z "${FUNC_KEY}" ]; then
  echo "ERROR: Could not retrieve Function App key. Is ${FUNC_APP_NAME} deployed?" >&2
  exit 1
fi

# ── 6. Create the Container Apps Job ─────────────────────────────────────────
echo ">> Creating Container Apps Job: ${JOB_NAME}"
az containerapp job create \
  --name "${JOB_NAME}" \
  --resource-group "${RG}" \
  --environment "${ENV_NAME}" \
  --trigger-type "Schedule" \
  --cron-expression "${CRON_EXPRESSION}" \
  --image "${ACR_NAME}.azurecr.io/${IMAGE_TAG}" \
  --registry-server "${ACR_NAME}.azurecr.io" \
  --mi-system-assigned \
  --env-vars "FUNC_APP_URL=${FUNC_APP_URL}" "FUNC_KEY=${FUNC_KEY}" \
  --cpu 0.25 \
  --memory 0.5Gi \
  --replica-timeout 300 \
  --replica-retry-limit 1 \
  --parallelism 1 \
  --replica-completion-count 1

# ── 7. Grant the Job's Managed Identity permission to pull from ACR ───────────
echo ">> Granting AcrPull role to Container Apps Job identity"
JOB_PRINCIPAL_ID=$(az containerapp job show \
  --name "${JOB_NAME}" \
  --resource-group "${RG}" \
  --query "identity.principalId" -o tsv)

ACR_ID=$(az acr show \
  --name "${ACR_NAME}" \
  --resource-group "${RG}" \
  --query id -o tsv)

az role assignment create \
  --assignee "${JOB_PRINCIPAL_ID}" \
  --role "AcrPull" \
  --scope "${ACR_ID}"

echo ""
echo "✔ Container Apps Job created."
echo "  Job name  : ${JOB_NAME}"
echo "  Schedule  : ${CRON_EXPRESSION} UTC (12:30 AM EST)"
echo ""
echo "  To trigger manually:"
echo "  az containerapp job start --name ${JOB_NAME} --resource-group ${RG}"
