#!/usr/bin/env bash
# Generated by GitHub Copilot
# test_local.sh – Commands to test the skeleton locally and trigger it manually in Azure.
#
# Usage:
#   bash deploy/test_local.sh [local|azure]
#   Default: local

set -euo pipefail

MODE="${1:-local}"

# ── Shared config (must match deploy scripts) ────────────────────────────────
RG="rg-brt-fleet-phase1"
FUNC_APP_NAME="brt-fleet-func"
JOB_NAME="brt-fleet-scheduler-job"

# ────────────────────────────────────────────────────────────────────────────
# LOCAL MODE
# ────────────────────────────────────────────────────────────────────────────
if [[ "${MODE}" == "local" ]]; then

  FUNC_BASE_URL="http://localhost:7071"
  RUN_ID="BRT-$(date +%Y-%m-%d)-LOCAL"

  echo "────────────────────────────────────────────────"
  echo " LOCAL TEST"
  echo " Ensure 'func start' is running in another terminal"
  echo " before executing this script."
  echo "────────────────────────────────────────────────"
  echo ""

  # 1. Trigger the HTTP starter
  echo ">> POST ${FUNC_BASE_URL}/api/start?runId=${RUN_ID}"
  RESPONSE=$(curl -s -X POST \
    "${FUNC_BASE_URL}/api/start?runId=${RUN_ID}" \
    -H "Content-Type: application/json")

  echo ""
  echo "Response from starter:"
  echo "${RESPONSE}" | python3 -m json.tool 2>/dev/null || echo "${RESPONSE}"

  # 2. Extract the statusQueryGetUri from the response
  STATUS_URL=$(echo "${RESPONSE}" | python3 -c \
    "import sys,json; d=json.load(sys.stdin); print(d.get('statusQueryGetUri',''))" 2>/dev/null || echo "")

  if [[ -n "${STATUS_URL}" ]]; then
    echo ""
    echo ">> Polling orchestration status (waiting 5 s)..."
    sleep 5
    curl -s "${STATUS_URL}" | python3 -m json.tool 2>/dev/null
  fi

# ────────────────────────────────────────────────────────────────────────────
# AZURE MODE – manual trigger
# ────────────────────────────────────────────────────────────────────────────
elif [[ "${MODE}" == "azure" ]]; then

  echo "────────────────────────────────────────────────"
  echo " AZURE MANUAL TRIGGER"
  echo "────────────────────────────────────────────────"

  # 1. Directly call the deployed Function App HTTP starter
  FUNC_BASE_URL="https://${FUNC_APP_NAME}.azurewebsites.net"
  RUN_ID="BRT-$(date +%Y-%m-%d)-MANUAL"

  echo ">> Calling Function App starter"
  curl -s -X POST \
    "${FUNC_BASE_URL}/api/start?runId=${RUN_ID}" \
    -H "Content-Type: application/json" \
    | python3 -m json.tool 2>/dev/null

  echo ""
  echo ">> Manually triggering Container Apps Job"
  az containerapp job start \
    --name "${JOB_NAME}" \
    --resource-group "${RG}"

  echo ""
  echo ">> Listing recent job executions"
  az containerapp job execution list \
    --name "${JOB_NAME}" \
    --resource-group "${RG}" \
    --output table

  echo ""
  echo ">> View Function App logs (last 50 lines):"
  echo "   az monitor app-insights query \\"
  echo "     --app brt-fleet-appinsights \\"
  echo "     --resource-group ${RG} \\"
  echo "     --analytics-query 'traces | order by timestamp desc | take 50'"

  echo ""
  echo ">> View Container Apps Job logs:"
  echo "   az containerapp job logs show \\"
  echo "     --name ${JOB_NAME} \\"
  echo "     --resource-group ${RG}"

else
  echo "Usage: $0 [local|azure]"
  exit 1
fi
