# Generated by GitHub Copilot
"""
BRT Fleet Movement – Phase 1 skeleton.
Python v2 programming model for Azure Durable Functions.

Components:
  - HTTP starter  : POST /api/start?runId=<id>
  - Orchestrator  : fleet_orchestrator
  - Activity      : print_start_activity
"""

import logging
import azure.functions as func
import azure.durable_functions as df
from datetime import datetime, timezone

# ---------------------------------------------------------------------------
# App registration
# ---------------------------------------------------------------------------
app = df.DFApp(http_auth_level=func.AuthLevel.ANONYMOUS)


# ---------------------------------------------------------------------------
# HTTP Starter – POST /api/start
# ---------------------------------------------------------------------------

@app.route(route="start", methods=["POST"])
@app.durable_client_input(client_name="client")
async def http_start(req: func.HttpRequest, client: df.DurableOrchestrationClient) -> func.HttpResponse:
    """
    Accepts POST /api/start?runId=<id>.
    Starts the fleet_orchestrator and returns HTTP 202 with instance metadata.

    Security note: runId is treated as opaque input and only used for logging.
    """
    run_id: str = req.params.get("runId", "UNKNOWN")

    # Input is logged but not executed – safe to pass as orchestrator input
    instance_id: str = await client.start_new("fleet_orchestrator", client_input=run_id)

    logging.info("Started orchestration | instanceId=%s | runId=%s", instance_id, run_id)

    return client.create_check_status_response(req, instance_id)


# ---------------------------------------------------------------------------
# Orchestrator – fleet_orchestrator
# ---------------------------------------------------------------------------

@app.orchestration_trigger(context_name="context")
def fleet_orchestrator(context: df.DurableOrchestrationContext):
    """
    Top-level orchestrator for the BRT fleet movement pipeline.
    Phase 1: single activity – prints a startup banner.
    """
    run_id: str = context.get_input()

    result: str = yield context.call_activity("print_start_activity", run_id)

    logging.info("Orchestrator completed | result=%s", result)
    return result


# ---------------------------------------------------------------------------
# Activity – print_start_activity
# ---------------------------------------------------------------------------

@app.activity_trigger(input_name="runId")
def print_start_activity(runId: str) -> str:
    """
    Phase 1 placeholder activity.
    Logs and prints a startup banner with UTC timestamp and runId.
    """
    utc_now: str = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    message: str = f"Flow started at {utc_now} | runId={runId}"

    # Dual-output so message appears in both App Insights traces and stdout
    logging.info(message)
    print(message)

    return message
