# Generated by GitHub Copilot
"""
Ops Dashboard Portal — FastAPI JSON API backend.

Reads run documents from ../fleet-agents/output/
Serves JSON API consumed by the React + TypeScript frontend (port 5173 dev).

HITL file bridge:
  Orchestrator writes : output/hitl_pending_{run_id}_{gate}.json
  Frontend polls      : GET  /api/runs/{run_id}/pending   (every 5 s)
  L2 submits decision : POST /api/runs/{run_id}/decision
  Portal writes       : output/hitl_decision_{run_id}_{gate}.json
  Orchestrator polls  : reads the decision file and resumes.

Start API (terminal 1):
  cd ops-dashboard-portal
  .venv/Scripts/uvicorn main:app --port 8080

Start frontend dev server (terminal 2):
  cd ops-dashboard-portal/frontend
  npm run dev
  -> http://localhost:5173   (proxies /api/* -> http://localhost:8080)
"""
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from dotenv import load_dotenv

load_dotenv()

# -- Path resolution -----------------------------------------------------------
_PORTAL_DIR    = Path(__file__).resolve().parent
_FLEET_DIR     = _PORTAL_DIR.parent / "fleet-agents"
_OUTPUT_DIR    = _FLEET_DIR / "output"
_FRONTEND_DIST = _PORTAL_DIR / "frontend" / "dist"

# Make the fleet-agents package importable so the portal can call the LLM agents
# (QAAgent, NLEditAgent). Load fleet-agents/.env first so config picks up the
# Azure OpenAI key and USE_MOCK_* flags.
if str(_FLEET_DIR) not in sys.path:
    sys.path.insert(0, str(_FLEET_DIR))
load_dotenv(_FLEET_DIR / ".env")


def _as_count(value) -> int:
    """Coerce a stored value (int count or list) into a count."""
    if isinstance(value, int):
        return value
    if isinstance(value, list):
        return len(value)
    return 0


def _build_run_context(run_id: str) -> dict:
    """Assemble a compact run context for the Q&A agent from the run document."""
    doc = _load_run(run_id) or {}
    steps = doc.get("steps", [])

    def _step_output(step_name: str) -> dict:
        for s in steps:
            if s.get("step") == step_name:
                return s.get("output") or {}
        return {}

    enrich_out = _step_output("stage2b_enrich")
    parse_out = _step_output("stage2_parse")
    recon_out = _step_output("stage5_reconcile")
    pending = _pending_gate(run_id) or {}
    # Enriched moves (with current SOTI folder) are richest; fall back to the
    # parse step, then to the live HITL-2 pending payload.
    moves = (enrich_out.get("intended_moves")
             or parse_out.get("intended_moves")
             or (pending.get("payload", {}) or {}).get("moves", []))
    return {
        "run_id": run_id,
        "state": doc.get("state", "unknown"),
        "current_step": doc.get("current_step", ""),
        "intended_moves": moves,
        "recon_result": {
            # stage5 stores counts under moved/unmoved/unidentified and the full
            # device lists under *_list keys — prefer the lists for the agent.
            "moved_count": _as_count(recon_out.get("moved")),
            "unmoved": recon_out.get("unmoved_list", []),
            "unidentified": recon_out.get("unidentified_list", []),
            "summary": recon_out.get("summary", ""),
        },
        "approvals": doc.get("approvals", []),
        "pending_gate": pending.get("gate", ""),
        "pending_payload": pending.get("payload", {}),
    }

app = FastAPI(title="BRT Fleet Movement -- Ops Dashboard API", version="2.0.0")

# CORS: allow Vite dev server origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8080",
    ],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# -- Helpers -------------------------------------------------------------------

def _load_all_runs() -> list[dict]:
    """Load all run documents from output dir, newest first."""
    runs = []
    for path in sorted(_OUTPUT_DIR.glob("run_*.json"), reverse=True):
        try:
            with open(path, encoding="utf-8") as f:
                runs.append(json.load(f))
        except Exception:
            pass
    return runs


def _load_run(run_id: str) -> dict | None:
    path = _OUTPUT_DIR / f"run_{run_id}.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _pending_gate(run_id: str) -> dict | None:
    """Return the first pending HITL gate for this run, or None."""
    for path in sorted(_OUTPUT_DIR.glob(f"hitl_pending_{run_id}_*.json")):
        try:
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return None


def _workbook_tabs(run_id: str) -> dict[str, list[list]]:
    """Read the 5-tab output workbook and return {tab: [[row], ...]}."""
    wb_path = _OUTPUT_DIR / f"BRT_FleetMovement_{run_id}.xlsx"
    if not wb_path.exists():
        return {}
    try:
        import openpyxl
        wb = openpyxl.load_workbook(str(wb_path), read_only=True)
        result: dict[str, list] = {}
        for sheet in wb.sheetnames:
            ws = wb[sheet]
            result[sheet] = [
                [str(c.value or "") for c in row]
                for row in ws.iter_rows()
            ]
        return result
    except Exception:
        return {}


# -- API Routes ----------------------------------------------------------------

@app.get("/api/runs")
async def api_runs():
    """List all runs, newest first."""
    return _load_all_runs()


@app.get("/api/runs/{run_id}")
async def api_run(run_id: str):
    """Get a single run document."""
    doc = _load_run(run_id)
    if not doc:
        return JSONResponse({"error": "not found"}, status_code=404)
    return doc


@app.get("/api/runs/{run_id}/pending")
async def api_pending(run_id: str):
    """Return pending HITL gate or {status: none}."""
    pending = _pending_gate(run_id)
    return pending or {"status": "none"}


@app.get("/api/runs/{run_id}/workbook")
async def api_workbook(run_id: str):
    """Return 5-tab output workbook as JSON: {tab_name: [[row], ...]}."""
    return _workbook_tabs(run_id)


@app.post("/api/runs/{run_id}/decision")
async def submit_decision(
    run_id: str,
    gate: str = Form(...),
    decision: str = Form(...),
    note: str = Form(""),
    subset_indices: str = Form(""),
):
    """L2 submits a HITL gate decision. Writes decision file, removes pending file."""
    safe_gate     = gate.replace(":", "_")
    decision_path = _OUTPUT_DIR / f"hitl_decision_{run_id}_{safe_gate}.json"
    pending_path  = _OUTPUT_DIR / f"hitl_pending_{run_id}_{safe_gate}.json"

    payload = {
        "run_id":         run_id,
        "gate":           gate,
        "decision":       decision,
        "note":           note,
        "subset_indices": [
            int(x.strip()) for x in subset_indices.split(",")
            if x.strip().isdigit()
        ],
        "decided_at":  datetime.now(timezone.utc).isoformat(),
        "decided_by":  "L2-ops-portal",
    }

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(decision_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    if pending_path.exists():
        pending_path.unlink()

    return {"status": "ok", "run_id": run_id, "gate": gate, "decision": decision}


# -- LLM-assisted endpoints (Q&A + NL edit accelerator) ------------------------
# These run synchronously (plain `def`) so FastAPI executes them in a threadpool
# and the blocking OpenAI SDK call doesn't stall the event loop. The agents are
# imported lazily so a missing dependency degrades gracefully to a JSON error.

@app.post("/api/runs/{run_id}/ask")
def ask_question(run_id: str, question: str = Form(...)):
    """Conversational Q&A over a single run's data (grounded in run context)."""
    try:
        from agents.portal import QAAgent
    except Exception as exc:  # noqa: BLE001
        return JSONResponse(
            {"error": f"QA agent unavailable: {exc}"}, status_code=503
        )
    try:
        context = _build_run_context(run_id)
        answer = QAAgent().answer(question, context)
        return {"run_id": run_id, "question": question, "answer": answer}
    except Exception as exc:  # noqa: BLE001
        return JSONResponse({"error": str(exc)}, status_code=500)


@app.post("/api/runs/{run_id}/nl-edit")
def nl_edit(run_id: str, instruction: str = Form(...)):
    """
    Parse a free-text reviewer instruction into PROPOSED, validated overlay edits
    against the current HITL-2 move list. Edits are never auto-applied — the
    operator still submits the actual decision via /decision.
    """
    try:
        from agents.portal import NLEditAgent
    except Exception as exc:  # noqa: BLE001
        return JSONResponse(
            {"error": f"NL-edit agent unavailable: {exc}"}, status_code=503
        )
    pending = _pending_gate(run_id) or {}
    moves = (pending.get("payload", {}) or {}).get("moves", [])
    if not moves:
        # Fall back to the persisted enriched move list (normalise key names)
        ctx = _build_run_context(run_id)
        moves = [
            {"index": i,
             "device": m.get("current_device") or m.get("device", ""),
             "bus": m.get("bus_number") or m.get("bus", ""),
             "target": m.get("target_folder") or m.get("target", "")}
            for i, m in enumerate(ctx.get("intended_moves", []))
        ]
    try:
        result = NLEditAgent().parse_edits(instruction, moves)
        return {"run_id": run_id, "instruction": instruction, **result}
    except Exception as exc:  # noqa: BLE001
        return JSONResponse({"error": str(exc)}, status_code=500)


# -- Serve React production build (deployment) --------------------------------
if _FRONTEND_DIST.exists():
    _assets = _FRONTEND_DIST / "assets"
    if _assets.exists():
        app.mount("/assets", StaticFiles(directory=str(_assets)), name="assets")

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):  # noqa: ARG001
        return FileResponse(str(_FRONTEND_DIST / "index.html"))
