# Generated by GitHub Copilot
"""
Ops Dashboard Portal — FastAPI JSON API backend.

Reads run documents from ../fleet-agents/output/
Serves JSON API consumed by the React + TypeScript frontend (port 5173 dev).

HITL file bridge:
  Orchestrator writes : output/hitl_pending_{run_id}_{gate}.json
  Frontend polls      : GET  /api/runs/{run_id}/pending   (every 5 s)
  L2 submits decision : POST /api/runs/{run_id}/decision
  Portal writes       : output/hitl_decision_{run_id}_{gate}.json
  Orchestrator polls  : reads the decision file and resumes.

Start API (terminal 1):
  cd ops-dashboard-portal
  .venv/Scripts/uvicorn main:app --port 8080

Start frontend dev server (terminal 2):
  cd ops-dashboard-portal/frontend
  npm run dev
  -> http://localhost:5173   (proxies /api/* -> http://localhost:8080)
"""
import json
from datetime import datetime, timezone
from pathlib import Path

from fastapi import FastAPI, Form
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse, FileResponse
from fastapi.staticfiles import StaticFiles
from dotenv import load_dotenv

load_dotenv()

# -- Path resolution -----------------------------------------------------------
_PORTAL_DIR    = Path(__file__).resolve().parent
_OUTPUT_DIR    = _PORTAL_DIR.parent / "fleet-agents" / "output"
_FRONTEND_DIST = _PORTAL_DIR / "frontend" / "dist"

app = FastAPI(title="BRT Fleet Movement -- Ops Dashboard API", version="2.0.0")

# CORS: allow Vite dev server origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=[
        "http://localhost:5173",
        "http://127.0.0.1:5173",
        "http://localhost:8080",
    ],
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)


# -- Helpers -------------------------------------------------------------------

def _load_all_runs() -> list[dict]:
    """Load all run documents from output dir, newest first."""
    runs = []
    for path in sorted(_OUTPUT_DIR.glob("run_*.json"), reverse=True):
        try:
            with open(path, encoding="utf-8") as f:
                runs.append(json.load(f))
        except Exception:
            pass
    return runs


def _load_run(run_id: str) -> dict | None:
    path = _OUTPUT_DIR / f"run_{run_id}.json"
    if not path.exists():
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def _pending_gate(run_id: str) -> dict | None:
    """Return the first pending HITL gate for this run, or None."""
    for path in sorted(_OUTPUT_DIR.glob(f"hitl_pending_{run_id}_*.json")):
        try:
            with open(path, encoding="utf-8") as f:
                return json.load(f)
        except Exception:
            pass
    return None


def _workbook_tabs(run_id: str) -> dict[str, list[list]]:
    """Read the 5-tab output workbook and return {tab: [[row], ...]}."""
    wb_path = _OUTPUT_DIR / f"BRT_FleetMovement_{run_id}.xlsx"
    if not wb_path.exists():
        return {}
    try:
        import openpyxl
        wb = openpyxl.load_workbook(str(wb_path), read_only=True)
        result: dict[str, list] = {}
        for sheet in wb.sheetnames:
            ws = wb[sheet]
            result[sheet] = [
                [str(c.value or "") for c in row]
                for row in ws.iter_rows()
            ]
        return result
    except Exception:
        return {}


# -- API Routes ----------------------------------------------------------------

@app.get("/api/runs")
async def api_runs():
    """List all runs, newest first."""
    return _load_all_runs()


@app.get("/api/runs/{run_id}")
async def api_run(run_id: str):
    """Get a single run document."""
    doc = _load_run(run_id)
    if not doc:
        return JSONResponse({"error": "not found"}, status_code=404)
    return doc


@app.get("/api/runs/{run_id}/pending")
async def api_pending(run_id: str):
    """Return pending HITL gate or {status: none}."""
    pending = _pending_gate(run_id)
    return pending or {"status": "none"}


@app.get("/api/runs/{run_id}/workbook")
async def api_workbook(run_id: str):
    """Return 5-tab output workbook as JSON: {tab_name: [[row], ...]}."""
    return _workbook_tabs(run_id)


@app.post("/api/runs/{run_id}/decision")
async def submit_decision(
    run_id: str,
    gate: str = Form(...),
    decision: str = Form(...),
    note: str = Form(""),
    subset_indices: str = Form(""),
):
    """L2 submits a HITL gate decision. Writes decision file, removes pending file."""
    safe_gate     = gate.replace(":", "_")
    decision_path = _OUTPUT_DIR / f"hitl_decision_{run_id}_{safe_gate}.json"
    pending_path  = _OUTPUT_DIR / f"hitl_pending_{run_id}_{safe_gate}.json"

    payload = {
        "run_id":         run_id,
        "gate":           gate,
        "decision":       decision,
        "note":           note,
        "subset_indices": [
            int(x.strip()) for x in subset_indices.split(",")
            if x.strip().isdigit()
        ],
        "decided_at":  datetime.now(timezone.utc).isoformat(),
        "decided_by":  "L2-ops-portal",
    }

    _OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    with open(decision_path, "w", encoding="utf-8") as f:
        json.dump(payload, f, indent=2)

    if pending_path.exists():
        pending_path.unlink()

    return {"status": "ok", "run_id": run_id, "gate": gate, "decision": decision}


# -- Serve React production build (deployment) --------------------------------
if _FRONTEND_DIST.exists():
    _assets = _FRONTEND_DIST / "assets"
    if _assets.exists():
        app.mount("/assets", StaticFiles(directory=str(_assets)), name="assets")

    @app.get("/{full_path:path}")
    async def serve_spa(full_path: str):  # noqa: ARG001
        return FileResponse(str(_FRONTEND_DIST / "index.html"))
