# Generated by GitHub Copilot
"""
Idempotent agent provisioning — create once, reuse by name on every run.
Agents are narrators ONLY; they receive structured JSON and return plain prose.
No tools are attached to any agent — orchestrator owns all tool calls.
"""
import config

# ── System instructions for each narrator ────────────────────────────────────

_PARSER_INSTRUCTIONS = (
    "You generate a concise plain-English summary for a Level 2 operations "
    "person reviewing BRT Fleet device movements. You receive a structured "
    "list of intended moves and any parsing issues. You produce a 3-4 "
    "sentence summary highlighting total counts, target folder breakdown, "
    "and any issues that need attention. Do NOT make decisions or "
    "recommendations about moves — only narrate the data."
)

_RECON_INSTRUCTIONS = (
    "You generate a concise plain-English reconciliation report for a Level 2 "
    "operations person. You receive lists of successfully moved devices, "
    "unmoved devices with reasons, and unidentified devices. Produce a 3-5 "
    "sentence summary of what succeeded, what failed, and why. "
    "Do NOT make decisions — only narrate the results."
)

_EXEC_INSTRUCTIONS = (
    "You draft a ServiceNow SR note and summary email for a BRT Fleet device "
    "movement operation. Given the list of moved devices and a run ID, "
    "produce professional, factual, concise notes suitable for an IT "
    "operations SR record. Do NOT invent device names or data not present "
    "in the input."
)


def _get_or_create(client, name: str, instructions: str):
    """Fetch existing agent by name, or create it if absent (idempotent)."""
    agents_client = client.agents
    for agent in agents_client.list_agents():
        if agent.name == name:
            return agent
    return agents_client.create_agent(
        model=config.AZURE_OPENAI_DEPLOYMENT,
        name=name,
        instructions=instructions,
    )


def get_or_create_parser_narrator(client):
    """Idempotently provision the DVA parser narrator agent."""
    return _get_or_create(client, "brt-parser-narrator-v1", _PARSER_INSTRUCTIONS)


def get_or_create_recon_narrator(client):
    """Idempotently provision the reconciliation narrator agent."""
    return _get_or_create(client, "brt-recon-narrator-v1", _RECON_INSTRUCTIONS)


def get_or_create_execution_narrator(client):
    """Idempotently provision the SR / email execution narrator agent."""
    return _get_or_create(client, "brt-execution-narrator-v1", _EXEC_INSTRUCTIONS)
