# Generated by GitHub Copilot
"""
Returns a configured AIProjectClient using DefaultAzureCredential.
Requires FOUNDRY_PROJECT_CONNECTION_STRING to be set.

Security: no API keys — uses DefaultAzureCredential (Managed Identity / az login).
"""
import config


def get_project_client():
    """
    Create and return an AIProjectClient for agent lifecycle management.

    Raises RuntimeError if FOUNDRY_PROJECT_CONNECTION_STRING is not configured —
    this prevents silent fallback to anonymous access.
    """
    from azure.ai.projects import AIProjectClient
    from azure.identity import DefaultAzureCredential

    if not config.FOUNDRY_PROJECT_CONNECTION_STRING:
        raise RuntimeError(
            "FOUNDRY_PROJECT_CONNECTION_STRING not set — "
            "Azure AI Developer role required. "
            "Keep USE_MOCK_LLM=True until the role is assigned."
        )

    return AIProjectClient.from_connection_string(
        conn_str=config.FOUNDRY_PROJECT_CONNECTION_STRING,
        credential=DefaultAzureCredential(),
    )
